// Auto-generated by scripts/generateCategoryCrossSell.js — last update: 2026-04-18
// SK: category pair co-occurrence from orders

export interface CategoryCrossSellPair {
  catA: string;
  catB: string;
  count: number;
  pct: number;
}

export interface CategoryCrossSellData {
  totalOrders: number;
  multiItemOrders: number;
  catPairs: CategoryCrossSellPair[];
  subCatPairs: CategoryCrossSellPair[];
}

export const categoryCrossSellDataSK: CategoryCrossSellData = {
  "totalOrders": 23030,
  "multiItemOrders": 17445,
  "catPairs": [
    {
      "catA": "Spotrebný materiál pre štúdiá",
      "catB": "Tetovanie",
      "count": 5152,
      "pct": 22.37
    },
    {
      "catA": "Farby na tetovanie",
      "catB": "Spotrebný materiál pre štúdiá",
      "count": 3683,
      "pct": 15.99
    },
    {
      "catA": "Farby na tetovanie",
      "catB": "Tetovanie",
      "count": 3474,
      "pct": 15.08
    },
    {
      "catA": "Permanentný make-up",
      "catB": "Spotrebný materiál pre štúdiá",
      "count": 3354,
      "pct": 14.56
    },
    {
      "catA": "Permanentný make-up",
      "catB": "Tetovanie",
      "count": 2146,
      "pct": 9.32
    },
    {
      "catA": "Farby na tetovanie",
      "catB": "Permanentný make-up",
      "count": 1306,
      "pct": 5.67
    },
    {
      "catA": "Piercing",
      "catB": "Spotrebný materiál pre štúdiá",
      "count": 648,
      "pct": 2.81
    },
    {
      "catA": "Piercing",
      "catB": "Tetovanie",
      "count": 376,
      "pct": 1.63
    },
    {
      "catA": "Permanentný make-up",
      "catB": "Piercing",
      "count": 295,
      "pct": 1.28
    },
    {
      "catA": "Farby na tetovanie",
      "catB": "Piercing",
      "count": 235,
      "pct": 1.02
    },
    {
      "catA": "Tetovanie",
      "catB": "Špeciálna ponuka",
      "count": 36,
      "pct": 0.16
    },
    {
      "catA": "Spotrebný materiál pre štúdiá",
      "catB": "Špeciálna ponuka",
      "count": 30,
      "pct": 0.13
    },
    {
      "catA": "Farby na tetovanie",
      "catB": "Špeciálna ponuka",
      "count": 28,
      "pct": 0.12
    },
    {
      "catA": "Permanentný make-up",
      "catB": "sady",
      "count": 19,
      "pct": 0.08
    },
    {
      "catA": "Permanentný make-up",
      "catB": "Špeciálna ponuka",
      "count": 13,
      "pct": 0.06
    },
    {
      "catA": "Spotrebný materiál pre štúdiá",
      "catB": "sady",
      "count": 13,
      "pct": 0.06
    },
    {
      "catA": "Farby na tetovanie",
      "catB": "sady",
      "count": 12,
      "pct": 0.05
    },
    {
      "catA": "Tetovanie",
      "catB": "sady",
      "count": 4,
      "pct": 0.02
    },
    {
      "catA": "Piercing",
      "catB": "Špeciálna ponuka",
      "count": 3,
      "pct": 0.01
    },
    {
      "catA": "Piercing",
      "catB": "sady",
      "count": 1,
      "pct": 0
    }
  ],
  "subCatPairs": [
    {
      "catA": "Farby na tetovanie › EÚ schválené tetovacie farby",
      "catB": "Tetovanie › Tetovacie cartridge",
      "count": 1776,
      "pct": 7.71
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Pomôcky na prenos motívu",
      "catB": "Tetovanie › Tetovacie cartridge",
      "count": 1067,
      "pct": 4.63
    },
    {
      "catA": "Farby na tetovanie › EÚ schválené tetovacie farby",
      "catB": "Spotrebný materiál pre štúdiá › Pomôcky na prenos motívu",
      "count": 867,
      "pct": 3.76
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Jednorazové rukavice",
      "catB": "Tetovanie › Tetovacie cartridge",
      "count": 758,
      "pct": 3.29
    },
    {
      "catA": "Farby na tetovanie › Príslušenstvo k farbám",
      "catB": "Tetovanie › Tetovacie cartridge",
      "count": 721,
      "pct": 3.13
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Ostatné",
      "catB": "Tetovanie › Tetovacie cartridge",
      "count": 651,
      "pct": 2.83
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Mydlá a peny",
      "catB": "Tetovanie › Tetovacie cartridge",
      "count": 649,
      "pct": 2.82
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Dezinfekcia",
      "catB": "Tetovanie › Tetovacie cartridge",
      "count": 626,
      "pct": 2.72
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Hojivé fólie a tattoo finish",
      "catB": "Tetovanie › Tetovacie cartridge",
      "count": 555,
      "pct": 2.41
    },
    {
      "catA": "Farby na tetovanie › EÚ schválené tetovacie farby",
      "catB": "Farby na tetovanie › Príslušenstvo k farbám",
      "count": 522,
      "pct": 2.27
    },
    {
      "catA": "Permanentný make-up › Pigmenty",
      "catB": "Permanentný make-up › Príslušenstvo k PMU",
      "count": 493,
      "pct": 2.14
    },
    {
      "catA": "Farby na tetovanie › EÚ schválené tetovacie farby",
      "catB": "Spotrebný materiál pre štúdiá › Ostatné",
      "count": 483,
      "pct": 2.1
    },
    {
      "catA": "Farby na tetovanie › EÚ schválené tetovacie farby",
      "catB": "Spotrebný materiál pre štúdiá › Mydlá a peny",
      "count": 477,
      "pct": 2.07
    },
    {
      "catA": "Permanentný make-up › Cartridge pre PMU",
      "catB": "Tetovanie › Tetovacie cartridge",
      "count": 445,
      "pct": 1.93
    },
    {
      "catA": "Farby na tetovanie › EÚ schválené tetovacie farby",
      "catB": "Spotrebný materiál pre štúdiá › Jednorazové rukavice",
      "count": 445,
      "pct": 1.93
    },
    {
      "catA": "Farby na tetovanie › EÚ schválené tetovacie farby",
      "catB": "Spotrebný materiál pre štúdiá › Dezinfekcia",
      "count": 439,
      "pct": 1.91
    },
    {
      "catA": "Permanentný make-up › Cartridge pre PMU",
      "catB": "Permanentný make-up › Pigmenty",
      "count": 416,
      "pct": 1.81
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Dezinfekcia",
      "catB": "Spotrebný materiál pre štúdiá › Jednorazové rukavice",
      "count": 412,
      "pct": 1.79
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Ostatné",
      "catB": "Spotrebný materiál pre štúdiá › Pomôcky na prenos motívu",
      "count": 410,
      "pct": 1.78
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Dezinfekcia",
      "catB": "Spotrebný materiál pre štúdiá › Mydlá a peny",
      "count": 409,
      "pct": 1.78
    },
    {
      "catA": "Farby na tetovanie › Príslušenstvo k farbám",
      "catB": "Spotrebný materiál pre štúdiá › Ostatné",
      "count": 408,
      "pct": 1.77
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Dezinfekcia",
      "catB": "Spotrebný materiál pre štúdiá › Pomôcky na prenos motívu",
      "count": 407,
      "pct": 1.77
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Vazelíny, maslá",
      "catB": "Tetovanie › Tetovacie cartridge",
      "count": 407,
      "pct": 1.77
    },
    {
      "catA": "Farby na tetovanie › EÚ schválené tetovacie farby",
      "catB": "Spotrebný materiál pre štúdiá › Hojivé fólie a tattoo finish",
      "count": 405,
      "pct": 1.76
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Jednorazové rukavice",
      "catB": "Spotrebný materiál pre štúdiá › Pomôcky na prenos motívu",
      "count": 394,
      "pct": 1.71
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Mydlá a peny",
      "catB": "Spotrebný materiál pre štúdiá › Pomôcky na prenos motívu",
      "count": 387,
      "pct": 1.68
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Jednorazové rukavice",
      "catB": "Spotrebný materiál pre štúdiá › Mydlá a peny",
      "count": 383,
      "pct": 1.66
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Jednorazové rukavice",
      "catB": "Spotrebný materiál pre štúdiá › Ostatné",
      "count": 380,
      "pct": 1.65
    },
    {
      "catA": "Farby na tetovanie › Príslušenstvo k farbám",
      "catB": "Spotrebný materiál pre štúdiá › Pomôcky na prenos motívu",
      "count": 374,
      "pct": 1.62
    },
    {
      "catA": "Farby na tetovanie › Príslušenstvo k farbám",
      "catB": "Spotrebný materiál pre štúdiá › Jednorazové rukavice",
      "count": 368,
      "pct": 1.6
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Mydlá a peny",
      "catB": "Spotrebný materiál pre štúdiá › Ostatné",
      "count": 367,
      "pct": 1.59
    },
    {
      "catA": "Tetovanie › Starostlivosť o tetovanie",
      "catB": "Tetovanie › Tetovacie cartridge",
      "count": 351,
      "pct": 1.52
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Vrecká, obaly",
      "catB": "Tetovanie › Tetovacie cartridge",
      "count": 343,
      "pct": 1.49
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Dezinfekcia",
      "catB": "Spotrebný materiál pre štúdiá › Ostatné",
      "count": 341,
      "pct": 1.48
    },
    {
      "catA": "Permanentný make-up › Príslušenstvo k PMU",
      "catB": "Permanentný make-up › Zákres a procedúra PMU",
      "count": 340,
      "pct": 1.48
    },
    {
      "catA": "Farby na tetovanie › Príslušenstvo k farbám",
      "catB": "Spotrebný materiál pre štúdiá › Mydlá a peny",
      "count": 330,
      "pct": 1.43
    },
    {
      "catA": "Farby na tetovanie › EÚ schválené tetovacie farby",
      "catB": "Tetovanie › Gripy, tubusy, špičky",
      "count": 325,
      "pct": 1.41
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Hojivé fólie a tattoo finish",
      "catB": "Spotrebný materiál pre štúdiá › Pomôcky na prenos motívu",
      "count": 317,
      "pct": 1.38
    },
    {
      "catA": "Farby na tetovanie › Príslušenstvo k farbám",
      "catB": "Spotrebný materiál pre štúdiá › Dezinfekcia",
      "count": 312,
      "pct": 1.35
    },
    {
      "catA": "Farby na tetovanie › EÚ schválené tetovacie farby",
      "catB": "Spotrebný materiál pre štúdiá › Vazelíny, maslá",
      "count": 295,
      "pct": 1.28
    },
    {
      "catA": "Permanentný make-up › Pigmenty",
      "catB": "Tetovanie › Tetovacie cartridge",
      "count": 290,
      "pct": 1.26
    },
    {
      "catA": "Farby na tetovanie › Umelecké farby",
      "catB": "Tetovanie › Tetovacie cartridge",
      "count": 289,
      "pct": 1.25
    },
    {
      "catA": "Permanentný make-up › Pigmenty",
      "catB": "Permanentný make-up › Zákres a procedúra PMU",
      "count": 286,
      "pct": 1.24
    },
    {
      "catA": "Permanentný make-up › Cartridge pre PMU",
      "catB": "Permanentný make-up › Príslušenstvo k PMU",
      "count": 281,
      "pct": 1.22
    },
    {
      "catA": "Permanentný make-up › Príslušenstvo k PMU",
      "catB": "Tetovanie › Tetovacie cartridge",
      "count": 278,
      "pct": 1.21
    },
    {
      "catA": "Farby na tetovanie › Príslušenstvo k farbám",
      "catB": "Permanentný make-up › Príslušenstvo k PMU",
      "count": 266,
      "pct": 1.16
    },
    {
      "catA": "Farby na tetovanie › EÚ schválené tetovacie farby",
      "catB": "Farby na tetovanie › Umelecké farby",
      "count": 256,
      "pct": 1.11
    },
    {
      "catA": "Farby na tetovanie › EÚ schválené tetovacie farby",
      "catB": "Tetovanie › Starostlivosť o tetovanie",
      "count": 252,
      "pct": 1.09
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Pomôcky na prenos motívu",
      "catB": "Spotrebný materiál pre štúdiá › Vazelíny, maslá",
      "count": 249,
      "pct": 1.08
    },
    {
      "catA": "Permanentný make-up › Príslušenstvo k PMU",
      "catB": "Spotrebný materiál pre štúdiá › Jednorazové rukavice",
      "count": 239,
      "pct": 1.04
    },
    {
      "catA": "Permanentný make-up › Príslušenstvo k PMU",
      "catB": "Spotrebný materiál pre štúdiá › Ostatné",
      "count": 239,
      "pct": 1.04
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Dezinfekcia",
      "catB": "Spotrebný materiál pre štúdiá › Hojivé fólie a tattoo finish",
      "count": 224,
      "pct": 0.97
    },
    {
      "catA": "Permanentný make-up › Príslušenstvo k PMU",
      "catB": "Spotrebný materiál pre štúdiá › Dezinfekcia",
      "count": 219,
      "pct": 0.95
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Mydlá a peny",
      "catB": "Spotrebný materiál pre štúdiá › Vazelíny, maslá",
      "count": 215,
      "pct": 0.93
    },
    {
      "catA": "Permanentný make-up › Príslušenstvo k PMU",
      "catB": "Spotrebný materiál pre štúdiá › Mydlá a peny",
      "count": 213,
      "pct": 0.92
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Hojivé fólie a tattoo finish",
      "catB": "Spotrebný materiál pre štúdiá › Jednorazové rukavice",
      "count": 211,
      "pct": 0.92
    },
    {
      "catA": "Farby na tetovanie › Príslušenstvo k farbám",
      "catB": "Permanentný make-up › Pigmenty",
      "count": 208,
      "pct": 0.9
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Ostatné",
      "catB": "Spotrebný materiál pre štúdiá › Vrecká, obaly",
      "count": 208,
      "pct": 0.9
    },
    {
      "catA": "Farby na tetovanie › Príslušenstvo k farbám",
      "catB": "Permanentný make-up › Cartridge pre PMU",
      "count": 204,
      "pct": 0.89
    },
    {
      "catA": "Farby na tetovanie › EÚ schválené tetovacie farby",
      "catB": "Spotrebný materiál pre štúdiá › Vrecká, obaly",
      "count": 202,
      "pct": 0.88
    },
    {
      "catA": "Permanentný make-up › Pigmenty",
      "catB": "Spotrebný materiál pre štúdiá › Mydlá a peny",
      "count": 200,
      "pct": 0.87
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Hojivé fólie a tattoo finish",
      "catB": "Spotrebný materiál pre štúdiá › Mydlá a peny",
      "count": 200,
      "pct": 0.87
    },
    {
      "catA": "Permanentný make-up › Pigmenty",
      "catB": "Spotrebný materiál pre štúdiá › Dezinfekcia",
      "count": 194,
      "pct": 0.84
    },
    {
      "catA": "Farby na tetovanie › Príslušenstvo k farbám",
      "catB": "Permanentný make-up › Zákres a procedúra PMU",
      "count": 193,
      "pct": 0.84
    },
    {
      "catA": "Permanentný make-up › Cartridge pre PMU",
      "catB": "Permanentný make-up › Zákres a procedúra PMU",
      "count": 192,
      "pct": 0.83
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Dezinfekcia",
      "catB": "Spotrebný materiál pre štúdiá › Vrecká, obaly",
      "count": 190,
      "pct": 0.83
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Dezinfekcia",
      "catB": "Spotrebný materiál pre štúdiá › Vazelíny, maslá",
      "count": 190,
      "pct": 0.83
    },
    {
      "catA": "Farby na tetovanie › Príslušenstvo k farbám",
      "catB": "Spotrebný materiál pre štúdiá › Vrecká, obaly",
      "count": 189,
      "pct": 0.82
    },
    {
      "catA": "Tetovanie › Tetovacie cartridge",
      "catB": "Tetovanie › Tetovacie strojčeky",
      "count": 179,
      "pct": 0.78
    },
    {
      "catA": "Permanentný make-up › Pigmenty",
      "catB": "Spotrebný materiál pre štúdiá › Jednorazové rukavice",
      "count": 176,
      "pct": 0.76
    },
    {
      "catA": "Tetovanie › Handpoke",
      "catB": "Tetovanie › Tetovacie cartridge",
      "count": 175,
      "pct": 0.76
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Jednorazové rukavice",
      "catB": "Spotrebný materiál pre štúdiá › Vazelíny, maslá",
      "count": 174,
      "pct": 0.76
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Jednorazové rukavice",
      "catB": "Spotrebný materiál pre štúdiá › Vrecká, obaly",
      "count": 174,
      "pct": 0.76
    },
    {
      "catA": "Farby na tetovanie › Príslušenstvo k farbám",
      "catB": "Spotrebný materiál pre štúdiá › Hojivé fólie a tattoo finish",
      "count": 172,
      "pct": 0.75
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Ostatné",
      "catB": "Spotrebný materiál pre štúdiá › Vazelíny, maslá",
      "count": 171,
      "pct": 0.74
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Pomôcky na prenos motívu",
      "catB": "Tetovanie › Gripy, tubusy, špičky",
      "count": 170,
      "pct": 0.74
    },
    {
      "catA": "Permanentný make-up › Pigmenty",
      "catB": "Permanentný make-up › Starostlivosť o PMU",
      "count": 169,
      "pct": 0.73
    },
    {
      "catA": "Permanentný make-up › Zákres a procedúra PMU",
      "catB": "Spotrebný materiál pre štúdiá › Ostatné",
      "count": 168,
      "pct": 0.73
    },
    {
      "catA": "Piercing › Piercingové ihly - Kanyly",
      "catB": "Piercing › Piercingové šperky",
      "count": 168,
      "pct": 0.73
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Pomôcky na prenos motívu",
      "catB": "Spotrebný materiál pre štúdiá › Vrecká, obaly",
      "count": 164,
      "pct": 0.71
    },
    {
      "catA": "Permanentný make-up › Cartridge pre PMU",
      "catB": "Spotrebný materiál pre štúdiá › Ostatné",
      "count": 164,
      "pct": 0.71
    },
    {
      "catA": "Farby na tetovanie › Príslušenstvo k farbám",
      "catB": "Spotrebný materiál pre štúdiá › Vazelíny, maslá",
      "count": 162,
      "pct": 0.7
    },
    {
      "catA": "Permanentný make-up › Zákres a procedúra PMU",
      "catB": "Tetovanie › Tetovacie cartridge",
      "count": 162,
      "pct": 0.7
    },
    {
      "catA": "Permanentný make-up › Cartridge pre PMU",
      "catB": "Spotrebný materiál pre štúdiá › Mydlá a peny",
      "count": 158,
      "pct": 0.69
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Pomôcky na prenos motívu",
      "catB": "Tetovanie › Starostlivosť o tetovanie",
      "count": 157,
      "pct": 0.68
    },
    {
      "catA": "Permanentný make-up › Príslušenstvo k PMU",
      "catB": "Permanentný make-up › Starostlivosť o PMU",
      "count": 153,
      "pct": 0.66
    },
    {
      "catA": "Permanentný make-up › Pigmenty",
      "catB": "Spotrebný materiál pre štúdiá › Ostatné",
      "count": 149,
      "pct": 0.65
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Hojivé fólie a tattoo finish",
      "catB": "Spotrebný materiál pre štúdiá › Ostatné",
      "count": 148,
      "pct": 0.64
    },
    {
      "catA": "Piercing › Piercingové ihly - Kanyly",
      "catB": "Piercing › Piercingové nástroje",
      "count": 146,
      "pct": 0.63
    },
    {
      "catA": "Permanentný make-up › Cartridge pre PMU",
      "catB": "Spotrebný materiál pre štúdiá › Jednorazové rukavice",
      "count": 145,
      "pct": 0.63
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Holítka, podložky",
      "catB": "Tetovanie › Tetovacie cartridge",
      "count": 145,
      "pct": 0.63
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Dezinfekcia",
      "catB": "Tetovanie › Starostlivosť o tetovanie",
      "count": 143,
      "pct": 0.62
    },
    {
      "catA": "Permanentný make-up › Zákres a procedúra PMU",
      "catB": "Spotrebný materiál pre štúdiá › Mydlá a peny",
      "count": 143,
      "pct": 0.62
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Mydlá a peny",
      "catB": "Spotrebný materiál pre štúdiá › Vrecká, obaly",
      "count": 141,
      "pct": 0.61
    },
    {
      "catA": "Farby na tetovanie › EÚ schválené tetovacie farby",
      "catB": "Tetovanie › Tetovacie strojčeky",
      "count": 139,
      "pct": 0.6
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Jednorazové rukavice",
      "catB": "Tetovanie › Starostlivosť o tetovanie",
      "count": 137,
      "pct": 0.59
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Hojivé fólie a tattoo finish",
      "catB": "Tetovanie › Starostlivosť o tetovanie",
      "count": 135,
      "pct": 0.59
    },
    {
      "catA": "Spotrebný materiál pre štúdiá › Mydlá a peny",
      "catB": "Tetovanie › Starostlivosť o tetovanie",
      "count": 134,
      "pct": 0.58
    },
    {
      "catA": "Farby na tetovanie › Umelecké farby",
      "catB": "Spotrebný materiál pre štúdiá › Pomôcky na prenos motívu",
      "count": 133,
      "pct": 0.58
    },
    {
      "catA": "Permanentný make-up › Cartridge pre PMU",
      "catB": "Spotrebný materiál pre štúdiá › Dezinfekcia",
      "count": 133,
      "pct": 0.58
    }
  ]
};
