// Auto-generated by scripts/generateCategoryCrossSell.js — last update: 2026-04-18
// NL: category pair co-occurrence from orders

export interface CategoryCrossSellPair {
  catA: string;
  catB: string;
  count: number;
  pct: number;
}

export interface CategoryCrossSellData {
  totalOrders: number;
  multiItemOrders: number;
  catPairs: CategoryCrossSellPair[];
  subCatPairs: CategoryCrossSellPair[];
}

export const categoryCrossSellDataNL: CategoryCrossSellData = {
  "totalOrders": 11,
  "multiItemOrders": 5,
  "catPairs": [
    {
      "catA": "Permanente make-up",
      "catB": "Verbruiksartikelen voor studio's",
      "count": 1,
      "pct": 9.09
    },
    {
      "catA": "Permanente make-up",
      "catB": "Tatoeagekleuren",
      "count": 1,
      "pct": 9.09
    },
    {
      "catA": "Tatoeagekleuren",
      "catB": "Verbruiksartikelen voor studio's",
      "count": 1,
      "pct": 9.09
    }
  ],
  "subCatPairs": [
    {
      "catA": "Permanente make-up › Cartridge voor PMU",
      "catB": "Permanente make-up › EU-goedgekeurde pigmenten",
      "count": 1,
      "pct": 9.09
    },
    {
      "catA": "Permanente make-up › PMU-zorg",
      "catB": "Verbruiksartikelen voor studio's › Zeep, schuim",
      "count": 1,
      "pct": 9.09
    },
    {
      "catA": "Permanente make-up › PMU-zorg",
      "catB": "Verbruiksartikelen voor studio's › Helende folies en tattoo finish",
      "count": 1,
      "pct": 9.09
    },
    {
      "catA": "Permanente make-up › PMU-zorg",
      "catB": "Verbruiksartikelen voor studio's › Hulpmiddelen voor het overbrengen van motieven",
      "count": 1,
      "pct": 9.09
    },
    {
      "catA": "Permanente make-up › PMU-zorg",
      "catB": "Verbruiksartikelen voor studio's › Vaseline, boter",
      "count": 1,
      "pct": 9.09
    },
    {
      "catA": "Permanente make-up › PMU-zorg",
      "catB": "Tatoeagekleuren › EU-goedgekeurde tatoeage-inkten",
      "count": 1,
      "pct": 9.09
    },
    {
      "catA": "Verbruiksartikelen voor studio's › Helende folies en tattoo finish",
      "catB": "Verbruiksartikelen voor studio's › Zeep, schuim",
      "count": 1,
      "pct": 9.09
    },
    {
      "catA": "Verbruiksartikelen voor studio's › Hulpmiddelen voor het overbrengen van motieven",
      "catB": "Verbruiksartikelen voor studio's › Zeep, schuim",
      "count": 1,
      "pct": 9.09
    },
    {
      "catA": "Verbruiksartikelen voor studio's › Vaseline, boter",
      "catB": "Verbruiksartikelen voor studio's › Zeep, schuim",
      "count": 1,
      "pct": 9.09
    },
    {
      "catA": "Tatoeagekleuren › EU-goedgekeurde tatoeage-inkten",
      "catB": "Verbruiksartikelen voor studio's › Zeep, schuim",
      "count": 1,
      "pct": 9.09
    },
    {
      "catA": "Verbruiksartikelen voor studio's › Helende folies en tattoo finish",
      "catB": "Verbruiksartikelen voor studio's › Hulpmiddelen voor het overbrengen van motieven",
      "count": 1,
      "pct": 9.09
    },
    {
      "catA": "Verbruiksartikelen voor studio's › Helende folies en tattoo finish",
      "catB": "Verbruiksartikelen voor studio's › Vaseline, boter",
      "count": 1,
      "pct": 9.09
    },
    {
      "catA": "Tatoeagekleuren › EU-goedgekeurde tatoeage-inkten",
      "catB": "Verbruiksartikelen voor studio's › Helende folies en tattoo finish",
      "count": 1,
      "pct": 9.09
    },
    {
      "catA": "Verbruiksartikelen voor studio's › Hulpmiddelen voor het overbrengen van motieven",
      "catB": "Verbruiksartikelen voor studio's › Vaseline, boter",
      "count": 1,
      "pct": 9.09
    },
    {
      "catA": "Tatoeagekleuren › EU-goedgekeurde tatoeage-inkten",
      "catB": "Verbruiksartikelen voor studio's › Hulpmiddelen voor het overbrengen van motieven",
      "count": 1,
      "pct": 9.09
    },
    {
      "catA": "Tatoeagekleuren › EU-goedgekeurde tatoeage-inkten",
      "catB": "Verbruiksartikelen voor studio's › Vaseline, boter",
      "count": 1,
      "pct": 9.09
    }
  ]
};
