// Auto-generated by scripts/generateCategoryCrossSell.js — last update: 2026-04-18
// CZ: category pair co-occurrence from orders

export interface CategoryCrossSellPair {
  catA: string;
  catB: string;
  count: number;
  pct: number;
}

export interface CategoryCrossSellData {
  totalOrders: number;
  multiItemOrders: number;
  catPairs: CategoryCrossSellPair[];
  subCatPairs: CategoryCrossSellPair[];
}

export const categoryCrossSellDataCZ: CategoryCrossSellData = {
  "totalOrders": 7775,
  "multiItemOrders": 6020,
  "catPairs": [
    {
      "catA": "Spotřební materiál pro studia",
      "catB": "Tetování",
      "count": 2714,
      "pct": 34.91
    },
    {
      "catA": "Barvy na tetování",
      "catB": "Spotřební materiál pro studia",
      "count": 1527,
      "pct": 19.64
    },
    {
      "catA": "Barvy na tetování",
      "catB": "Tetování",
      "count": 1386,
      "pct": 17.83
    },
    {
      "catA": "Permanentní make-up",
      "catB": "Spotřební materiál pro studia",
      "count": 858,
      "pct": 11.04
    },
    {
      "catA": "Permanentní make-up",
      "catB": "Tetování",
      "count": 538,
      "pct": 6.92
    },
    {
      "catA": "Barvy na tetování",
      "catB": "Permanentní make-up",
      "count": 287,
      "pct": 3.69
    },
    {
      "catA": "Piercing",
      "catB": "Spotřební materiál pro studia",
      "count": 254,
      "pct": 3.27
    },
    {
      "catA": "Piercing",
      "catB": "Tetování",
      "count": 189,
      "pct": 2.43
    },
    {
      "catA": "Permanentní make-up",
      "catB": "Piercing",
      "count": 92,
      "pct": 1.18
    },
    {
      "catA": "Barvy na tetování",
      "catB": "Piercing",
      "count": 85,
      "pct": 1.09
    },
    {
      "catA": "Speciální nabídka",
      "catB": "Spotřební materiál pro studia",
      "count": 10,
      "pct": 0.13
    },
    {
      "catA": "Speciální nabídka",
      "catB": "Tetování",
      "count": 7,
      "pct": 0.09
    },
    {
      "catA": "Permanentní make-up",
      "catB": "Speciální nabídka",
      "count": 3,
      "pct": 0.04
    },
    {
      "catA": "Barvy na tetování",
      "catB": "Speciální nabídka",
      "count": 3,
      "pct": 0.04
    },
    {
      "catA": "Sety",
      "catB": "Tetování",
      "count": 1,
      "pct": 0.01
    }
  ],
  "subCatPairs": [
    {
      "catA": "Barvy na tetování › EU schválené tetovací barvy",
      "catB": "Tetování › Tetovací cartridge",
      "count": 1015,
      "pct": 13.05
    },
    {
      "catA": "Spotřební materiál pro studia › Pomůcky pro přenos motivu",
      "catB": "Tetování › Tetovací cartridge",
      "count": 823,
      "pct": 10.59
    },
    {
      "catA": "Spotřební materiál pro studia › Ostatní",
      "catB": "Tetování › Tetovací cartridge",
      "count": 763,
      "pct": 9.81
    },
    {
      "catA": "Spotřební materiál pro studia › Jednorázové rukavice",
      "catB": "Tetování › Tetovací cartridge",
      "count": 567,
      "pct": 7.29
    },
    {
      "catA": "Spotřební materiál pro studia › Dezinfekce",
      "catB": "Tetování › Tetovací cartridge",
      "count": 526,
      "pct": 6.77
    },
    {
      "catA": "Spotřební materiál pro studia › Hojivé fólie a tattoo finish",
      "catB": "Tetování › Tetovací cartridge",
      "count": 512,
      "pct": 6.59
    },
    {
      "catA": "Barvy na tetování › EU schválené tetovací barvy",
      "catB": "Spotřební materiál pro studia › Pomůcky pro přenos motivu",
      "count": 481,
      "pct": 6.19
    },
    {
      "catA": "Spotřební materiál pro studia › Kalíšky, kelímky",
      "catB": "Tetování › Tetovací cartridge",
      "count": 455,
      "pct": 5.85
    },
    {
      "catA": "Spotřební materiál pro studia › Sáčky, obaly",
      "catB": "Tetování › Tetovací cartridge",
      "count": 440,
      "pct": 5.66
    },
    {
      "catA": "Spotřební materiál pro studia › Ostatní",
      "catB": "Spotřební materiál pro studia › Pomůcky pro přenos motivu",
      "count": 418,
      "pct": 5.38
    },
    {
      "catA": "Spotřební materiál pro studia › Mýdla, pěny",
      "catB": "Tetování › Tetovací cartridge",
      "count": 410,
      "pct": 5.27
    },
    {
      "catA": "Spotřební materiál pro studia › Holítka, podložky",
      "catB": "Tetování › Tetovací cartridge",
      "count": 402,
      "pct": 5.17
    },
    {
      "catA": "Barvy na tetování › EU schválené tetovací barvy",
      "catB": "Spotřební materiál pro studia › Ostatní",
      "count": 395,
      "pct": 5.08
    },
    {
      "catA": "Spotřební materiál pro studia › Jednorázové rukavice",
      "catB": "Spotřební materiál pro studia › Ostatní",
      "count": 342,
      "pct": 4.4
    },
    {
      "catA": "Spotřební materiál pro studia › Dezinfekce",
      "catB": "Spotřební materiál pro studia › Ostatní",
      "count": 337,
      "pct": 4.33
    },
    {
      "catA": "Spotřební materiál pro studia › Ostatní",
      "catB": "Spotřební materiál pro studia › Sáčky, obaly",
      "count": 311,
      "pct": 4
    },
    {
      "catA": "Spotřební materiál pro studia › Dezinfekce",
      "catB": "Spotřební materiál pro studia › Pomůcky pro přenos motivu",
      "count": 304,
      "pct": 3.91
    },
    {
      "catA": "Barvy na tetování › EU schválené tetovací barvy",
      "catB": "Spotřební materiál pro studia › Dezinfekce",
      "count": 295,
      "pct": 3.79
    },
    {
      "catA": "Spotřební materiál pro studia › Vazelíny, másla",
      "catB": "Tetování › Tetovací cartridge",
      "count": 294,
      "pct": 3.78
    },
    {
      "catA": "Barvy na tetování › EU schválené tetovací barvy",
      "catB": "Spotřební materiál pro studia › Kalíšky, kelímky",
      "count": 291,
      "pct": 3.74
    },
    {
      "catA": "Spotřební materiál pro studia › Dezinfekce",
      "catB": "Spotřební materiál pro studia › Jednorázové rukavice",
      "count": 283,
      "pct": 3.64
    },
    {
      "catA": "Spotřební materiál pro studia › Kalíšky, kelímky",
      "catB": "Spotřební materiál pro studia › Ostatní",
      "count": 274,
      "pct": 3.52
    },
    {
      "catA": "Spotřební materiál pro studia › Jednorázové rukavice",
      "catB": "Spotřební materiál pro studia › Pomůcky pro přenos motivu",
      "count": 274,
      "pct": 3.52
    },
    {
      "catA": "Permanentní make-up › Cartridge pro PMU",
      "catB": "Tetování › Tetovací cartridge",
      "count": 269,
      "pct": 3.46
    },
    {
      "catA": "Barvy na tetování › EU schválené tetovací barvy",
      "catB": "Spotřební materiál pro studia › Hojivé fólie a tattoo finish",
      "count": 267,
      "pct": 3.43
    },
    {
      "catA": "Barvy na tetování › EU schválené tetovací barvy",
      "catB": "Spotřební materiál pro studia › Jednorázové rukavice",
      "count": 266,
      "pct": 3.42
    },
    {
      "catA": "Spotřební materiál pro studia › Mýdla, pěny",
      "catB": "Spotřební materiál pro studia › Ostatní",
      "count": 259,
      "pct": 3.33
    },
    {
      "catA": "Barvy na tetování › EU schválené tetovací barvy",
      "catB": "Spotřební materiál pro studia › Mýdla, pěny",
      "count": 256,
      "pct": 3.29
    },
    {
      "catA": "Spotřební materiál pro studia › Holítka, podložky",
      "catB": "Spotřební materiál pro studia › Ostatní",
      "count": 248,
      "pct": 3.19
    },
    {
      "catA": "Spotřební materiál pro studia › Dezinfekce",
      "catB": "Spotřební materiál pro studia › Sáčky, obaly",
      "count": 248,
      "pct": 3.19
    },
    {
      "catA": "Barvy na tetování › Příslušenství k barvám",
      "catB": "Tetování › Tetovací cartridge",
      "count": 247,
      "pct": 3.18
    },
    {
      "catA": "Spotřební materiál pro studia › Hojivé fólie a tattoo finish",
      "catB": "Spotřební materiál pro studia › Pomůcky pro přenos motivu",
      "count": 246,
      "pct": 3.16
    },
    {
      "catA": "Spotřební materiál pro studia › Kalíšky, kelímky",
      "catB": "Spotřební materiál pro studia › Pomůcky pro přenos motivu",
      "count": 242,
      "pct": 3.11
    },
    {
      "catA": "Spotřební materiál pro studia › Pomůcky pro přenos motivu",
      "catB": "Spotřební materiál pro studia › Sáčky, obaly",
      "count": 230,
      "pct": 2.96
    },
    {
      "catA": "Tetování › Péče o tetování",
      "catB": "Tetování › Tetovací cartridge",
      "count": 227,
      "pct": 2.92
    },
    {
      "catA": "Spotřební materiál pro studia › Mýdla, pěny",
      "catB": "Spotřební materiál pro studia › Pomůcky pro přenos motivu",
      "count": 223,
      "pct": 2.87
    },
    {
      "catA": "Spotřební materiál pro studia › Jednorázové rukavice",
      "catB": "Spotřební materiál pro studia › Sáčky, obaly",
      "count": 220,
      "pct": 2.83
    },
    {
      "catA": "Barvy na tetování › EU schválené tetovací barvy",
      "catB": "Spotřební materiál pro studia › Sáčky, obaly",
      "count": 217,
      "pct": 2.79
    },
    {
      "catA": "Spotřební materiál pro studia › Hojivé fólie a tattoo finish",
      "catB": "Spotřební materiál pro studia › Ostatní",
      "count": 215,
      "pct": 2.77
    },
    {
      "catA": "Spotřební materiál pro studia › Holítka, podložky",
      "catB": "Spotřební materiál pro studia › Pomůcky pro přenos motivu",
      "count": 210,
      "pct": 2.7
    },
    {
      "catA": "Spotřební materiál pro studia › Dezinfekce",
      "catB": "Spotřební materiál pro studia › Kalíšky, kelímky",
      "count": 207,
      "pct": 2.66
    },
    {
      "catA": "Spotřební materiál pro studia › Dezinfekce",
      "catB": "Spotřební materiál pro studia › Mýdla, pěny",
      "count": 201,
      "pct": 2.59
    },
    {
      "catA": "Barvy na tetování › EU schválené tetovací barvy",
      "catB": "Spotřební materiál pro studia › Holítka, podložky",
      "count": 200,
      "pct": 2.57
    },
    {
      "catA": "Spotřební materiál pro studia › Dezinfekce",
      "catB": "Spotřební materiál pro studia › Holítka, podložky",
      "count": 199,
      "pct": 2.56
    },
    {
      "catA": "Spotřební materiál pro studia › Dezinfekce",
      "catB": "Spotřební materiál pro studia › Hojivé fólie a tattoo finish",
      "count": 192,
      "pct": 2.47
    },
    {
      "catA": "Barvy na tetování › EU schválené tetovací barvy",
      "catB": "Barvy na tetování › Příslušenství k barvám",
      "count": 190,
      "pct": 2.44
    },
    {
      "catA": "Spotřební materiál pro studia › Holítka, podložky",
      "catB": "Spotřební materiál pro studia › Jednorázové rukavice",
      "count": 189,
      "pct": 2.43
    },
    {
      "catA": "Spotřební materiál pro studia › Holítka, podložky",
      "catB": "Spotřební materiál pro studia › Sáčky, obaly",
      "count": 188,
      "pct": 2.42
    },
    {
      "catA": "Spotřební materiál pro studia › Jednorázové rukavice",
      "catB": "Spotřební materiál pro studia › Kalíšky, kelímky",
      "count": 186,
      "pct": 2.39
    },
    {
      "catA": "Barvy na tetování › EU schválené tetovací barvy",
      "catB": "Spotřební materiál pro studia › Vazelíny, másla",
      "count": 185,
      "pct": 2.38
    },
    {
      "catA": "Spotřební materiál pro studia › Ostatní",
      "catB": "Spotřební materiál pro studia › Vazelíny, másla",
      "count": 173,
      "pct": 2.23
    },
    {
      "catA": "Spotřební materiál pro studia › Jednorázové rukavice",
      "catB": "Spotřební materiál pro studia › Mýdla, pěny",
      "count": 173,
      "pct": 2.23
    },
    {
      "catA": "Spotřební materiál pro studia › Kalíšky, kelímky",
      "catB": "Spotřební materiál pro studia › Sáčky, obaly",
      "count": 161,
      "pct": 2.07
    },
    {
      "catA": "Spotřební materiál pro studia › Holítka, podložky",
      "catB": "Spotřební materiál pro studia › Kalíšky, kelímky",
      "count": 160,
      "pct": 2.06
    },
    {
      "catA": "Permanentní make-up › Cartridge pro PMU",
      "catB": "Permanentní make-up › EU Schválené pigmenty",
      "count": 158,
      "pct": 2.03
    },
    {
      "catA": "Spotřební materiál pro studia › Hojivé fólie a tattoo finish",
      "catB": "Spotřební materiál pro studia › Sáčky, obaly",
      "count": 155,
      "pct": 1.99
    },
    {
      "catA": "Spotřební materiál pro studia › Pomůcky pro přenos motivu",
      "catB": "Spotřební materiál pro studia › Vazelíny, másla",
      "count": 153,
      "pct": 1.97
    },
    {
      "catA": "Spotřební materiál pro studia › Hojivé fólie a tattoo finish",
      "catB": "Spotřební materiál pro studia › Jednorázové rukavice",
      "count": 153,
      "pct": 1.97
    },
    {
      "catA": "Barvy na tetování › Příslušenství k barvám",
      "catB": "Spotřební materiál pro studia › Ostatní",
      "count": 150,
      "pct": 1.93
    },
    {
      "catA": "Spotřební materiál pro studia › Hojivé fólie a tattoo finish",
      "catB": "Spotřební materiál pro studia › Holítka, podložky",
      "count": 150,
      "pct": 1.93
    },
    {
      "catA": "Spotřební materiál pro studia › Hojivé fólie a tattoo finish",
      "catB": "Spotřební materiál pro studia › Mýdla, pěny",
      "count": 146,
      "pct": 1.88
    },
    {
      "catA": "Spotřební materiál pro studia › Mýdla, pěny",
      "catB": "Spotřební materiál pro studia › Sáčky, obaly",
      "count": 145,
      "pct": 1.86
    },
    {
      "catA": "Spotřební materiál pro studia › Hojivé fólie a tattoo finish",
      "catB": "Spotřební materiál pro studia › Kalíšky, kelímky",
      "count": 144,
      "pct": 1.85
    },
    {
      "catA": "Spotřební materiál pro studia › Kalíšky, kelímky",
      "catB": "Spotřební materiál pro studia › Mýdla, pěny",
      "count": 143,
      "pct": 1.84
    },
    {
      "catA": "Permanentní make-up › Cartridge pro PMU",
      "catB": "Spotřební materiál pro studia › Ostatní",
      "count": 140,
      "pct": 1.8
    },
    {
      "catA": "Spotřební materiál pro studia › Dezinfekce",
      "catB": "Spotřební materiál pro studia › Vazelíny, másla",
      "count": 137,
      "pct": 1.76
    },
    {
      "catA": "Barvy na tetování › EU schválené tetovací barvy",
      "catB": "Tetování › Péče o tetování",
      "count": 132,
      "pct": 1.7
    },
    {
      "catA": "Barvy na tetování › Příslušenství k barvám",
      "catB": "Spotřební materiál pro studia › Kalíšky, kelímky",
      "count": 129,
      "pct": 1.66
    },
    {
      "catA": "Spotřební materiál pro studia › Mýdla, pěny",
      "catB": "Spotřební materiál pro studia › Vazelíny, másla",
      "count": 129,
      "pct": 1.66
    },
    {
      "catA": "Spotřební materiál pro studia › Ostatní",
      "catB": "Tetování › Péče o tetování",
      "count": 128,
      "pct": 1.65
    },
    {
      "catA": "Barvy na tetování › Příslušenství k barvám",
      "catB": "Spotřební materiál pro studia › Pomůcky pro přenos motivu",
      "count": 123,
      "pct": 1.58
    },
    {
      "catA": "Permanentní make-up › Cartridge pro PMU",
      "catB": "Spotřební materiál pro studia › Jednorázové rukavice",
      "count": 122,
      "pct": 1.57
    },
    {
      "catA": "Spotřební materiál pro studia › Jednorázové rukavice",
      "catB": "Spotřební materiál pro studia › Vazelíny, másla",
      "count": 115,
      "pct": 1.48
    },
    {
      "catA": "Spotřební materiál pro studia › Holítka, podložky",
      "catB": "Spotřební materiál pro studia › Mýdla, pěny",
      "count": 114,
      "pct": 1.47
    },
    {
      "catA": "Permanentní make-up › Cartridge pro PMU",
      "catB": "Spotřební materiál pro studia › Mýdla, pěny",
      "count": 111,
      "pct": 1.43
    },
    {
      "catA": "Spotřební materiál pro studia › Kalíšky, kelímky",
      "catB": "Spotřební materiál pro studia › Vazelíny, másla",
      "count": 109,
      "pct": 1.4
    },
    {
      "catA": "Tetování › Tetovací cartridge",
      "catB": "Tetování › Tetovací strojky",
      "count": 104,
      "pct": 1.34
    },
    {
      "catA": "Permanentní make-up › Cartridge pro PMU",
      "catB": "Permanentní make-up › Péče o PMU",
      "count": 103,
      "pct": 1.32
    },
    {
      "catA": "Permanentní make-up › Cartridge pro PMU",
      "catB": "Spotřební materiál pro studia › Dezinfekce",
      "count": 103,
      "pct": 1.32
    },
    {
      "catA": "Barvy na tetování › Příslušenství k barvám",
      "catB": "Spotřební materiál pro studia › Dezinfekce",
      "count": 103,
      "pct": 1.32
    },
    {
      "catA": "Spotřební materiál pro studia › Hojivé fólie a tattoo finish",
      "catB": "Spotřební materiál pro studia › Vazelíny, másla",
      "count": 102,
      "pct": 1.31
    },
    {
      "catA": "Spotřební materiál pro studia › Sáčky, obaly",
      "catB": "Spotřební materiál pro studia › Vazelíny, másla",
      "count": 100,
      "pct": 1.29
    },
    {
      "catA": "Spotřební materiál pro studia › Hojivé fólie a tattoo finish",
      "catB": "Tetování › Péče o tetování",
      "count": 100,
      "pct": 1.29
    },
    {
      "catA": "Permanentní make-up › Cartridge pro PMU",
      "catB": "Spotřební materiál pro studia › Sáčky, obaly",
      "count": 96,
      "pct": 1.23
    },
    {
      "catA": "Spotřební materiál pro studia › Dezinfekce",
      "catB": "Tetování › Péče o tetování",
      "count": 96,
      "pct": 1.23
    },
    {
      "catA": "Spotřební materiál pro studia › Jednorázové rukavice",
      "catB": "Tetování › Péče o tetování",
      "count": 93,
      "pct": 1.2
    },
    {
      "catA": "Barvy na tetování › EU schválené tetovací barvy",
      "catB": "Permanentní make-up › Cartridge pro PMU",
      "count": 92,
      "pct": 1.18
    },
    {
      "catA": "Barvy na tetování › Příslušenství k barvám",
      "catB": "Spotřební materiál pro studia › Jednorázové rukavice",
      "count": 88,
      "pct": 1.13
    },
    {
      "catA": "Permanentní make-up › Cartridge pro PMU",
      "catB": "Spotřební materiál pro studia › Kalíšky, kelímky",
      "count": 88,
      "pct": 1.13
    },
    {
      "catA": "Permanentní make-up › Cartridge pro PMU",
      "catB": "Spotřební materiál pro studia › Holítka, podložky",
      "count": 87,
      "pct": 1.12
    },
    {
      "catA": "Permanentní make-up › Cartridge pro PMU",
      "catB": "Permanentní make-up › Příslušenství k PMU",
      "count": 87,
      "pct": 1.12
    },
    {
      "catA": "Spotřební materiál pro studia › Pomůcky pro přenos motivu",
      "catB": "Tetování › Péče o tetování",
      "count": 86,
      "pct": 1.11
    },
    {
      "catA": "Spotřební materiál pro studia › Mýdla, pěny",
      "catB": "Tetování › Péče o tetování",
      "count": 85,
      "pct": 1.09
    },
    {
      "catA": "Piercing › Piercingové jehly - Kanyly",
      "catB": "Piercing › Piercingové šperky",
      "count": 83,
      "pct": 1.07
    },
    {
      "catA": "Barvy na tetování › Umělecké barvy",
      "catB": "Tetování › Tetovací cartridge",
      "count": 82,
      "pct": 1.05
    },
    {
      "catA": "Barvy na tetování › Příslušenství k barvám",
      "catB": "Spotřební materiál pro studia › Hojivé fólie a tattoo finish",
      "count": 76,
      "pct": 0.98
    },
    {
      "catA": "Barvy na tetování › Příslušenství k barvám",
      "catB": "Permanentní make-up › Cartridge pro PMU",
      "count": 76,
      "pct": 0.98
    },
    {
      "catA": "Barvy na tetování › Příslušenství k barvám",
      "catB": "Spotřební materiál pro studia › Mýdla, pěny",
      "count": 75,
      "pct": 0.96
    },
    {
      "catA": "Spotřební materiál pro studia › Holítka, podložky",
      "catB": "Spotřební materiál pro studia › Vazelíny, másla",
      "count": 74,
      "pct": 0.95
    },
    {
      "catA": "Permanentní make-up › Cartridge pro PMU",
      "catB": "Spotřební materiál pro studia › Pomůcky pro přenos motivu",
      "count": 74,
      "pct": 0.95
    }
  ]
};
