// Auto-generated by scripts/fetchShoptetData.js — last update: 2026-04-18
// AT: product pair co-occurrence from orders

export interface CrossSellPair {
  productA: string;
  productB: string;
  count: number;
  pct: number;
}

export interface CrossSellData {
  totalOrders: number;
  multiItemOrders: number;
  pairs: CrossSellPair[];
}

export const crossSellDataAT: CrossSellData = {
  "totalOrders": 3444,
  "multiItemOrders": 2423,
  "pairs": [
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 586,
      "pct": 17.015098722415793
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Bishop DaVinci V2 Liner",
      "count": 422,
      "pct": 12.253193960511034
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Cheyenne Safety Liner",
      "count": 336,
      "pct": 9.75609756097561
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Round Shader Long Taper",
      "count": 318,
      "pct": 9.233449477351916
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Cheyenne Safety Liner",
      "count": 280,
      "pct": 8.130081300813007
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Bishop DaVinci V2 Round Shader",
      "count": 276,
      "pct": 8.013937282229964
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Bishop DaVinci V2 Liner",
      "count": 274,
      "pct": 7.955865272938444
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 234,
      "pct": 6.794425087108014
    },
    {
      "productA": "Bishop DaVinci V2 Magnum",
      "productB": "Cheyenne Safety Liner",
      "count": 230,
      "pct": 6.678281068524972
    },
    {
      "productA": "Kwadron Cartridges Round Liner Long Taper",
      "productB": "Kwadron Cartridges Round Liner Long Taper",
      "count": 205,
      "pct": 5.952380952380952
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Cheyenne Safety Liner",
      "count": 184,
      "pct": 5.342624854819976
    },
    {
      "productA": "Kwadron Cartridges Round Shader Long Taper",
      "productB": "Kwadron Cartridges Round Shader Long Taper",
      "count": 177,
      "pct": 5.139372822299651
    },
    {
      "productA": "Kwadron Magnum Long Taper",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 173,
      "pct": 5.023228803716608
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Bishop DaVinci V2 Magnum",
      "count": 164,
      "pct": 4.761904761904762
    },
    {
      "productA": "Bishop DaVinci V2 Round Shader",
      "productB": "Cheyenne Safety Liner",
      "count": 138,
      "pct": 4.006968641114982
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Soft Edge Medium taper",
      "count": 130,
      "pct": 3.7746806039488967
    },
    {
      "productA": "Kwadron Round Shader Long Taper",
      "productB": "Kwadron Round Shader Long Taper",
      "count": 114,
      "pct": 3.3101045296167246
    },
    {
      "productA": "Kwadron Soft Edge Long Taper",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 113,
      "pct": 3.281068524970964
    },
    {
      "productA": "Piranha Liner Nadeln Round Liner - 5 Stück",
      "productB": "Piranha Liner Nadeln Round Liner - 5 Stück",
      "count": 108,
      "pct": 3.1358885017421603
    },
    {
      "productA": "Kwadron Magnum Medium Taper",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 106,
      "pct": 3.077816492450639
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Bishop DaVinci V2 Curved Magnum",
      "count": 105,
      "pct": 3.048780487804878
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Bishop DaVinci V2 Magnum",
      "count": 103,
      "pct": 2.9907084785133566
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Bishop DaVinci V2 Round Shader",
      "count": 101,
      "pct": 2.9326364692218347
    },
    {
      "productA": "Kwadron Cartridges PMU Optima Liner",
      "productB": "Kwadron Cartridges PMU Optima Liner",
      "count": 99,
      "pct": 2.8745644599303137
    },
    {
      "productA": "Kwadron Cartridges Round Liner Long Taper",
      "productB": "Kwadron Cartridges Round Shader Long Taper",
      "count": 95,
      "pct": 2.7584204413472704
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Round Liner",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 94,
      "pct": 2.72938443670151
    },
    {
      "productA": "Bishop DaVinci V2 Round Shader",
      "productB": "Bishop DaVinci V2 Round Shader",
      "count": 90,
      "pct": 2.6132404181184667
    },
    {
      "productA": "CRAFT Liner Cartridges",
      "productB": "CRAFT Magnum Soft Edge",
      "count": 90,
      "pct": 2.6132404181184667
    },
    {
      "productA": "Cartridge Mast Ocean Heart",
      "productB": "Cartridge Mast Ocean Heart",
      "count": 88,
      "pct": 2.5551684088269457
    },
    {
      "productA": "Cartridge Mast Ocean Heart",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 88,
      "pct": 2.5551684088269457
    },
    {
      "productA": "Kwadron Round Shader Long Taper",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 86,
      "pct": 2.497096399535424
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron cartridge PMU Optima Liner",
      "count": 86,
      "pct": 2.497096399535424
    },
    {
      "productA": "Kwadron cartridge PMU Optima Liner",
      "productB": "Kwadron cartridge PMU Optima Liner",
      "count": 85,
      "pct": 2.468060394889663
    },
    {
      "productA": "Kwadron Magnum Long Taper",
      "productB": "Kwadron Round Shader Long Taper",
      "count": 83,
      "pct": 2.4099883855981417
    },
    {
      "productA": "Kwadron Magnum Medium Taper",
      "productB": "Kwadron Round Shader Long Taper",
      "count": 82,
      "pct": 2.380952380952381
    },
    {
      "productA": "CRAFT Liner Cartridges",
      "productB": "CRAFT Liner Cartridges",
      "count": 80,
      "pct": 2.3228803716608595
    },
    {
      "productA": "CRAFT Magnum Soft Edge",
      "productB": "CRAFT Magnum Soft Edge",
      "count": 77,
      "pct": 2.2357723577235773
    },
    {
      "productA": "Kwadron Round Shader Long Taper",
      "productB": "Kwadron Soft Edge Medium taper",
      "count": 68,
      "pct": 1.9744483159117305
    },
    {
      "productA": "Kwadron Cartridges Round Shader Long Taper",
      "productB": "Kwadron Cartridges Soft Edge Long Taper Sublime",
      "count": 64,
      "pct": 1.8583042973286876
    },
    {
      "productA": "Bishop DaVinci V2 Magnum",
      "productB": "Bishop DaVinci V2 Round Shader",
      "count": 64,
      "pct": 1.8583042973286876
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Soft Edge Long Taper Sublime",
      "count": 63,
      "pct": 1.8292682926829267
    },
    {
      "productA": "EZ INkin REVO Round Liner",
      "productB": "EZ INkin REVO Round Liner",
      "count": 62,
      "pct": 1.8002322880371662
    },
    {
      "productA": "Kwadron Cartridges Round Liner Long Taper",
      "productB": "Kwadron Cartridges Soft Edge runde Schattierung Long taper",
      "count": 60,
      "pct": 1.7421602787456445
    },
    {
      "productA": "Bishop DaVinci V2 Magnum",
      "productB": "Bishop DaVinci V2 Magnum",
      "count": 60,
      "pct": 1.7421602787456445
    },
    {
      "productA": "Piranha Liner Nadeln Round Liner - 5 Stück",
      "productB": "Piranha Schattierungsnadeln Round Shader - 5Stück",
      "count": 60,
      "pct": 1.7421602787456445
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Curved Magnum",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 58,
      "pct": 1.684088269454123
    },
    {
      "productA": "Kwadron Round Liner Medium Taper",
      "productB": "Kwadron Round Liner Medium Taper",
      "count": 57,
      "pct": 1.6550522648083623
    },
    {
      "productA": "Kwadron Soft Edge Medium taper",
      "productB": "Kwadron Soft Edge Medium taper",
      "count": 57,
      "pct": 1.6550522648083623
    },
    {
      "productA": "Cartridge Mast Ocean Heart",
      "productB": "Kwadron Cartridges PMU Optima Liner",
      "count": 56,
      "pct": 1.6260162601626018
    },
    {
      "productA": "TOMBOW Körper Marker",
      "productB": "TOMBOW Körper Marker",
      "count": 55,
      "pct": 1.5969802555168409
    },
    {
      "productA": "Cartridge Mast Ocean Heart",
      "productB": "Kwadron cartridge PMU Optima Liner",
      "count": 54,
      "pct": 1.5679442508710801
    },
    {
      "productA": "CRAFT Magnum Soft Edge",
      "productB": "CRAFT Magnum flache zweireihige Cartridges",
      "count": 52,
      "pct": 1.5098722415795587
    },
    {
      "productA": "EZ INkin REVO Round Liner",
      "productB": "EZ INkin REVO Round Shader",
      "count": 51,
      "pct": 1.480836236933798
    },
    {
      "productA": "Kwadron Magnum Long Taper",
      "productB": "Kwadron Magnum Long Taper",
      "count": 51,
      "pct": 1.480836236933798
    },
    {
      "productA": "Cheyenne Safety Open Liner - Strong lining Cartridges",
      "productB": "Cheyenne Safety Open Liner - Strong lining Cartridges",
      "count": 50,
      "pct": 1.4518002322880372
    },
    {
      "productA": "Dragonhawk MAST Pro 2 Round Liner",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 50,
      "pct": 1.4518002322880372
    },
    {
      "productA": "EZ INkin REVO Magnum",
      "productB": "Kwadron Cartridges Round Shader Long Taper",
      "count": 48,
      "pct": 1.3937282229965158
    },
    {
      "productA": "EZ Tattoo Supply EZ REVOLUTION Round Liner Long Taper 0,35mm",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 48,
      "pct": 1.3937282229965158
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 47,
      "pct": 1.364692218350755
    },
    {
      "productA": "Farbkappen - Ink Cups",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 45,
      "pct": 1.3066202090592334
    },
    {
      "productA": "Farbkappen - Ink Cups",
      "productB": "Farbkappen - Ink Cups",
      "count": 44,
      "pct": 1.2775842044134729
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Cheyenne Safety Open Liner - Strong lining Cartridges",
      "count": 44,
      "pct": 1.2775842044134729
    },
    {
      "productA": "Kwadron Cartridges Round Liner Long Taper",
      "productB": "Kwadron Cartridges Soft Edge Long Taper Sublime",
      "count": 43,
      "pct": 1.248548199767712
    },
    {
      "productA": "Elite III Round Liner",
      "productB": "Elite III Round Liner",
      "count": 43,
      "pct": 1.248548199767712
    },
    {
      "productA": "SQUIDSTER Körpermarkers",
      "productB": "SQUIDSTER Körpermarkers",
      "count": 43,
      "pct": 1.248548199767712
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Round Shader Medium Taper",
      "count": 43,
      "pct": 1.248548199767712
    },
    {
      "productA": "Cheyenne Safety Liner - Liner cartridge",
      "productB": "Cheyenne Safety Liner - Liner cartridge",
      "count": 42,
      "pct": 1.2195121951219512
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Round Liner",
      "productB": "Emalla Eliot Pro Cartridge Round Shader",
      "count": 42,
      "pct": 1.2195121951219512
    },
    {
      "productA": "Kwadron Round Liner Medium Taper",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 42,
      "pct": 1.2195121951219512
    },
    {
      "productA": "Piranha Schattierungsnadeln Round Shader - 5Stück",
      "productB": "Piranha Schattierungsnadeln Round Shader - 5Stück",
      "count": 41,
      "pct": 1.1904761904761905
    },
    {
      "productA": "Dragonhawk YUE Round Liner",
      "productB": "Dragonhawk YUE Round Liner",
      "count": 41,
      "pct": 1.1904761904761905
    },
    {
      "productA": "Dragonhawk MAST Pro Round Liner",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 41,
      "pct": 1.1904761904761905
    },
    {
      "productA": "Kwadron Cartridges Magnum Long Taper",
      "productB": "Kwadron Cartridges Round Liner Long Taper",
      "count": 40,
      "pct": 1.1614401858304297
    },
    {
      "productA": "Griff Bandage - Grip Wrap",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 40,
      "pct": 1.1614401858304297
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Griff Bandage - Grip Wrap",
      "count": 39,
      "pct": 1.132404181184669
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Stencil Stuff",
      "count": 39,
      "pct": 1.132404181184669
    },
    {
      "productA": "CRAFT Liner Cartridges",
      "productB": "CRAFT Shader Cartridge",
      "count": 39,
      "pct": 1.132404181184669
    },
    {
      "productA": "Kwadron Magnum Long Taper",
      "productB": "Kwadron Magnum Medium Taper",
      "count": 39,
      "pct": 1.132404181184669
    },
    {
      "productA": "Dragonhawk YUE Round Liner",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 38,
      "pct": 1.1033681765389083
    },
    {
      "productA": "Kwadron Magnum Medium Taper",
      "productB": "Kwadron Soft Edge Medium taper",
      "count": 38,
      "pct": 1.1033681765389083
    },
    {
      "productA": "Kwadron Magnum Long Taper",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 37,
      "pct": 1.0743321718931476
    },
    {
      "productA": "CRAFT Magnum Soft Edge",
      "productB": "Cheyenne Safety Liner",
      "count": 37,
      "pct": 1.0743321718931476
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Round Liner Medium Taper",
      "count": 36,
      "pct": 1.0452961672473868
    },
    {
      "productA": "EZ Tattoo Supply EZ REVOLUTION Round Liner Long Taper 0,35mm",
      "productB": "Kwadron Soft Edge Long Taper Sublime",
      "count": 36,
      "pct": 1.0452961672473868
    },
    {
      "productA": "Kwadron Round Liner Medium Taper",
      "productB": "Kwadron Soft Edge Medium taper",
      "count": 36,
      "pct": 1.0452961672473868
    },
    {
      "productA": "PEPAX LANCE Round Liner",
      "productB": "PEPAX LANCE Round Liner",
      "count": 36,
      "pct": 1.0452961672473868
    },
    {
      "productA": "EZ REVOLUTION Magnum Long Taper Bug Pin 0,30mm",
      "productB": "EZ REVOLUTION Round Liner Long Taper 0,35mm",
      "count": 36,
      "pct": 1.0452961672473868
    },
    {
      "productA": "ECLIPSE TATTOO INK Total Black 150ml",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 35,
      "pct": 1.0162601626016259
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Cheyenne Safety Shader",
      "count": 35,
      "pct": 1.0162601626016259
    },
    {
      "productA": "Piranha Revolution Round Liner Long Taper",
      "productB": "Piranha Revolution Round Shader Long Taper",
      "count": 34,
      "pct": 0.9872241579558653
    },
    {
      "productA": "EZ INkin REVO Curved Magnum",
      "productB": "EZ INkin REVO Round Liner",
      "count": 34,
      "pct": 0.9872241579558653
    },
    {
      "productA": "CRAFT Liner Cartridges",
      "productB": "CRAFT Magnum flache zweireihige Cartridges",
      "count": 34,
      "pct": 0.9872241579558653
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Cheyenne Safety Shader",
      "count": 34,
      "pct": 0.9872241579558653
    },
    {
      "productA": "Griff Bandage - Grip Wrap",
      "productB": "Griff Bandage - Grip Wrap",
      "count": 33,
      "pct": 0.9581881533101044
    },
    {
      "productA": "CRAFT Magnum flache zweireihige Cartridges",
      "productB": "CRAFT Magnum flache zweireihige Cartridges",
      "count": 33,
      "pct": 0.9581881533101044
    },
    {
      "productA": "Kwadron Round Liner Medium Taper",
      "productB": "Kwadron Round Shader Long Taper",
      "count": 33,
      "pct": 0.9581881533101044
    },
    {
      "productA": "ELITE Infini Round Liner",
      "productB": "ELITE Infini Round Liner",
      "count": 31,
      "pct": 0.9001161440185831
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Farbkappen - Ink Cups",
      "count": 31,
      "pct": 0.9001161440185831
    },
    {
      "productA": "Kwadron Magnum Medium Taper",
      "productB": "Kwadron Magnum Medium Taper",
      "count": 31,
      "pct": 0.9001161440185831
    },
    {
      "productA": "Kwadron Cartridges Round Liner Medium Taper",
      "productB": "Kwadron Cartridges Soft Edge Long Taper Sublime",
      "count": 30,
      "pct": 0.8710801393728222
    }
  ]
};
