// Auto-generated by scripts/fetchShoptetData.js — last update: 2026-04-17
// PL: product pair co-occurrence from orders

export interface CrossSellPair {
  productA: string;
  productB: string;
  count: number;
  pct: number;
}

export interface CrossSellData {
  totalOrders: number;
  multiItemOrders: number;
  pairs: CrossSellPair[];
}

export const crossSellDataPL: CrossSellData = {
  "totalOrders": 10655,
  "multiItemOrders": 5824,
  "pairs": [
    {
      "productA": "PEPAX LANCE Round Liner",
      "productB": "PEPAX LANCE Round Liner",
      "count": 888,
      "pct": 8.334115438761144
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Bishop DaVinci V2 Liner",
      "count": 652,
      "pct": 6.119192867198498
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Round Liner",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 508,
      "pct": 4.767714687939934
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Cheyenne Safety Liner",
      "count": 471,
      "pct": 4.420459877991553
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Bishop DaVinci V2 Curved Magnum",
      "count": 358,
      "pct": 3.35992491787893
    },
    {
      "productA": "PEPAX LANCE Round Liner",
      "productB": "PEPAX LANCE Round Shader",
      "count": 316,
      "pct": 2.965743782261849
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 284,
      "pct": 2.6654152979821677
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Bishop DaVinci V2 Round Shader",
      "count": 283,
      "pct": 2.656030032848428
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Round Liner",
      "productB": "Emalla Eliot Pro Cartridge Round Shader",
      "count": 263,
      "pct": 2.4683247301736273
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Bishop DaVinci V2 Liner",
      "count": 244,
      "pct": 2.290004692632567
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Curved Magnum",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 243,
      "pct": 2.280619427498827
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Cheyenne Safety Soft Edge zaokrąglona końcówka płaska",
      "count": 242,
      "pct": 2.271234162365087
    },
    {
      "productA": "Cheyenne Safety Liner - Liner Cartride",
      "productB": "Cheyenne Safety Liner - Liner Cartride",
      "count": 214,
      "pct": 2.008446738620366
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Bishop DaVinci V2 Round Shader",
      "count": 206,
      "pct": 1.9333646175504458
    },
    {
      "productA": "Dragonhawk YUE Round Liner",
      "productB": "Dragonhawk YUE Round Liner",
      "count": 201,
      "pct": 1.8864382918817455
    },
    {
      "productA": "PEPAX LANCE Curved Magnum",
      "productB": "PEPAX LANCE Round Liner",
      "count": 193,
      "pct": 1.8113561708118255
    },
    {
      "productA": "EZ INkin REVO Round Liner",
      "productB": "EZ INkin REVO Round Liner",
      "count": 174,
      "pct": 1.6330361332707648
    },
    {
      "productA": "Cheyenne Safety Liner - Liner Cartride",
      "productB": "Cheyenne Safety Magnum - płaska prosta",
      "count": 172,
      "pct": 1.614265603003285
    },
    {
      "productA": "Elite III Round Liner",
      "productB": "Elite III Round Liner",
      "count": 169,
      "pct": 1.5861098076020648
    },
    {
      "productA": "AVA Arrow Cartridge Round Liner",
      "productB": "AVA Arrow Cartridge Round Liner",
      "count": 167,
      "pct": 1.5673392773345847
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Round Shader Long Taper",
      "count": 148,
      "pct": 1.3890192397935242
    },
    {
      "productA": "Cheyenne Safety Soft Edge zaokrąglona końcówka płaska",
      "productB": "Cheyenne Safety Soft Edge zaokrąglona końcówka płaska",
      "count": 145,
      "pct": 1.360863444392304
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Bishop DaVinci V2 Magnum",
      "count": 145,
      "pct": 1.360863444392304
    },
    {
      "productA": "ELITE Infini Round Liner",
      "productB": "ELITE Infini Round Liner",
      "count": 142,
      "pct": 1.3327076489910838
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Cheyenne Safety Liner",
      "count": 124,
      "pct": 1.1637728765837634
    },
    {
      "productA": "Cartridge CRAFT Liner",
      "productB": "Cartridge CRAFT Liner",
      "count": 121,
      "pct": 1.1356170811825435
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Curved Magnum",
      "productB": "Emalla Eliot Pro Cartridge Round Shader",
      "count": 120,
      "pct": 1.1262318160488034
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 111,
      "pct": 1.041764429845143
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Curved Magnum",
      "productB": "Emalla Eliot Pro Cartridge Curved Magnum",
      "count": 111,
      "pct": 1.041764429845143
    },
    {
      "productA": "Marker do ciała SQUIDSTER",
      "productB": "Marker do ciała SQUIDSTER",
      "count": 109,
      "pct": 1.022993899577663
    },
    {
      "productA": "Okrągłe igły Piranha Liner - 5 sztuk",
      "productB": "Okrągłe igły Piranha Liner - 5 sztuk",
      "count": 109,
      "pct": 1.022993899577663
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 107,
      "pct": 1.004223369310183
    },
    {
      "productA": "Cheyenne Safety Liner - Liner Cartridge",
      "productB": "Cheyenne Safety Liner - Liner Cartridge",
      "count": 106,
      "pct": 0.9948381041764429
    },
    {
      "productA": "Cartridge Kwadron PMU Optima Liner",
      "productB": "Cartridge Kwadron PMU Optima Liner",
      "count": 104,
      "pct": 0.9760675739089629
    },
    {
      "productA": "Bishop DaVinci V2 Round Shader",
      "productB": "Bishop DaVinci V2 Round Shader",
      "count": 96,
      "pct": 0.9009854528390426
    },
    {
      "productA": "ELITE Infini Round Liner",
      "productB": "ELITE Infini Round Shader",
      "count": 89,
      "pct": 0.8352885969028625
    },
    {
      "productA": "Cartridge Kwadron Round Liner Long Taper",
      "productB": "Cartridge Kwadron Round Liner Long Taper",
      "count": 88,
      "pct": 0.8259033317691225
    },
    {
      "productA": "Kwadron Round Shader Long Taper",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 88,
      "pct": 0.8259033317691225
    },
    {
      "productA": "AVA Arrow Cartridge Curved Magnum",
      "productB": "AVA Arrow Cartridge Round Liner",
      "count": 88,
      "pct": 0.8259033317691225
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Round Shader",
      "productB": "Emalla Eliot Pro Cartridge Round Shader",
      "count": 87,
      "pct": 0.8165180666353824
    },
    {
      "productA": "Dragonhawk YUE Round Liner",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 87,
      "pct": 0.8165180666353824
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 87,
      "pct": 0.8165180666353824
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Cheyenne Safety Shader",
      "count": 82,
      "pct": 0.7695917409666823
    },
    {
      "productA": "Kwadron Soft Edge Long Taper",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 82,
      "pct": 0.7695917409666823
    },
    {
      "productA": "Taśma ochronna - owijka",
      "productB": "Taśma ochronna - owijka",
      "count": 81,
      "pct": 0.7602064758329423
    },
    {
      "productA": "Elite III Round Liner Bugpin",
      "productB": "Elite III Round Shader",
      "count": 81,
      "pct": 0.7602064758329423
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Curved Magnum",
      "productB": "PEPAX LANCE Round Liner",
      "count": 80,
      "pct": 0.7508212106992023
    },
    {
      "productA": "Cheyenne Safety Liner - Liner Cartride",
      "productB": "Cheyenne Safety Soft Edge zaokrąglona końcówka płaska",
      "count": 77,
      "pct": 0.7226654152979821
    },
    {
      "productA": "EZ REVOLUTION Round Liner Long Taper 0,35 mm",
      "productB": "EZ REVOLUTION Round Liner Long Taper 0,35 mm",
      "count": 76,
      "pct": 0.7132801501642422
    },
    {
      "productA": "Elite III Round Liner Bugpin",
      "productB": "Elite III Round Liner Bugpin",
      "count": 75,
      "pct": 0.7038948850305021
    },
    {
      "productA": "Elite III Round Liner",
      "productB": "Elite III Round Shader",
      "count": 75,
      "pct": 0.7038948850305021
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Taśma ochronna - owijka",
      "count": 75,
      "pct": 0.7038948850305021
    },
    {
      "productA": "Cartridge CRAFT Liner",
      "productB": "Cartridge CRAFT Magnum dwurzędowe",
      "count": 73,
      "pct": 0.685124354763022
    },
    {
      "productA": "EZ REVOLUTION Round Liner Long Taper 0,35 mm",
      "productB": "EZ REVOLUTION Round Shader Long Taper 0,35 mm",
      "count": 73,
      "pct": 0.685124354763022
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Cartridge Cheyenne Safety Liner BugPin fine liner",
      "count": 73,
      "pct": 0.685124354763022
    },
    {
      "productA": "Bishop DaVinci V2 Magnum",
      "productB": "Bishop DaVinci V2 Round Shader",
      "count": 72,
      "pct": 0.6757390896292821
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 72,
      "pct": 0.6757390896292821
    },
    {
      "productA": "Cartridge Mast Ocean Heart",
      "productB": "Cartridge Mast Ocean Heart",
      "count": 68,
      "pct": 0.6381980290943219
    },
    {
      "productA": "PEPAX LANCE Curved Magnum",
      "productB": "PEPAX LANCE Round Shader",
      "count": 68,
      "pct": 0.6381980290943219
    },
    {
      "productA": "Cartridge CRAFT Liner",
      "productB": "Cartridge CRAFT Shader",
      "count": 67,
      "pct": 0.6288127639605819
    },
    {
      "productA": "Cartridge CRAFT Liner",
      "productB": "Cheyenne Safety Liner",
      "count": 67,
      "pct": 0.6288127639605819
    },
    {
      "productA": "EZ INkin REVO Round Liner",
      "productB": "EZ INkin REVO Round Shader",
      "count": 67,
      "pct": 0.6288127639605819
    },
    {
      "productA": "Elite III Curved Magnum Medium Taper (soft edge)",
      "productB": "Elite III Round Liner",
      "count": 67,
      "pct": 0.6288127639605819
    },
    {
      "productA": "Kwadron Round Shader Long Taper",
      "productB": "Kwadron Round Shader Long Taper",
      "count": 66,
      "pct": 0.6194274988268419
    },
    {
      "productA": "EZ REVOLUTION Round Shader Long Taper 0,35 mm",
      "productB": "EZ REVOLUTION Round Shader Long Taper 0,35 mm",
      "count": 63,
      "pct": 0.5912717034256219
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "FineLine Round Liner - 3RL",
      "count": 63,
      "pct": 0.5912717034256219
    },
    {
      "productA": "Elite III Magnum",
      "productB": "Elite III Round Shader",
      "count": 62,
      "pct": 0.5818864382918817
    },
    {
      "productA": "AVA Arrow Cartridge Round Liner",
      "productB": "AVA Arrow Cartridge Round Shader",
      "count": 62,
      "pct": 0.5818864382918817
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Dragonhawk YUE Round Liner",
      "count": 61,
      "pct": 0.5725011731581418
    },
    {
      "productA": "FineLine Round Liner - 3RL",
      "productB": "FineLine Round Liner - 3RL",
      "count": 59,
      "pct": 0.5537306428906617
    },
    {
      "productA": "Elite III Magnum",
      "productB": "Elite III Round Liner Bugpin",
      "count": 58,
      "pct": 0.5443453777569216
    },
    {
      "productA": "PEPAX LANCE Curved Magnum",
      "productB": "PEPAX LANCE Curved Magnum",
      "count": 58,
      "pct": 0.5443453777569216
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 57,
      "pct": 0.5349601126231815
    },
    {
      "productA": "CRAFT Soft Edge",
      "productB": "Cartridge CRAFT Liner",
      "count": 56,
      "pct": 0.5255748474894416
    },
    {
      "productA": "ELITE Infini Closed Curved Magnum Bugpin (SoftEdge)",
      "productB": "ELITE Infini Round Liner",
      "count": 56,
      "pct": 0.5255748474894416
    },
    {
      "productA": "Bishop DaVinci V2 Round Shader",
      "productB": "Cartridge CRAFT Liner",
      "count": 55,
      "pct": 0.5161895823557016
    },
    {
      "productA": "Cartridge CRAFT Magnum dwurzędowe",
      "productB": "Cartridge CRAFT Shader",
      "count": 55,
      "pct": 0.5161895823557016
    },
    {
      "productA": "Cheyenne Safety Shader",
      "productB": "Cheyenne Safety Shader",
      "count": 55,
      "pct": 0.5161895823557016
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "PEPAX LANCE Round Liner",
      "count": 55,
      "pct": 0.5161895823557016
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Cheyenne Safety Open Liner - mocna podszewka cartridge",
      "count": 55,
      "pct": 0.5161895823557016
    },
    {
      "productA": "Elite III Magnum",
      "productB": "Elite III Round Liner",
      "count": 54,
      "pct": 0.5068043172219615
    },
    {
      "productA": "Elite III Curved Magnum Medium Taper (soft edge)",
      "productB": "Elite III Curved Magnum Medium Taper (soft edge)",
      "count": 54,
      "pct": 0.5068043172219615
    },
    {
      "productA": "ELITE Infini Round Shader",
      "productB": "ELITE Infini Round Shader",
      "count": 54,
      "pct": 0.5068043172219615
    },
    {
      "productA": "Cheyenne BIG Magnum Soft Edge Safety cartridge, okrągły",
      "productB": "Cheyenne BIG Magnum Soft Edge Safety cartridge, okrągły",
      "count": 54,
      "pct": 0.5068043172219615
    },
    {
      "productA": "Elite III Round Liner",
      "productB": "Kwadron Flat, jednorzędowy",
      "count": 54,
      "pct": 0.5068043172219615
    },
    {
      "productA": "Bishop DaVinci V2 Round Shader",
      "productB": "Liner Bishop DaVinci V2",
      "count": 52,
      "pct": 0.48803378695448146
    },
    {
      "productA": "Revolution Round Shader Long Taper",
      "productB": "Revolution Soft Edge Long Taper",
      "count": 52,
      "pct": 0.48803378695448146
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Elite III Curved Magnum Medium Taper (soft edge)",
      "count": 52,
      "pct": 0.48803378695448146
    },
    {
      "productA": "Elite III Flat jednorzędowa",
      "productB": "Elite III Round Liner",
      "count": 51,
      "pct": 0.4786485218207414
    },
    {
      "productA": "PEPAX LANCE Round Shader",
      "productB": "PEPAX LANCE Round Shader",
      "count": 51,
      "pct": 0.4786485218207414
    },
    {
      "productA": "PEPAX LANCE Magnum",
      "productB": "PEPAX LANCE Round Liner",
      "count": 51,
      "pct": 0.4786485218207414
    },
    {
      "productA": "Cheyenne Capillary Liner",
      "productB": "Cheyenne Capillary Liner",
      "count": 50,
      "pct": 0.4692632566870014
    },
    {
      "productA": "Cheyenne Safety Magnum - płaska prosta",
      "productB": "Cheyenne Safety Magnum - płaska prosta",
      "count": 50,
      "pct": 0.4692632566870014
    },
    {
      "productA": "Cartridge Kwadron Round Liner Long Taper",
      "productB": "Cartridge Kwadron Soft Edge Long Taper Sublime",
      "count": 50,
      "pct": 0.4692632566870014
    },
    {
      "productA": "Cartridge Cheyenne Safety Liner BugPin fine liner",
      "productB": "Cheyenne Safety Shader",
      "count": 49,
      "pct": 0.4598779915532614
    },
    {
      "productA": "Cartridge Cheyenne Safety Liner BugPin fine liner",
      "productB": "Cartridge Cheyenne Safety Liner BugPin fine liner",
      "count": 49,
      "pct": 0.4598779915532614
    },
    {
      "productA": "EZ V-SELECT Liner Cartridge",
      "productB": "EZ V-SELECT Liner Cartridge",
      "count": 49,
      "pct": 0.4598779915532614
    },
    {
      "productA": "EZ INkin REVO Curved Magnum",
      "productB": "EZ INkin REVO Round Liner",
      "count": 48,
      "pct": 0.4504927264195213
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Cartridge CRAFT Liner",
      "count": 46,
      "pct": 0.4317221961520413
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "EZ INkin REVO Round Liner",
      "count": 46,
      "pct": 0.4317221961520413
    }
  ]
};
