// Auto-generated by scripts/fetchShoptetDataDE.js — last update: 2026-04-18
// DE: product pair co-occurrence from orders

export interface CrossSellPair {
  productA: string;
  productB: string;
  count: number;
  pct: number;
}

export interface CrossSellData {
  totalOrders: number;
  multiItemOrders: number;
  pairs: CrossSellPair[];
}

export const crossSellDataDE: CrossSellData = {
  "totalOrders": 18486,
  "multiItemOrders": 11465,
  "pairs": [
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Bishop DaVinci V2 Liner",
      "count": 2228,
      "pct": 12.052363951098128
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 2217,
      "pct": 11.992859461213893
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 1686,
      "pct": 9.120415449529373
    },
    {
      "productA": "Kwadron Soft Edge Long Taper",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 1217,
      "pct": 6.5833603808287355
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Round Shader Long Taper",
      "count": 948,
      "pct": 5.128205128205128
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Bishop DaVinci V2 Liner",
      "count": 928,
      "pct": 5.020015146597425
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Cheyenne Safety Liner",
      "count": 866,
      "pct": 4.684626203613545
    },
    {
      "productA": "Dragonhawk YUE Round Liner",
      "productB": "Dragonhawk YUE Round Liner",
      "count": 801,
      "pct": 4.33300876338851
    },
    {
      "productA": "Kwadron Round Shader Long Taper",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 736,
      "pct": 3.9813913231634754
    },
    {
      "productA": "Kwadron Cartridges Round Liner Long Taper",
      "productB": "Kwadron Cartridges Round Liner Long Taper",
      "count": 724,
      "pct": 3.9164773341988535
    },
    {
      "productA": "Kwadron Cartridges PMU Optima Liner",
      "productB": "Kwadron Cartridges PMU Optima Liner",
      "count": 628,
      "pct": 3.3971654224818777
    },
    {
      "productA": "EZ INkin REVO Round Liner",
      "productB": "EZ INkin REVO Round Liner",
      "count": 617,
      "pct": 3.3376609325976414
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Bishop DaVinci V2 Round Shader",
      "count": 602,
      "pct": 3.256518446391864
    },
    {
      "productA": "Kwadron Round Shader Long Taper",
      "productB": "Kwadron Round Shader Long Taper",
      "count": 557,
      "pct": 3.013090987774532
    },
    {
      "productA": "Piranha Liner Nadeln Round Liner - 5 Stück",
      "productB": "Piranha Liner Nadeln Round Liner - 5 Stück",
      "count": 482,
      "pct": 2.6073785567456453
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Round Liner",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 460,
      "pct": 2.488369576977172
    },
    {
      "productA": "Kwadron Round Liner Medium Taper",
      "productB": "Kwadron Round Liner Medium Taper",
      "count": 458,
      "pct": 2.477550578816402
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Bishop DaVinci V2 Curved Magnum",
      "count": 422,
      "pct": 2.282808611922536
    },
    {
      "productA": "Kwadron Cartridges Round Liner Long Taper",
      "productB": "Kwadron Cartridges Round Shader Long Taper",
      "count": 414,
      "pct": 2.239532619279455
    },
    {
      "productA": "ELITE Infini Round Liner",
      "productB": "ELITE Infini Round Liner",
      "count": 411,
      "pct": 2.223304122038299
    },
    {
      "productA": "CRAFT Liner Cartridges",
      "productB": "CRAFT Liner Cartridges",
      "count": 372,
      "pct": 2.012333657903278
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Cheyenne Safety Soft Edge abgerundete Spitze flach",
      "count": 348,
      "pct": 1.8825056799740343
    },
    {
      "productA": "Farbkappen - Ink Cups",
      "productB": "Farbkappen - Ink Cups",
      "count": 325,
      "pct": 1.7580872011251758
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Bishop DaVinci V2 Magnum",
      "count": 315,
      "pct": 1.7039922103213243
    },
    {
      "productA": "Kwadron Magnum Long Taper",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 312,
      "pct": 1.6877637130801686
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Dragonhawk YUE Round Liner",
      "count": 306,
      "pct": 1.6553067185978578
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 305,
      "pct": 1.6498972195174728
    },
    {
      "productA": "EZ INkin REVO Round Liner",
      "productB": "EZ INkin REVO Round Shader",
      "count": 301,
      "pct": 1.628259223195932
    },
    {
      "productA": "Elite III Curved Magnum Medium Taper (Soft Edge)",
      "productB": "Elite III Curved Magnum Medium Taper (Soft Edge)",
      "count": 295,
      "pct": 1.5958022287136213
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Soft Edge Medium taper",
      "count": 285,
      "pct": 1.5417072379097696
    },
    {
      "productA": "Cartridge Mast Ocean Heart",
      "productB": "Cartridge Mast Ocean Heart",
      "count": 276,
      "pct": 1.4930217461863031
    },
    {
      "productA": "PEPAX LANCE Round Liner",
      "productB": "PEPAX LANCE Round Liner",
      "count": 272,
      "pct": 1.4713837498647626
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 266,
      "pct": 1.4389267553824516
    },
    {
      "productA": "Kwadron Cartridges Round Shader Long Taper",
      "productB": "Kwadron Cartridges Round Shader Long Taper",
      "count": 265,
      "pct": 1.4335172563020664
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Curved Magnum",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 264,
      "pct": 1.4281077572216814
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Round Liner Medium Taper",
      "count": 255,
      "pct": 1.379422265498215
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Bishop DaVinci V2 Round Shader",
      "count": 238,
      "pct": 1.2874607811316672
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 236,
      "pct": 1.276641782970897
    },
    {
      "productA": "Mosquito-Kanüle - selbstlösend 1Stk",
      "productB": "Mosquito-Kanüle - selbstlösend 1Stk",
      "count": 226,
      "pct": 1.2225467921670454
    },
    {
      "productA": "Kwadron cartridge Round Liner Long Taper",
      "productB": "Kwadron cartridge Round Shader Long Taper",
      "count": 224,
      "pct": 1.2117277940062752
    },
    {
      "productA": "Cartridge Stellar - Ballpoint Cartridge",
      "productB": "Cartridge Stellar - Ballpoint Cartridge",
      "count": 224,
      "pct": 1.2117277940062752
    },
    {
      "productA": "CRAFT Liner Cartridges",
      "productB": "CRAFT Shader Cartridge",
      "count": 223,
      "pct": 1.20631829492589
    },
    {
      "productA": "Kwadron Cartridges Magnum Long Taper",
      "productB": "Kwadron Cartridges Round Liner Long Taper",
      "count": 219,
      "pct": 1.1846802986043492
    },
    {
      "productA": "Cheyenne Safety Soft Edge abgerundete Spitze flach",
      "productB": "Cheyenne Safety Soft Edge abgerundete Spitze flach",
      "count": 219,
      "pct": 1.1846802986043492
    },
    {
      "productA": "Elite III Curved Magnum Medium Taper (Soft Edge)",
      "productB": "Elite III Round Liner",
      "count": 212,
      "pct": 1.1468138050416532
    },
    {
      "productA": "EZ INkin REVO Curved Magnum",
      "productB": "EZ INkin REVO Round Liner",
      "count": 210,
      "pct": 1.1359948068808827
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Cheyenne Safety Shader",
      "count": 210,
      "pct": 1.1359948068808827
    },
    {
      "productA": "Kwadron Round Liner Medium Taper",
      "productB": "Kwadron Soft Edge Medium taper",
      "count": 208,
      "pct": 1.1251758087201125
    },
    {
      "productA": "Bishop DaVinci V2 Round Shader",
      "productB": "Bishop DaVinci V2 Round Shader",
      "count": 207,
      "pct": 1.1197663096397275
    },
    {
      "productA": "Kwadron Cartridges Round Liner Long Taper",
      "productB": "Kwadron Cartridges Soft Edge Long Taper Sublime",
      "count": 206,
      "pct": 1.1143568105593422
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Cheyenne Safety Liner",
      "count": 203,
      "pct": 1.0981283133181867
    },
    {
      "productA": "Elite III Round Liner",
      "productB": "Elite III Round Liner",
      "count": 199,
      "pct": 1.076490316996646
    },
    {
      "productA": "Kwadron cartridge Round Liner Long Taper",
      "productB": "Kwadron cartridge Round Liner Long Taper",
      "count": 189,
      "pct": 1.0223953261927945
    },
    {
      "productA": "CRAFT Liner Cartridges",
      "productB": "CRAFT Magnum Soft Edge",
      "count": 187,
      "pct": 1.0115763280320242
    },
    {
      "productA": "Cheyenne Capillary Liner - Liner Cartridges",
      "productB": "Cheyenne Capillary Liner - Liner Cartridges",
      "count": 181,
      "pct": 0.9791193335497134
    },
    {
      "productA": "Kwadron Flat Cartridges - Einreihig",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 181,
      "pct": 0.9791193335497134
    },
    {
      "productA": "FineLine Round Liner - 3RL",
      "productB": "FineLine Round Liner - 3RL",
      "count": 179,
      "pct": 0.9683003353889431
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Round Liner",
      "productB": "Emalla Eliot Pro Cartridge Round Shader",
      "count": 172,
      "pct": 0.9304338418262469
    },
    {
      "productA": "CRAFT Liner Cartridges",
      "productB": "Cheyenne Safety Liner",
      "count": 170,
      "pct": 0.9196148436654765
    },
    {
      "productA": "CRAFT Liner Cartridges",
      "productB": "CRAFT Magnum flache zweireihige Cartridges",
      "count": 168,
      "pct": 0.9087958455047063
    },
    {
      "productA": "Kwadron Round Liner Medium Taper",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 166,
      "pct": 0.897976847343936
    },
    {
      "productA": "Kwadron Magnum Long Taper Sublime",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 163,
      "pct": 0.8817483501027805
    },
    {
      "productA": "Griff Bandage - Grip Wrap",
      "productB": "Griff Bandage - Grip Wrap",
      "count": 162,
      "pct": 0.8763388510223954
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Griff Bandage - Grip Wrap",
      "count": 159,
      "pct": 0.8601103537812399
    },
    {
      "productA": "Kwadron Magnum Long Taper",
      "productB": "Kwadron Magnum Long Taper",
      "count": 156,
      "pct": 0.8438818565400843
    },
    {
      "productA": "EZ INkin REVO Round Liner",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 156,
      "pct": 0.8438818565400843
    },
    {
      "productA": "AVA Arrow Cartridge Round Liner",
      "productB": "AVA Arrow Cartridge Round Liner",
      "count": 155,
      "pct": 0.8384723574596992
    },
    {
      "productA": "Dragonhawk YUE Round Liner",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 152,
      "pct": 0.8222438602185437
    },
    {
      "productA": "Kwadron Cartridges Soft Edge runde Schattierung Long taper",
      "productB": "Kwadron Cartridges Soft Edge runde Schattierung Long taper",
      "count": 146,
      "pct": 0.7897868657362328
    },
    {
      "productA": "Kwadron Cartridges Round Liner Long Taper",
      "productB": "Kwadron Cartridges Soft Edge runde Schattierung Long taper",
      "count": 144,
      "pct": 0.7789678675754625
    },
    {
      "productA": "TOMBOW Körper Marker",
      "productB": "TOMBOW Körper Marker",
      "count": 144,
      "pct": 0.7789678675754625
    },
    {
      "productA": "Kwadron Soft Edge Long Taper",
      "productB": "Kwadron Soft Edge Medium taper",
      "count": 144,
      "pct": 0.7789678675754625
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Kwadron Cartridges Round Liner Long Taper",
      "count": 143,
      "pct": 0.7735583684950774
    },
    {
      "productA": "CRAFT Magnum Soft Edge",
      "productB": "CRAFT Magnum Soft Edge",
      "count": 143,
      "pct": 0.7735583684950774
    },
    {
      "productA": "Piranha Stahlpiercing Mini-Banane - 10Stk",
      "productB": "Stahlpiercing Barbell - 10Stück",
      "count": 140,
      "pct": 0.7573298712539218
    },
    {
      "productA": "Kwadron Soft Edge Medium taper",
      "productB": "Kwadron Soft Edge Medium taper",
      "count": 139,
      "pct": 0.7519203721735367
    },
    {
      "productA": "Bishop DaVinci V2 Magnum",
      "productB": "Bishop DaVinci V2 Magnum",
      "count": 138,
      "pct": 0.7465108730931516
    },
    {
      "productA": "Cheyenne Safety Liner - Liner Cartridge",
      "productB": "Cheyenne Safety Liner - Liner Cartridge",
      "count": 138,
      "pct": 0.7465108730931516
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "ECLIPSE TATTOO INK Total Black 150ml",
      "count": 138,
      "pct": 0.7465108730931516
    },
    {
      "productA": "EZ REVOLUTION Round Liner Long Taper 0,35mm",
      "productB": "EZ REVOLUTION Round Liner Long Taper 0,35mm",
      "count": 136,
      "pct": 0.7356918749323813
    },
    {
      "productA": "Cheyenne Safety Shader",
      "productB": "Cheyenne Safety Shader",
      "count": 136,
      "pct": 0.7356918749323813
    },
    {
      "productA": "Bishop DaVinci V2 Magnum",
      "productB": "Bishop DaVinci V2 Round Shader",
      "count": 136,
      "pct": 0.7356918749323813
    },
    {
      "productA": "Piranha Liner Nadeln Round Liner - 5 Stück",
      "productB": "Piranha Schattierungsnadeln Round Shader - 5Stück",
      "count": 133,
      "pct": 0.7194633776912258
    },
    {
      "productA": "Kwadron Cartridges Round Liner Medium Taper",
      "productB": "Kwadron Cartridges Round Liner Medium Taper",
      "count": 133,
      "pct": 0.7194633776912258
    },
    {
      "productA": "Dragonhawk YUE Round Liner",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 133,
      "pct": 0.7194633776912258
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Farbkappen - Ink Cups",
      "count": 131,
      "pct": 0.7086443795304554
    },
    {
      "productA": "EZ INkin REVO Magnum",
      "productB": "EZ INkin REVO Round Liner",
      "count": 129,
      "pct": 0.6978253813696852
    },
    {
      "productA": "Farbkappen - Ink Cups",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 129,
      "pct": 0.6978253813696852
    },
    {
      "productA": "Dragonhawk YUE Round Liner",
      "productB": "EZ INkin REVO Round Liner",
      "count": 129,
      "pct": 0.6978253813696852
    },
    {
      "productA": "ELITE Infini Round Liner",
      "productB": "ELITE Infini Round Shader",
      "count": 128,
      "pct": 0.6924158822893
    },
    {
      "productA": "Dragonhawk YUE Round Liner",
      "productB": "FineLine Round Liner - 3RL",
      "count": 128,
      "pct": 0.6924158822893
    },
    {
      "productA": "Stahlpiercing Barbell - 10Stück",
      "productB": "Stahlpiercing Barbell - 10Stück",
      "count": 127,
      "pct": 0.6870063832089148
    },
    {
      "productA": "Cheyenne Safety Shader",
      "productB": "Cheyenne Safety Soft Edge abgerundete Spitze flach",
      "count": 127,
      "pct": 0.6870063832089148
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Round Liner",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 127,
      "pct": 0.6870063832089148
    },
    {
      "productA": "Kwadron Soft Edge Long Taper",
      "productB": "PEPAX LANCE Round Liner",
      "count": 127,
      "pct": 0.6870063832089148
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Elite III Curved Magnum Medium Taper (Soft Edge)",
      "count": 123,
      "pct": 0.6653683868873742
    },
    {
      "productA": "Cheyenne Safety Soft Edge BugPin, feine runde Schattierung",
      "productB": "Cheyenne Safety Soft Edge BugPin, feine runde Schattierung",
      "count": 122,
      "pct": 0.6599588878069891
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 122,
      "pct": 0.6599588878069891
    },
    {
      "productA": "Kwadron Magnum Long Taper",
      "productB": "Kwadron Round Shader Long Taper",
      "count": 122,
      "pct": 0.6599588878069891
    },
    {
      "productA": "Kwadron Round Liner Medium Taper",
      "productB": "Kwadron Round Shader Long Taper",
      "count": 122,
      "pct": 0.6599588878069891
    }
  ]
};
