// Auto-generated by scripts/fetchShoptetData.js — last update: 2026-04-18
// PL: product pair co-occurrence from orders

export interface CrossSellPair {
  productA: string;
  productB: string;
  count: number;
  pct: number;
}

export interface CrossSellData {
  totalOrders: number;
  multiItemOrders: number;
  pairs: CrossSellPair[];
}

export const crossSellDataPL: CrossSellData = {
  "totalOrders": 10676,
  "multiItemOrders": 5834,
  "pairs": [
    {
      "productA": "PEPAX LANCE Round Liner",
      "productB": "PEPAX LANCE Round Liner",
      "count": 888,
      "pct": 8.317721993255901
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Bishop DaVinci V2 Liner",
      "count": 652,
      "pct": 6.107156238291496
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Round Liner",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 508,
      "pct": 4.7583364556013485
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Cheyenne Safety Liner",
      "count": 471,
      "pct": 4.411764705882353
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Bishop DaVinci V2 Curved Magnum",
      "count": 358,
      "pct": 3.353315848632447
    },
    {
      "productA": "PEPAX LANCE Round Liner",
      "productB": "PEPAX LANCE Round Shader",
      "count": 316,
      "pct": 2.959910078681154
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 284,
      "pct": 2.660172349194455
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Bishop DaVinci V2 Round Shader",
      "count": 283,
      "pct": 2.6508055451479957
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Round Liner",
      "productB": "Emalla Eliot Pro Cartridge Round Shader",
      "count": 263,
      "pct": 2.4634694642188086
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Bishop DaVinci V2 Liner",
      "count": 244,
      "pct": 2.285500187336081
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Curved Magnum",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 243,
      "pct": 2.2761333832896216
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Cheyenne Safety Soft Edge zaokrąglona końcówka płaska",
      "count": 242,
      "pct": 2.2667665792431624
    },
    {
      "productA": "Cheyenne Safety Liner - Liner Cartride",
      "productB": "Cheyenne Safety Liner - Liner Cartride",
      "count": 214,
      "pct": 2.0044960659423006
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Bishop DaVinci V2 Round Shader",
      "count": 206,
      "pct": 1.9295616335706256
    },
    {
      "productA": "Dragonhawk YUE Round Liner",
      "productB": "Dragonhawk YUE Round Liner",
      "count": 201,
      "pct": 1.882727613338329
    },
    {
      "productA": "PEPAX LANCE Curved Magnum",
      "productB": "PEPAX LANCE Round Liner",
      "count": 193,
      "pct": 1.807793180966654
    },
    {
      "productA": "EZ INkin REVO Round Liner",
      "productB": "EZ INkin REVO Round Liner",
      "count": 174,
      "pct": 1.6298239040839264
    },
    {
      "productA": "Cheyenne Safety Liner - Liner Cartride",
      "productB": "Cheyenne Safety Magnum - płaska prosta",
      "count": 172,
      "pct": 1.6110902959910078
    },
    {
      "productA": "Elite III Round Liner",
      "productB": "Elite III Round Liner",
      "count": 169,
      "pct": 1.5829898838516296
    },
    {
      "productA": "AVA Arrow Cartridge Round Liner",
      "productB": "AVA Arrow Cartridge Round Liner",
      "count": 167,
      "pct": 1.564256275758711
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Round Shader Long Taper",
      "count": 148,
      "pct": 1.3862869988759834
    },
    {
      "productA": "Cheyenne Safety Soft Edge zaokrąglona końcówka płaska",
      "productB": "Cheyenne Safety Soft Edge zaokrąglona końcówka płaska",
      "count": 145,
      "pct": 1.3581865867366054
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Bishop DaVinci V2 Magnum",
      "count": 145,
      "pct": 1.3581865867366054
    },
    {
      "productA": "ELITE Infini Round Liner",
      "productB": "ELITE Infini Round Liner",
      "count": 142,
      "pct": 1.3300861745972274
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Cheyenne Safety Liner",
      "count": 124,
      "pct": 1.1614837017609592
    },
    {
      "productA": "Cartridge CRAFT Liner",
      "productB": "Cartridge CRAFT Liner",
      "count": 121,
      "pct": 1.1333832896215812
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Curved Magnum",
      "productB": "Emalla Eliot Pro Cartridge Round Shader",
      "count": 120,
      "pct": 1.1240164855751216
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 111,
      "pct": 1.0397152491569877
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Curved Magnum",
      "productB": "Emalla Eliot Pro Cartridge Curved Magnum",
      "count": 111,
      "pct": 1.0397152491569877
    },
    {
      "productA": "Marker do ciała SQUIDSTER",
      "productB": "Marker do ciała SQUIDSTER",
      "count": 110,
      "pct": 1.0303484451105283
    },
    {
      "productA": "Okrągłe igły Piranha Liner - 5 sztuk",
      "productB": "Okrągłe igły Piranha Liner - 5 sztuk",
      "count": 109,
      "pct": 1.020981641064069
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 107,
      "pct": 1.0022480329711503
    },
    {
      "productA": "Cheyenne Safety Liner - Liner Cartridge",
      "productB": "Cheyenne Safety Liner - Liner Cartridge",
      "count": 106,
      "pct": 0.992881228924691
    },
    {
      "productA": "Cartridge Kwadron PMU Optima Liner",
      "productB": "Cartridge Kwadron PMU Optima Liner",
      "count": 104,
      "pct": 0.9741476208317721
    },
    {
      "productA": "Bishop DaVinci V2 Round Shader",
      "productB": "Bishop DaVinci V2 Round Shader",
      "count": 96,
      "pct": 0.8992131884600975
    },
    {
      "productA": "ELITE Infini Round Liner",
      "productB": "ELITE Infini Round Shader",
      "count": 89,
      "pct": 0.8336455601348819
    },
    {
      "productA": "Cartridge Kwadron Round Liner Long Taper",
      "productB": "Cartridge Kwadron Round Liner Long Taper",
      "count": 88,
      "pct": 0.8242787560884226
    },
    {
      "productA": "Kwadron Round Shader Long Taper",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 88,
      "pct": 0.8242787560884226
    },
    {
      "productA": "AVA Arrow Cartridge Curved Magnum",
      "productB": "AVA Arrow Cartridge Round Liner",
      "count": 88,
      "pct": 0.8242787560884226
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Round Shader",
      "productB": "Emalla Eliot Pro Cartridge Round Shader",
      "count": 87,
      "pct": 0.8149119520419632
    },
    {
      "productA": "Dragonhawk YUE Round Liner",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 87,
      "pct": 0.8149119520419632
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 87,
      "pct": 0.8149119520419632
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Cheyenne Safety Shader",
      "count": 82,
      "pct": 0.7680779318096665
    },
    {
      "productA": "Kwadron Soft Edge Long Taper",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 82,
      "pct": 0.7680779318096665
    },
    {
      "productA": "Taśma ochronna - owijka",
      "productB": "Taśma ochronna - owijka",
      "count": 81,
      "pct": 0.7587111277632071
    },
    {
      "productA": "Elite III Round Liner Bugpin",
      "productB": "Elite III Round Shader",
      "count": 81,
      "pct": 0.7587111277632071
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Curved Magnum",
      "productB": "PEPAX LANCE Round Liner",
      "count": 80,
      "pct": 0.7493443237167479
    },
    {
      "productA": "Cheyenne Safety Liner - Liner Cartride",
      "productB": "Cheyenne Safety Soft Edge zaokrąglona końcówka płaska",
      "count": 77,
      "pct": 0.7212439115773698
    },
    {
      "productA": "EZ REVOLUTION Round Liner Long Taper 0,35 mm",
      "productB": "EZ REVOLUTION Round Liner Long Taper 0,35 mm",
      "count": 76,
      "pct": 0.7118771075309105
    },
    {
      "productA": "Elite III Round Liner Bugpin",
      "productB": "Elite III Round Liner Bugpin",
      "count": 75,
      "pct": 0.7025103034844511
    },
    {
      "productA": "Elite III Round Liner",
      "productB": "Elite III Round Shader",
      "count": 75,
      "pct": 0.7025103034844511
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Taśma ochronna - owijka",
      "count": 75,
      "pct": 0.7025103034844511
    },
    {
      "productA": "Cartridge CRAFT Liner",
      "productB": "Cartridge CRAFT Magnum dwurzędowe",
      "count": 73,
      "pct": 0.6837766953915324
    },
    {
      "productA": "EZ REVOLUTION Round Liner Long Taper 0,35 mm",
      "productB": "EZ REVOLUTION Round Shader Long Taper 0,35 mm",
      "count": 73,
      "pct": 0.6837766953915324
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Cartridge Cheyenne Safety Liner BugPin fine liner",
      "count": 73,
      "pct": 0.6837766953915324
    },
    {
      "productA": "Bishop DaVinci V2 Magnum",
      "productB": "Bishop DaVinci V2 Round Shader",
      "count": 72,
      "pct": 0.674409891345073
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 72,
      "pct": 0.674409891345073
    },
    {
      "productA": "Cartridge Mast Ocean Heart",
      "productB": "Cartridge Mast Ocean Heart",
      "count": 68,
      "pct": 0.6369426751592357
    },
    {
      "productA": "PEPAX LANCE Curved Magnum",
      "productB": "PEPAX LANCE Round Shader",
      "count": 68,
      "pct": 0.6369426751592357
    },
    {
      "productA": "Cartridge CRAFT Liner",
      "productB": "Cartridge CRAFT Shader",
      "count": 67,
      "pct": 0.6275758711127762
    },
    {
      "productA": "Cartridge CRAFT Liner",
      "productB": "Cheyenne Safety Liner",
      "count": 67,
      "pct": 0.6275758711127762
    },
    {
      "productA": "EZ INkin REVO Round Liner",
      "productB": "EZ INkin REVO Round Shader",
      "count": 67,
      "pct": 0.6275758711127762
    },
    {
      "productA": "Elite III Curved Magnum Medium Taper (soft edge)",
      "productB": "Elite III Round Liner",
      "count": 67,
      "pct": 0.6275758711127762
    },
    {
      "productA": "Kwadron Round Shader Long Taper",
      "productB": "Kwadron Round Shader Long Taper",
      "count": 66,
      "pct": 0.618209067066317
    },
    {
      "productA": "EZ REVOLUTION Round Shader Long Taper 0,35 mm",
      "productB": "EZ REVOLUTION Round Shader Long Taper 0,35 mm",
      "count": 63,
      "pct": 0.590108654926939
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "FineLine Round Liner - 3RL",
      "count": 63,
      "pct": 0.590108654926939
    },
    {
      "productA": "Elite III Magnum",
      "productB": "Elite III Round Shader",
      "count": 62,
      "pct": 0.5807418508804796
    },
    {
      "productA": "AVA Arrow Cartridge Round Liner",
      "productB": "AVA Arrow Cartridge Round Shader",
      "count": 62,
      "pct": 0.5807418508804796
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Dragonhawk YUE Round Liner",
      "count": 61,
      "pct": 0.5713750468340203
    },
    {
      "productA": "FineLine Round Liner - 3RL",
      "productB": "FineLine Round Liner - 3RL",
      "count": 59,
      "pct": 0.5526414387411015
    },
    {
      "productA": "Elite III Magnum",
      "productB": "Elite III Round Liner Bugpin",
      "count": 58,
      "pct": 0.5432746346946422
    },
    {
      "productA": "PEPAX LANCE Curved Magnum",
      "productB": "PEPAX LANCE Curved Magnum",
      "count": 58,
      "pct": 0.5432746346946422
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 57,
      "pct": 0.5339078306481828
    },
    {
      "productA": "CRAFT Soft Edge",
      "productB": "Cartridge CRAFT Liner",
      "count": 56,
      "pct": 0.5245410266017235
    },
    {
      "productA": "ELITE Infini Closed Curved Magnum Bugpin (SoftEdge)",
      "productB": "ELITE Infini Round Liner",
      "count": 56,
      "pct": 0.5245410266017235
    },
    {
      "productA": "Bishop DaVinci V2 Round Shader",
      "productB": "Cartridge CRAFT Liner",
      "count": 55,
      "pct": 0.5151742225552641
    },
    {
      "productA": "Cartridge CRAFT Magnum dwurzędowe",
      "productB": "Cartridge CRAFT Shader",
      "count": 55,
      "pct": 0.5151742225552641
    },
    {
      "productA": "Cheyenne Safety Shader",
      "productB": "Cheyenne Safety Shader",
      "count": 55,
      "pct": 0.5151742225552641
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "PEPAX LANCE Round Liner",
      "count": 55,
      "pct": 0.5151742225552641
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Cheyenne Safety Open Liner - mocna podszewka cartridge",
      "count": 55,
      "pct": 0.5151742225552641
    },
    {
      "productA": "Elite III Magnum",
      "productB": "Elite III Round Liner",
      "count": 54,
      "pct": 0.5058074185088048
    },
    {
      "productA": "Elite III Curved Magnum Medium Taper (soft edge)",
      "productB": "Elite III Curved Magnum Medium Taper (soft edge)",
      "count": 54,
      "pct": 0.5058074185088048
    },
    {
      "productA": "ELITE Infini Round Shader",
      "productB": "ELITE Infini Round Shader",
      "count": 54,
      "pct": 0.5058074185088048
    },
    {
      "productA": "Cheyenne BIG Magnum Soft Edge Safety cartridge, okrągły",
      "productB": "Cheyenne BIG Magnum Soft Edge Safety cartridge, okrągły",
      "count": 54,
      "pct": 0.5058074185088048
    },
    {
      "productA": "Elite III Round Liner",
      "productB": "Kwadron Flat, jednorzędowy",
      "count": 54,
      "pct": 0.5058074185088048
    },
    {
      "productA": "Bishop DaVinci V2 Round Shader",
      "productB": "Liner Bishop DaVinci V2",
      "count": 52,
      "pct": 0.48707381041588604
    },
    {
      "productA": "Revolution Round Shader Long Taper",
      "productB": "Revolution Soft Edge Long Taper",
      "count": 52,
      "pct": 0.48707381041588604
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Elite III Curved Magnum Medium Taper (soft edge)",
      "count": 52,
      "pct": 0.48707381041588604
    },
    {
      "productA": "Elite III Flat jednorzędowa",
      "productB": "Elite III Round Liner",
      "count": 51,
      "pct": 0.47770700636942676
    },
    {
      "productA": "PEPAX LANCE Round Shader",
      "productB": "PEPAX LANCE Round Shader",
      "count": 51,
      "pct": 0.47770700636942676
    },
    {
      "productA": "PEPAX LANCE Magnum",
      "productB": "PEPAX LANCE Round Liner",
      "count": 51,
      "pct": 0.47770700636942676
    },
    {
      "productA": "Cheyenne Capillary Liner",
      "productB": "Cheyenne Capillary Liner",
      "count": 50,
      "pct": 0.4683402023229674
    },
    {
      "productA": "Cheyenne Safety Magnum - płaska prosta",
      "productB": "Cheyenne Safety Magnum - płaska prosta",
      "count": 50,
      "pct": 0.4683402023229674
    },
    {
      "productA": "Cartridge Kwadron Round Liner Long Taper",
      "productB": "Cartridge Kwadron Soft Edge Long Taper Sublime",
      "count": 50,
      "pct": 0.4683402023229674
    },
    {
      "productA": "Cartridge Cheyenne Safety Liner BugPin fine liner",
      "productB": "Cheyenne Safety Shader",
      "count": 49,
      "pct": 0.45897339827650807
    },
    {
      "productA": "Cartridge Cheyenne Safety Liner BugPin fine liner",
      "productB": "Cartridge Cheyenne Safety Liner BugPin fine liner",
      "count": 49,
      "pct": 0.45897339827650807
    },
    {
      "productA": "EZ V-SELECT Liner Cartridge",
      "productB": "EZ V-SELECT Liner Cartridge",
      "count": 49,
      "pct": 0.45897339827650807
    },
    {
      "productA": "EZ INkin REVO Curved Magnum",
      "productB": "EZ INkin REVO Round Liner",
      "count": 48,
      "pct": 0.44960659423004873
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Cartridge CRAFT Liner",
      "count": 46,
      "pct": 0.43087298613713004
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "EZ INkin REVO Round Liner",
      "count": 46,
      "pct": 0.43087298613713004
    }
  ]
};
