// Auto-generated by scripts/updateData.js — last update: 2026-03-19
// CZ: product pair co-occurrence from order export

export interface CrossSellPair {
  productA: string;
  productB: string;
  count: number;   // number of orders containing both products
  pct: number;     // % of total orders
}

export interface CrossSellData {
  totalOrders: number;
  multiItemOrders: number;
  pairs: CrossSellPair[];
}

export const crossSellDataCZ: CrossSellData = {
  "totalOrders": 1102,
  "multiItemOrders": 918,
  "pairs": [
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 241,
      "pct": 21.87
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 149,
      "pct": 13.52
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 142,
      "pct": 12.89
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 111,
      "pct": 10.07
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 110,
      "pct": 9.98
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 105,
      "pct": 9.53
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 93,
      "pct": 8.44
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 90,
      "pct": 8.17
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 86,
      "pct": 7.8
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Tuňák v olivovém oleji 160 g",
      "count": 81,
      "pct": 7.35
    },
    {
      "productA": "Makrela v olivovém oleji s citronem a pepřem 5 barev 118 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 78,
      "pct": 7.08
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 78,
      "pct": 7.08
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 72,
      "pct": 6.53
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 72,
      "pct": 6.53
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 69,
      "pct": 6.26
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 66,
      "pct": 5.99
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 66,
      "pct": 5.99
    },
    {
      "productA": "Makrela v olivovém oleji s citronem a pepřem 5 barev 118 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 62,
      "pct": 5.63
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 59,
      "pct": 5.35
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 59,
      "pct": 5.35
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 55,
      "pct": 4.99
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky marinované ve víně Muscadet 115 g",
      "count": 54,
      "pct": 4.9
    },
    {
      "productA": "Pěnová pomazánka z humra a koňaku 60 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 53,
      "pct": 4.81
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 53,
      "pct": 4.81
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 53,
      "pct": 4.81
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v slunečnicovém oleji s rajčaty 115 g",
      "count": 51,
      "pct": 4.63
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 51,
      "pct": 4.63
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 50,
      "pct": 4.54
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 50,
      "pct": 4.54
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 47,
      "pct": 4.26
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 45,
      "pct": 4.08
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 45,
      "pct": 4.08
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky s citronem a chilli papričkami 115 g",
      "count": 45,
      "pct": 4.08
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 45,
      "pct": 4.08
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Tuňák v olivovém oleji 160 g",
      "count": 44,
      "pct": 3.99
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v slunečnicovém oleji s rajčaty 115 g",
      "count": 42,
      "pct": 3.81
    },
    {
      "productA": "Sardinky v olivovém oleji s rajčaty 115 g",
      "productB": "Sardinky v slunečnicovém oleji s rajčaty 115 g",
      "count": 42,
      "pct": 3.81
    },
    {
      "productA": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 42,
      "pct": 3.81
    },
    {
      "productA": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 42,
      "pct": 3.81
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 42,
      "pct": 3.81
    },
    {
      "productA": "Sardinky v olivovém oleji s rajčaty 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 41,
      "pct": 3.72
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 40,
      "pct": 3.63
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 39,
      "pct": 3.54
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 39,
      "pct": 3.54
    },
    {
      "productA": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 39,
      "pct": 3.54
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 38,
      "pct": 3.45
    },
    {
      "productA": "Makrela ve víně s aromatickým kořením 118 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 38,
      "pct": 3.45
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 38,
      "pct": 3.45
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 38,
      "pct": 3.45
    },
    {
      "productA": "Pomazánka z tuňáka s parmezánem 60 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 38,
      "pct": 3.45
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 37,
      "pct": 3.36
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v arašídovém oleji 115 g",
      "count": 37,
      "pct": 3.36
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 36,
      "pct": 3.27
    },
    {
      "productA": "Makrela s rajčaty 112,5 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 35,
      "pct": 3.18
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 35,
      "pct": 3.18
    },
    {
      "productA": "Pěnová pomazánka z humra a koňaku 60 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 34,
      "pct": 3.09
    },
    {
      "productA": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 34,
      "pct": 3.09
    },
    {
      "productA": "Pomazánka z tuňáka s parmezánem 60 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 34,
      "pct": 3.09
    },
    {
      "productA": "Pomazánka ze sardinek a whisky 60 g",
      "productB": "Pěnová pomazánka z humra a koňaku 60 g",
      "count": 34,
      "pct": 3.09
    },
    {
      "productA": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 33,
      "pct": 2.99
    },
    {
      "productA": "Pomazánka z tuňáka s parmezánem 60 g",
      "productB": "Pěnová pomazánka z humra a koňaku 60 g",
      "count": 33,
      "pct": 2.99
    },
    {
      "productA": "Sardinky s olivovou tapenádou 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 33,
      "pct": 2.99
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "count": 33,
      "pct": 2.99
    },
    {
      "productA": "Makrela v olivovém oleji s citronem a pepřem 5 barev 118 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 32,
      "pct": 2.9
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "count": 32,
      "pct": 2.9
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 32,
      "pct": 2.9
    },
    {
      "productA": "Sardinky s olivovou tapenádou 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 32,
      "pct": 2.9
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 32,
      "pct": 2.9
    },
    {
      "productA": "Makrela Diablesse 112,5 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 31,
      "pct": 2.81
    },
    {
      "productA": "Sardinky s pepřem Batak a kurkumou 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 31,
      "pct": 2.81
    },
    {
      "productA": "Makrela v olivovém oleji s citronem a pepřem 5 barev 118 g",
      "productB": "Tuňák v olivovém oleji 160 g",
      "count": 31,
      "pct": 2.81
    },
    {
      "productA": "Pomazánka z makrely s limetkou 60 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 31,
      "pct": 2.81
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 31,
      "pct": 2.81
    },
    {
      "productA": "Sardinky v olivovém oleji s rajčaty 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 31,
      "pct": 2.81
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v arašídovém oleji s citronem 115 g",
      "count": 31,
      "pct": 2.81
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Tuňák ve vlastní šťávě 207 g",
      "count": 31,
      "pct": 2.81
    },
    {
      "productA": "Pěnová pomazánka z humra a koňaku 60 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 30,
      "pct": 2.72
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 30,
      "pct": 2.72
    },
    {
      "productA": "Makrela v olivovém oleji s citronem a pepřem 5 barev 118 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 30,
      "pct": 2.72
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s citronem a chilli papričkami 115 g",
      "count": 30,
      "pct": 2.72
    },
    {
      "productA": "Pěnová pomazánka z humra a koňaku 60 g",
      "productB": "Rillettes z tresky se sečuánským pepřem 60 g",
      "count": 29,
      "pct": 2.63
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 29,
      "pct": 2.63
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 29,
      "pct": 2.63
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v arašídovém oleji s citronem 115 g",
      "count": 29,
      "pct": 2.63
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky s olivovou tapenádou 115 g",
      "count": 29,
      "pct": 2.63
    },
    {
      "productA": "Salát z makrely s mrkví a čočkou Beluga 175 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 29,
      "pct": 2.63
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 29,
      "pct": 2.63
    },
    {
      "productA": "Sardinky s olivovou tapenádou 115 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 28,
      "pct": 2.54
    },
    {
      "productA": "Makrela ve víně s aromatickým kořením 118 g",
      "productB": "Sardinky marinované ve víně Muscadet 115 g",
      "count": 28,
      "pct": 2.54
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 28,
      "pct": 2.54
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 28,
      "pct": 2.54
    },
    {
      "productA": "Sardinky v arašídovém oleji 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 28,
      "pct": 2.54
    },
    {
      "productA": "Salát z tuňáka s paprikami a černou rýží 175 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 28,
      "pct": 2.54
    },
    {
      "productA": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 28,
      "pct": 2.54
    },
    {
      "productA": "Pěnová pomazánka z humra a koňaku 60 g",
      "productB": "Sardinky marinované ve víně Muscadet 115 g",
      "count": 27,
      "pct": 2.45
    },
    {
      "productA": "Rillettes z tresky se sečuánským pepřem 60 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 27,
      "pct": 2.45
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 27,
      "pct": 2.45
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "count": 27,
      "pct": 2.45
    },
    {
      "productA": "Sardinky s citronem a čili papričkami 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 27,
      "pct": 2.45
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v slunečnicovém oleji s rajčaty 115 g",
      "count": 27,
      "pct": 2.45
    }
  ]
};
