// Auto-generated by scripts/fetchShoptetData.js — last update: 2026-04-15
// PL: product pair co-occurrence from orders

export interface CrossSellPair {
  productA: string;
  productB: string;
  count: number;
  pct: number;
}

export interface CrossSellData {
  totalOrders: number;
  multiItemOrders: number;
  pairs: CrossSellPair[];
}

export const crossSellDataPL: CrossSellData = {
  "totalOrders": 10596,
  "multiItemOrders": 5799,
  "pairs": [
    {
      "productA": "PEPAX LANCE Round Liner",
      "productB": "PEPAX LANCE Round Liner",
      "count": 887,
      "pct": 8.37108342770857
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Bishop DaVinci V2 Liner",
      "count": 649,
      "pct": 6.124952812382031
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Round Liner",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 508,
      "pct": 4.794261985654964
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Cheyenne Safety Liner",
      "count": 471,
      "pct": 4.445073612684031
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Bishop DaVinci V2 Curved Magnum",
      "count": 358,
      "pct": 3.378633446583616
    },
    {
      "productA": "PEPAX LANCE Round Liner",
      "productB": "PEPAX LANCE Round Shader",
      "count": 316,
      "pct": 2.982257455643639
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 284,
      "pct": 2.6802567006417517
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Bishop DaVinci V2 Round Shader",
      "count": 283,
      "pct": 2.670819177047943
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Round Liner",
      "productB": "Emalla Eliot Pro Cartridge Round Shader",
      "count": 263,
      "pct": 2.4820687051717627
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Bishop DaVinci V2 Liner",
      "count": 244,
      "pct": 2.3027557568893924
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Curved Magnum",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 243,
      "pct": 2.2933182332955835
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Cheyenne Safety Soft Edge zaokrąglona końcówka płaska",
      "count": 242,
      "pct": 2.2838807097017746
    },
    {
      "productA": "Cheyenne Safety Liner - Liner Cartride",
      "productB": "Cheyenne Safety Liner - Liner Cartride",
      "count": 214,
      "pct": 2.019630049075123
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Bishop DaVinci V2 Round Shader",
      "count": 206,
      "pct": 1.9441298603246508
    },
    {
      "productA": "Dragonhawk YUE Round Liner",
      "productB": "Dragonhawk YUE Round Liner",
      "count": 201,
      "pct": 1.8969422423556057
    },
    {
      "productA": "PEPAX LANCE Curved Magnum",
      "productB": "PEPAX LANCE Round Liner",
      "count": 193,
      "pct": 1.8214420536051341
    },
    {
      "productA": "EZ INkin REVO Round Liner",
      "productB": "EZ INkin REVO Round Liner",
      "count": 174,
      "pct": 1.6421291053227631
    },
    {
      "productA": "Cheyenne Safety Liner - Liner Cartride",
      "productB": "Cheyenne Safety Magnum - płaska prosta",
      "count": 172,
      "pct": 1.6232540581351453
    },
    {
      "productA": "Elite III Round Liner",
      "productB": "Elite III Round Liner",
      "count": 169,
      "pct": 1.5949414873537182
    },
    {
      "productA": "AVA Arrow Cartridge Round Liner",
      "productB": "AVA Arrow Cartridge Round Liner",
      "count": 167,
      "pct": 1.5760664401661004
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Round Shader Long Taper",
      "count": 148,
      "pct": 1.3967534918837297
    },
    {
      "productA": "Cheyenne Safety Soft Edge zaokrąglona końcówka płaska",
      "productB": "Cheyenne Safety Soft Edge zaokrąglona końcówka płaska",
      "count": 145,
      "pct": 1.3684409211023028
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Bishop DaVinci V2 Magnum",
      "count": 145,
      "pct": 1.3684409211023028
    },
    {
      "productA": "ELITE Infini Round Liner",
      "productB": "ELITE Infini Round Liner",
      "count": 142,
      "pct": 1.3401283503208758
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Cheyenne Safety Liner",
      "count": 124,
      "pct": 1.1702529256323142
    },
    {
      "productA": "Cartridge CRAFT Liner",
      "productB": "Cartridge CRAFT Liner",
      "count": 121,
      "pct": 1.1419403548508873
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Curved Magnum",
      "productB": "Emalla Eliot Pro Cartridge Round Shader",
      "count": 120,
      "pct": 1.1325028312570782
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 111,
      "pct": 1.0475651189127972
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Curved Magnum",
      "productB": "Emalla Eliot Pro Cartridge Curved Magnum",
      "count": 111,
      "pct": 1.0475651189127972
    },
    {
      "productA": "Marker do ciała SQUIDSTER",
      "productB": "Marker do ciała SQUIDSTER",
      "count": 109,
      "pct": 1.0286900717251792
    },
    {
      "productA": "Okrągłe igły Piranha Liner - 5 sztuk",
      "productB": "Okrągłe igły Piranha Liner - 5 sztuk",
      "count": 109,
      "pct": 1.0286900717251792
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 107,
      "pct": 1.0098150245375614
    },
    {
      "productA": "Cheyenne Safety Liner - Liner Cartridge",
      "productB": "Cheyenne Safety Liner - Liner Cartridge",
      "count": 106,
      "pct": 1.0003775009437523
    },
    {
      "productA": "Cartridge Kwadron PMU Optima Liner",
      "productB": "Cartridge Kwadron PMU Optima Liner",
      "count": 104,
      "pct": 0.9815024537561344
    },
    {
      "productA": "Bishop DaVinci V2 Round Shader",
      "productB": "Bishop DaVinci V2 Round Shader",
      "count": 96,
      "pct": 0.9060022650056626
    },
    {
      "productA": "ELITE Infini Round Liner",
      "productB": "ELITE Infini Round Shader",
      "count": 89,
      "pct": 0.8399395998489996
    },
    {
      "productA": "Cartridge Kwadron Round Liner Long Taper",
      "productB": "Cartridge Kwadron Round Liner Long Taper",
      "count": 88,
      "pct": 0.8305020762551907
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Round Shader",
      "productB": "Emalla Eliot Pro Cartridge Round Shader",
      "count": 87,
      "pct": 0.8210645526613816
    },
    {
      "productA": "Dragonhawk YUE Round Liner",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 87,
      "pct": 0.8210645526613816
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 87,
      "pct": 0.8210645526613816
    },
    {
      "productA": "AVA Arrow Cartridge Curved Magnum",
      "productB": "AVA Arrow Cartridge Round Liner",
      "count": 87,
      "pct": 0.8210645526613816
    },
    {
      "productA": "Kwadron Round Shader Long Taper",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 85,
      "pct": 0.8021895054737638
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Cheyenne Safety Shader",
      "count": 82,
      "pct": 0.7738769346923368
    },
    {
      "productA": "Elite III Round Liner Bugpin",
      "productB": "Elite III Round Shader",
      "count": 81,
      "pct": 0.7644394110985278
    },
    {
      "productA": "Taśma ochronna - owijka",
      "productB": "Taśma ochronna - owijka",
      "count": 80,
      "pct": 0.7550018875047187
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Curved Magnum",
      "productB": "PEPAX LANCE Round Liner",
      "count": 80,
      "pct": 0.7550018875047187
    },
    {
      "productA": "Kwadron Soft Edge Long Taper",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 79,
      "pct": 0.7455643639109097
    },
    {
      "productA": "Cheyenne Safety Liner - Liner Cartride",
      "productB": "Cheyenne Safety Soft Edge zaokrąglona końcówka płaska",
      "count": 77,
      "pct": 0.7266893167232918
    },
    {
      "productA": "EZ REVOLUTION Round Liner Long Taper 0,35 mm",
      "productB": "EZ REVOLUTION Round Liner Long Taper 0,35 mm",
      "count": 76,
      "pct": 0.7172517931294828
    },
    {
      "productA": "Elite III Round Liner",
      "productB": "Elite III Round Shader",
      "count": 75,
      "pct": 0.7078142695356738
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Taśma ochronna - owijka",
      "count": 75,
      "pct": 0.7078142695356738
    },
    {
      "productA": "Elite III Round Liner Bugpin",
      "productB": "Elite III Round Liner Bugpin",
      "count": 74,
      "pct": 0.6983767459418648
    },
    {
      "productA": "Cartridge CRAFT Liner",
      "productB": "Cartridge CRAFT Magnum dwurzędowe",
      "count": 73,
      "pct": 0.6889392223480559
    },
    {
      "productA": "EZ REVOLUTION Round Liner Long Taper 0,35 mm",
      "productB": "EZ REVOLUTION Round Shader Long Taper 0,35 mm",
      "count": 73,
      "pct": 0.6889392223480559
    },
    {
      "productA": "Bishop DaVinci V2 Magnum",
      "productB": "Bishop DaVinci V2 Round Shader",
      "count": 72,
      "pct": 0.6795016987542469
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 72,
      "pct": 0.6795016987542469
    },
    {
      "productA": "Cartridge Mast Ocean Heart",
      "productB": "Cartridge Mast Ocean Heart",
      "count": 68,
      "pct": 0.6417516043790109
    },
    {
      "productA": "PEPAX LANCE Curved Magnum",
      "productB": "PEPAX LANCE Round Shader",
      "count": 68,
      "pct": 0.6417516043790109
    },
    {
      "productA": "Cartridge CRAFT Liner",
      "productB": "Cartridge CRAFT Shader",
      "count": 67,
      "pct": 0.6323140807852019
    },
    {
      "productA": "Cartridge CRAFT Liner",
      "productB": "Cheyenne Safety Liner",
      "count": 67,
      "pct": 0.6323140807852019
    },
    {
      "productA": "EZ INkin REVO Round Liner",
      "productB": "EZ INkin REVO Round Shader",
      "count": 67,
      "pct": 0.6323140807852019
    },
    {
      "productA": "Elite III Curved Magnum Medium Taper (soft edge)",
      "productB": "Elite III Round Liner",
      "count": 67,
      "pct": 0.6323140807852019
    },
    {
      "productA": "Kwadron Round Shader Long Taper",
      "productB": "Kwadron Round Shader Long Taper",
      "count": 66,
      "pct": 0.622876557191393
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Cartridge Cheyenne Safety Liner BugPin fine liner",
      "count": 64,
      "pct": 0.604001510003775
    },
    {
      "productA": "EZ REVOLUTION Round Shader Long Taper 0,35 mm",
      "productB": "EZ REVOLUTION Round Shader Long Taper 0,35 mm",
      "count": 63,
      "pct": 0.594563986409966
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "FineLine Round Liner - 3RL",
      "count": 63,
      "pct": 0.594563986409966
    },
    {
      "productA": "Elite III Magnum",
      "productB": "Elite III Round Shader",
      "count": 62,
      "pct": 0.5851264628161571
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Dragonhawk YUE Round Liner",
      "count": 61,
      "pct": 0.5756889392223481
    },
    {
      "productA": "AVA Arrow Cartridge Round Liner",
      "productB": "AVA Arrow Cartridge Round Shader",
      "count": 61,
      "pct": 0.5756889392223481
    },
    {
      "productA": "FineLine Round Liner - 3RL",
      "productB": "FineLine Round Liner - 3RL",
      "count": 59,
      "pct": 0.5568138920347301
    },
    {
      "productA": "Elite III Magnum",
      "productB": "Elite III Round Liner Bugpin",
      "count": 58,
      "pct": 0.5473763684409211
    },
    {
      "productA": "PEPAX LANCE Curved Magnum",
      "productB": "PEPAX LANCE Curved Magnum",
      "count": 58,
      "pct": 0.5473763684409211
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 57,
      "pct": 0.5379388448471121
    },
    {
      "productA": "CRAFT Soft Edge",
      "productB": "Cartridge CRAFT Liner",
      "count": 56,
      "pct": 0.5285013212533031
    },
    {
      "productA": "ELITE Infini Closed Curved Magnum Bugpin (SoftEdge)",
      "productB": "ELITE Infini Round Liner",
      "count": 56,
      "pct": 0.5285013212533031
    },
    {
      "productA": "Bishop DaVinci V2 Round Shader",
      "productB": "Cartridge CRAFT Liner",
      "count": 55,
      "pct": 0.5190637976594942
    },
    {
      "productA": "Cartridge CRAFT Magnum dwurzędowe",
      "productB": "Cartridge CRAFT Shader",
      "count": 55,
      "pct": 0.5190637976594942
    },
    {
      "productA": "Cheyenne Safety Shader",
      "productB": "Cheyenne Safety Shader",
      "count": 55,
      "pct": 0.5190637976594942
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "PEPAX LANCE Round Liner",
      "count": 55,
      "pct": 0.5190637976594942
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Cheyenne Safety Open Liner - mocna podszewka cartridge",
      "count": 55,
      "pct": 0.5190637976594942
    },
    {
      "productA": "Elite III Magnum",
      "productB": "Elite III Round Liner",
      "count": 54,
      "pct": 0.5096262740656852
    },
    {
      "productA": "Elite III Curved Magnum Medium Taper (soft edge)",
      "productB": "Elite III Curved Magnum Medium Taper (soft edge)",
      "count": 54,
      "pct": 0.5096262740656852
    },
    {
      "productA": "ELITE Infini Round Shader",
      "productB": "ELITE Infini Round Shader",
      "count": 54,
      "pct": 0.5096262740656852
    },
    {
      "productA": "Cheyenne BIG Magnum Soft Edge Safety cartridge, okrągły",
      "productB": "Cheyenne BIG Magnum Soft Edge Safety cartridge, okrągły",
      "count": 54,
      "pct": 0.5096262740656852
    },
    {
      "productA": "Elite III Round Liner",
      "productB": "Kwadron Flat, jednorzędowy",
      "count": 54,
      "pct": 0.5096262740656852
    },
    {
      "productA": "Bishop DaVinci V2 Round Shader",
      "productB": "Liner Bishop DaVinci V2",
      "count": 52,
      "pct": 0.4907512268780672
    },
    {
      "productA": "Revolution Round Shader Long Taper",
      "productB": "Revolution Soft Edge Long Taper",
      "count": 52,
      "pct": 0.4907512268780672
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Elite III Curved Magnum Medium Taper (soft edge)",
      "count": 52,
      "pct": 0.4907512268780672
    },
    {
      "productA": "Elite III Flat jednorzędowa",
      "productB": "Elite III Round Liner",
      "count": 51,
      "pct": 0.4813137032842582
    },
    {
      "productA": "PEPAX LANCE Round Shader",
      "productB": "PEPAX LANCE Round Shader",
      "count": 51,
      "pct": 0.4813137032842582
    },
    {
      "productA": "PEPAX LANCE Magnum",
      "productB": "PEPAX LANCE Round Liner",
      "count": 51,
      "pct": 0.4813137032842582
    },
    {
      "productA": "Cheyenne Capillary Liner",
      "productB": "Cheyenne Capillary Liner",
      "count": 50,
      "pct": 0.4718761796904492
    },
    {
      "productA": "Cheyenne Safety Magnum - płaska prosta",
      "productB": "Cheyenne Safety Magnum - płaska prosta",
      "count": 50,
      "pct": 0.4718761796904492
    },
    {
      "productA": "Cartridge Kwadron Round Liner Long Taper",
      "productB": "Cartridge Kwadron Soft Edge Long Taper Sublime",
      "count": 50,
      "pct": 0.4718761796904492
    },
    {
      "productA": "Cartridge Cheyenne Safety Liner BugPin fine liner",
      "productB": "Cheyenne Safety Shader",
      "count": 49,
      "pct": 0.4624386560966402
    },
    {
      "productA": "EZ V-SELECT Liner Cartridge",
      "productB": "EZ V-SELECT Liner Cartridge",
      "count": 49,
      "pct": 0.4624386560966402
    },
    {
      "productA": "EZ INkin REVO Curved Magnum",
      "productB": "EZ INkin REVO Round Liner",
      "count": 48,
      "pct": 0.4530011325028313
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Cartridge CRAFT Liner",
      "count": 46,
      "pct": 0.4341260853152133
    },
    {
      "productA": "Cartridge Cheyenne Safety Liner BugPin fine liner",
      "productB": "Cartridge Cheyenne Safety Liner BugPin fine liner",
      "count": 46,
      "pct": 0.4341260853152133
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "EZ INkin REVO Round Liner",
      "count": 46,
      "pct": 0.4341260853152133
    }
  ]
};
