// Auto-generated by scripts/fetchShoptetData.js — last update: 2026-04-16
// AT: product pair co-occurrence from orders

export interface CrossSellPair {
  productA: string;
  productB: string;
  count: number;
  pct: number;
}

export interface CrossSellData {
  totalOrders: number;
  multiItemOrders: number;
  pairs: CrossSellPair[];
}

export const crossSellDataAT: CrossSellData = {
  "totalOrders": 3428,
  "multiItemOrders": 2411,
  "pairs": [
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 586,
      "pct": 17.09451575262544
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Bishop DaVinci V2 Liner",
      "count": 422,
      "pct": 12.310385064177364
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Cheyenne Safety Liner",
      "count": 336,
      "pct": 9.801633605600934
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Round Shader Long Taper",
      "count": 318,
      "pct": 9.27654609101517
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Cheyenne Safety Liner",
      "count": 280,
      "pct": 8.168028004667445
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Bishop DaVinci V2 Round Shader",
      "count": 276,
      "pct": 8.051341890315053
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Bishop DaVinci V2 Liner",
      "count": 274,
      "pct": 7.992998833138857
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 234,
      "pct": 6.826137689614936
    },
    {
      "productA": "Bishop DaVinci V2 Magnum",
      "productB": "Cheyenne Safety Liner",
      "count": 230,
      "pct": 6.709451575262544
    },
    {
      "productA": "Kwadron Cartridges Round Liner Long Taper",
      "productB": "Kwadron Cartridges Round Liner Long Taper",
      "count": 205,
      "pct": 5.980163360560093
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Cheyenne Safety Liner",
      "count": 184,
      "pct": 5.367561260210035
    },
    {
      "productA": "Kwadron Cartridges Round Shader Long Taper",
      "productB": "Kwadron Cartridges Round Shader Long Taper",
      "count": 177,
      "pct": 5.1633605600933485
    },
    {
      "productA": "Kwadron Magnum Long Taper",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 173,
      "pct": 5.046674445740957
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Bishop DaVinci V2 Magnum",
      "count": 164,
      "pct": 4.784130688448075
    },
    {
      "productA": "Bishop DaVinci V2 Round Shader",
      "productB": "Cheyenne Safety Liner",
      "count": 138,
      "pct": 4.025670945157526
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Soft Edge Medium taper",
      "count": 130,
      "pct": 3.7922987164527426
    },
    {
      "productA": "Kwadron Round Shader Long Taper",
      "productB": "Kwadron Round Shader Long Taper",
      "count": 114,
      "pct": 3.325554259043174
    },
    {
      "productA": "Kwadron Soft Edge Long Taper",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 113,
      "pct": 3.296382730455076
    },
    {
      "productA": "Piranha Liner Nadeln Round Liner - 5 Stück",
      "productB": "Piranha Liner Nadeln Round Liner - 5 Stück",
      "count": 108,
      "pct": 3.150525087514586
    },
    {
      "productA": "Kwadron Magnum Medium Taper",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 106,
      "pct": 3.09218203033839
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Bishop DaVinci V2 Curved Magnum",
      "count": 104,
      "pct": 3.0338389731621938
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Bishop DaVinci V2 Magnum",
      "count": 103,
      "pct": 3.0046674445740957
    },
    {
      "productA": "Bishop DaVinci V2 Curved Magnum",
      "productB": "Bishop DaVinci V2 Round Shader",
      "count": 101,
      "pct": 2.9463243873978997
    },
    {
      "productA": "Kwadron Cartridges PMU Optima Liner",
      "productB": "Kwadron Cartridges PMU Optima Liner",
      "count": 99,
      "pct": 2.8879813302217037
    },
    {
      "productA": "Kwadron Cartridges Round Liner Long Taper",
      "productB": "Kwadron Cartridges Round Shader Long Taper",
      "count": 95,
      "pct": 2.7712952158693116
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Round Liner",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 94,
      "pct": 2.7421236872812136
    },
    {
      "productA": "Bishop DaVinci V2 Round Shader",
      "productB": "Bishop DaVinci V2 Round Shader",
      "count": 90,
      "pct": 2.6254375729288215
    },
    {
      "productA": "CRAFT Liner Cartridges",
      "productB": "CRAFT Magnum Soft Edge",
      "count": 90,
      "pct": 2.6254375729288215
    },
    {
      "productA": "Cartridge Mast Ocean Heart",
      "productB": "Cartridge Mast Ocean Heart",
      "count": 88,
      "pct": 2.5670945157526255
    },
    {
      "productA": "Cartridge Mast Ocean Heart",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 88,
      "pct": 2.5670945157526255
    },
    {
      "productA": "Kwadron Round Shader Long Taper",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 86,
      "pct": 2.5087514585764294
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron cartridge PMU Optima Liner",
      "count": 86,
      "pct": 2.5087514585764294
    },
    {
      "productA": "Kwadron cartridge PMU Optima Liner",
      "productB": "Kwadron cartridge PMU Optima Liner",
      "count": 85,
      "pct": 2.4795799299883314
    },
    {
      "productA": "Kwadron Magnum Long Taper",
      "productB": "Kwadron Round Shader Long Taper",
      "count": 83,
      "pct": 2.4212368728121354
    },
    {
      "productA": "Kwadron Magnum Medium Taper",
      "productB": "Kwadron Round Shader Long Taper",
      "count": 82,
      "pct": 2.3920653442240374
    },
    {
      "productA": "CRAFT Liner Cartridges",
      "productB": "CRAFT Liner Cartridges",
      "count": 80,
      "pct": 2.3337222870478413
    },
    {
      "productA": "CRAFT Magnum Soft Edge",
      "productB": "CRAFT Magnum Soft Edge",
      "count": 77,
      "pct": 2.2462077012835473
    },
    {
      "productA": "Kwadron Round Shader Long Taper",
      "productB": "Kwadron Soft Edge Medium taper",
      "count": 68,
      "pct": 1.9836639439906651
    },
    {
      "productA": "Kwadron Cartridges Round Shader Long Taper",
      "productB": "Kwadron Cartridges Soft Edge Long Taper Sublime",
      "count": 64,
      "pct": 1.8669778296382729
    },
    {
      "productA": "Bishop DaVinci V2 Magnum",
      "productB": "Bishop DaVinci V2 Round Shader",
      "count": 64,
      "pct": 1.8669778296382729
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Soft Edge Long Taper Sublime",
      "count": 63,
      "pct": 1.8378063010501748
    },
    {
      "productA": "EZ INkin REVO Round Liner",
      "productB": "EZ INkin REVO Round Liner",
      "count": 62,
      "pct": 1.8086347724620768
    },
    {
      "productA": "Kwadron Cartridges Round Liner Long Taper",
      "productB": "Kwadron Cartridges Soft Edge runde Schattierung Long taper",
      "count": 60,
      "pct": 1.7502917152858808
    },
    {
      "productA": "Bishop DaVinci V2 Magnum",
      "productB": "Bishop DaVinci V2 Magnum",
      "count": 60,
      "pct": 1.7502917152858808
    },
    {
      "productA": "Piranha Liner Nadeln Round Liner - 5 Stück",
      "productB": "Piranha Schattierungsnadeln Round Shader - 5Stück",
      "count": 60,
      "pct": 1.7502917152858808
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Curved Magnum",
      "productB": "Emalla Eliot Pro Cartridge Round Liner",
      "count": 58,
      "pct": 1.691948658109685
    },
    {
      "productA": "Kwadron Round Liner Medium Taper",
      "productB": "Kwadron Round Liner Medium Taper",
      "count": 57,
      "pct": 1.662777129521587
    },
    {
      "productA": "Kwadron Soft Edge Medium taper",
      "productB": "Kwadron Soft Edge Medium taper",
      "count": 57,
      "pct": 1.662777129521587
    },
    {
      "productA": "Cartridge Mast Ocean Heart",
      "productB": "Kwadron Cartridges PMU Optima Liner",
      "count": 56,
      "pct": 1.633605600933489
    },
    {
      "productA": "TOMBOW Körper Marker",
      "productB": "TOMBOW Körper Marker",
      "count": 55,
      "pct": 1.604434072345391
    },
    {
      "productA": "Cartridge Mast Ocean Heart",
      "productB": "Kwadron cartridge PMU Optima Liner",
      "count": 54,
      "pct": 1.575262543757293
    },
    {
      "productA": "CRAFT Magnum Soft Edge",
      "productB": "CRAFT Magnum flache zweireihige Cartridges",
      "count": 52,
      "pct": 1.5169194865810969
    },
    {
      "productA": "EZ INkin REVO Round Liner",
      "productB": "EZ INkin REVO Round Shader",
      "count": 51,
      "pct": 1.4877479579929989
    },
    {
      "productA": "Kwadron Magnum Long Taper",
      "productB": "Kwadron Magnum Long Taper",
      "count": 51,
      "pct": 1.4877479579929989
    },
    {
      "productA": "Cheyenne Safety Open Liner - Strong lining Cartridges",
      "productB": "Cheyenne Safety Open Liner - Strong lining Cartridges",
      "count": 50,
      "pct": 1.4585764294049008
    },
    {
      "productA": "Dragonhawk MAST Pro 2 Round Liner",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 50,
      "pct": 1.4585764294049008
    },
    {
      "productA": "EZ INkin REVO Magnum",
      "productB": "Kwadron Cartridges Round Shader Long Taper",
      "count": 48,
      "pct": 1.4002333722287048
    },
    {
      "productA": "EZ Tattoo Supply EZ REVOLUTION Round Liner Long Taper 0,35mm",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 48,
      "pct": 1.4002333722287048
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 46,
      "pct": 1.3418903150525088
    },
    {
      "productA": "Farbkappen - Ink Cups",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 45,
      "pct": 1.3127187864644108
    },
    {
      "productA": "Farbkappen - Ink Cups",
      "productB": "Farbkappen - Ink Cups",
      "count": 44,
      "pct": 1.2835472578763127
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Cheyenne Safety Open Liner - Strong lining Cartridges",
      "count": 44,
      "pct": 1.2835472578763127
    },
    {
      "productA": "Kwadron Cartridges Round Liner Long Taper",
      "productB": "Kwadron Cartridges Soft Edge Long Taper Sublime",
      "count": 43,
      "pct": 1.2543757292882147
    },
    {
      "productA": "Elite III Round Liner",
      "productB": "Elite III Round Liner",
      "count": 43,
      "pct": 1.2543757292882147
    },
    {
      "productA": "SQUIDSTER Körpermarkers",
      "productB": "SQUIDSTER Körpermarkers",
      "count": 43,
      "pct": 1.2543757292882147
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Round Shader Medium Taper",
      "count": 43,
      "pct": 1.2543757292882147
    },
    {
      "productA": "Cheyenne Safety Liner - Liner cartridge",
      "productB": "Cheyenne Safety Liner - Liner cartridge",
      "count": 42,
      "pct": 1.2252042007001167
    },
    {
      "productA": "Emalla Eliot Pro Cartridge Round Liner",
      "productB": "Emalla Eliot Pro Cartridge Round Shader",
      "count": 42,
      "pct": 1.2252042007001167
    },
    {
      "productA": "Kwadron Round Liner Medium Taper",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 42,
      "pct": 1.2252042007001167
    },
    {
      "productA": "Piranha Schattierungsnadeln Round Shader - 5Stück",
      "productB": "Piranha Schattierungsnadeln Round Shader - 5Stück",
      "count": 41,
      "pct": 1.1960326721120187
    },
    {
      "productA": "Dragonhawk YUE Round Liner",
      "productB": "Dragonhawk YUE Round Liner",
      "count": 41,
      "pct": 1.1960326721120187
    },
    {
      "productA": "Dragonhawk MAST Pro Round Liner",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 41,
      "pct": 1.1960326721120187
    },
    {
      "productA": "Kwadron Cartridges Magnum Long Taper",
      "productB": "Kwadron Cartridges Round Liner Long Taper",
      "count": 40,
      "pct": 1.1668611435239207
    },
    {
      "productA": "Griff Bandage - Grip Wrap",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 40,
      "pct": 1.1668611435239207
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Griff Bandage - Grip Wrap",
      "count": 39,
      "pct": 1.1376896149358227
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Stencil Stuff",
      "count": 39,
      "pct": 1.1376896149358227
    },
    {
      "productA": "CRAFT Liner Cartridges",
      "productB": "CRAFT Shader Cartridge",
      "count": 39,
      "pct": 1.1376896149358227
    },
    {
      "productA": "Kwadron Magnum Long Taper",
      "productB": "Kwadron Magnum Medium Taper",
      "count": 39,
      "pct": 1.1376896149358227
    },
    {
      "productA": "Dragonhawk YUE Round Liner",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 38,
      "pct": 1.1085180863477246
    },
    {
      "productA": "Kwadron Magnum Medium Taper",
      "productB": "Kwadron Soft Edge Medium taper",
      "count": 38,
      "pct": 1.1085180863477246
    },
    {
      "productA": "Kwadron Magnum Long Taper",
      "productB": "Kwadron Soft Edge Long Taper",
      "count": 37,
      "pct": 1.0793465577596266
    },
    {
      "productA": "CRAFT Magnum Soft Edge",
      "productB": "Cheyenne Safety Liner",
      "count": 37,
      "pct": 1.0793465577596266
    },
    {
      "productA": "Kwadron Round Liner Long Taper",
      "productB": "Kwadron Round Liner Medium Taper",
      "count": 36,
      "pct": 1.0501750291715286
    },
    {
      "productA": "EZ Tattoo Supply EZ REVOLUTION Round Liner Long Taper 0,35mm",
      "productB": "Kwadron Soft Edge Long Taper Sublime",
      "count": 36,
      "pct": 1.0501750291715286
    },
    {
      "productA": "Kwadron Round Liner Medium Taper",
      "productB": "Kwadron Soft Edge Medium taper",
      "count": 36,
      "pct": 1.0501750291715286
    },
    {
      "productA": "EZ REVOLUTION Magnum Long Taper Bug Pin 0,30mm",
      "productB": "EZ REVOLUTION Round Liner Long Taper 0,35mm",
      "count": 36,
      "pct": 1.0501750291715286
    },
    {
      "productA": "ECLIPSE TATTOO INK Total Black 150ml",
      "productB": "Kwadron Round Liner Long Taper",
      "count": 35,
      "pct": 1.0210035005834306
    },
    {
      "productA": "Cheyenne Safety Liner",
      "productB": "Cheyenne Safety Shader",
      "count": 35,
      "pct": 1.0210035005834306
    },
    {
      "productA": "Piranha Revolution Round Liner Long Taper",
      "productB": "Piranha Revolution Round Shader Long Taper",
      "count": 34,
      "pct": 0.9918319719953326
    },
    {
      "productA": "EZ INkin REVO Curved Magnum",
      "productB": "EZ INkin REVO Round Liner",
      "count": 34,
      "pct": 0.9918319719953326
    },
    {
      "productA": "CRAFT Liner Cartridges",
      "productB": "CRAFT Magnum flache zweireihige Cartridges",
      "count": 34,
      "pct": 0.9918319719953326
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Cheyenne Safety Shader",
      "count": 34,
      "pct": 0.9918319719953326
    },
    {
      "productA": "Griff Bandage - Grip Wrap",
      "productB": "Griff Bandage - Grip Wrap",
      "count": 33,
      "pct": 0.9626604434072347
    },
    {
      "productA": "CRAFT Magnum flache zweireihige Cartridges",
      "productB": "CRAFT Magnum flache zweireihige Cartridges",
      "count": 33,
      "pct": 0.9626604434072347
    },
    {
      "productA": "Kwadron Round Liner Medium Taper",
      "productB": "Kwadron Round Shader Long Taper",
      "count": 33,
      "pct": 0.9626604434072347
    },
    {
      "productA": "PEPAX LANCE Round Liner",
      "productB": "PEPAX LANCE Round Liner",
      "count": 33,
      "pct": 0.9626604434072347
    },
    {
      "productA": "ELITE Infini Round Liner",
      "productB": "ELITE Infini Round Liner",
      "count": 31,
      "pct": 0.9043173862310384
    },
    {
      "productA": "Bishop DaVinci V2 Liner",
      "productB": "Farbkappen - Ink Cups",
      "count": 31,
      "pct": 0.9043173862310384
    },
    {
      "productA": "Kwadron Magnum Medium Taper",
      "productB": "Kwadron Magnum Medium Taper",
      "count": 31,
      "pct": 0.9043173862310384
    },
    {
      "productA": "Kwadron Cartridges Round Liner Medium Taper",
      "productB": "Kwadron Cartridges Soft Edge Long Taper Sublime",
      "count": 30,
      "pct": 0.8751458576429404
    }
  ]
};
