// Auto-generated by scripts/updateData.js — last update: 2026-04-03
// CZ: product pair co-occurrence from order export

export interface CrossSellPair {
  productA: string;
  productB: string;
  count: number;   // number of orders containing both products
  pct: number;     // % of total orders
}

export interface CrossSellData {
  totalOrders: number;
  multiItemOrders: number;
  pairs: CrossSellPair[];
}

export const crossSellDataCZ: CrossSellData = {
  "totalOrders": 1184,
  "multiItemOrders": 981,
  "pairs": [
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 266,
      "pct": 22.47
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 173,
      "pct": 14.61
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 158,
      "pct": 13.34
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 128,
      "pct": 10.81
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 120,
      "pct": 10.14
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 114,
      "pct": 9.63
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 100,
      "pct": 8.45
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 99,
      "pct": 8.36
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 94,
      "pct": 7.94
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Tuňák v olivovém oleji 160 g",
      "count": 87,
      "pct": 7.35
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 85,
      "pct": 7.18
    },
    {
      "productA": "Makrela v olivovém oleji s citronem a pepřem 5 barev 118 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 83,
      "pct": 7.01
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 80,
      "pct": 6.76
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 79,
      "pct": 6.67
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 77,
      "pct": 6.5
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 72,
      "pct": 6.08
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 69,
      "pct": 5.83
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 69,
      "pct": 5.83
    },
    {
      "productA": "Makrela v olivovém oleji s citronem a pepřem 5 barev 118 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 65,
      "pct": 5.49
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 62,
      "pct": 5.24
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 61,
      "pct": 5.15
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky marinované ve víně Muscadet 115 g",
      "count": 60,
      "pct": 5.07
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 59,
      "pct": 4.98
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v slunečnicovém oleji s rajčaty 115 g",
      "count": 58,
      "pct": 4.9
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 56,
      "pct": 4.73
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 56,
      "pct": 4.73
    },
    {
      "productA": "Pěnová pomazánka z humra a koňaku 60 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 55,
      "pct": 4.65
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 52,
      "pct": 4.39
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 52,
      "pct": 4.39
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 49,
      "pct": 4.14
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 49,
      "pct": 4.14
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky s citronem a chilli papričkami 115 g",
      "count": 48,
      "pct": 4.05
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 47,
      "pct": 3.97
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 46,
      "pct": 3.89
    },
    {
      "productA": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 46,
      "pct": 3.89
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Tuňák v olivovém oleji 160 g",
      "count": 46,
      "pct": 3.89
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 45,
      "pct": 3.8
    },
    {
      "productA": "Pomazánka z tuňáka s parmezánem 60 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 45,
      "pct": 3.8
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v slunečnicovém oleji s rajčaty 115 g",
      "count": 44,
      "pct": 3.72
    },
    {
      "productA": "Sardinky v olivovém oleji s rajčaty 115 g",
      "productB": "Sardinky v slunečnicovém oleji s rajčaty 115 g",
      "count": 44,
      "pct": 3.72
    },
    {
      "productA": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 44,
      "pct": 3.72
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 44,
      "pct": 3.72
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v arašídovém oleji 115 g",
      "count": 43,
      "pct": 3.63
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 42,
      "pct": 3.55
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 42,
      "pct": 3.55
    },
    {
      "productA": "Sardinky v olivovém oleji s rajčaty 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 42,
      "pct": 3.55
    },
    {
      "productA": "Makrela ve víně s aromatickým kořením 118 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 41,
      "pct": 3.46
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 41,
      "pct": 3.46
    },
    {
      "productA": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 41,
      "pct": 3.46
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 40,
      "pct": 3.38
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 40,
      "pct": 3.38
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 39,
      "pct": 3.29
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 38,
      "pct": 3.21
    },
    {
      "productA": "Pomazánka z tuňáka s parmezánem 60 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 38,
      "pct": 3.21
    },
    {
      "productA": "Sardinky s olivovou tapenádou 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 37,
      "pct": 3.13
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 37,
      "pct": 3.13
    },
    {
      "productA": "Pomazánka z tuňáka s parmezánem 60 g",
      "productB": "Pěnová pomazánka z humra a koňaku 60 g",
      "count": 36,
      "pct": 3.04
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "count": 36,
      "pct": 3.04
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 36,
      "pct": 3.04
    },
    {
      "productA": "Pomazánka ze sardinek a whisky 60 g",
      "productB": "Pěnová pomazánka z humra a koňaku 60 g",
      "count": 36,
      "pct": 3.04
    },
    {
      "productA": "Makrela s rajčaty 112,5 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 35,
      "pct": 2.96
    },
    {
      "productA": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 35,
      "pct": 2.96
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 35,
      "pct": 2.96
    },
    {
      "productA": "Pěnová pomazánka z humra a koňaku 60 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 34,
      "pct": 2.87
    },
    {
      "productA": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 34,
      "pct": 2.87
    },
    {
      "productA": "Sardinky s pepřem Batak a kurkumou 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 34,
      "pct": 2.87
    },
    {
      "productA": "Makrela v olivovém oleji s citronem a pepřem 5 barev 118 g",
      "productB": "Tuňák v olivovém oleji 160 g",
      "count": 34,
      "pct": 2.87
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s citronem a chilli papričkami 115 g",
      "count": 34,
      "pct": 2.87
    },
    {
      "productA": "Makrela v olivovém oleji s citronem a pepřem 5 barev 118 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 33,
      "pct": 2.79
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "count": 33,
      "pct": 2.79
    },
    {
      "productA": "Sardinky v olivovém oleji s rajčaty 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 33,
      "pct": 2.79
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v arašídovém oleji s citronem 115 g",
      "count": 33,
      "pct": 2.79
    },
    {
      "productA": "Sardinky s olivovou tapenádou 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 33,
      "pct": 2.79
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 33,
      "pct": 2.79
    },
    {
      "productA": "Makrela Diablesse 112,5 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 32,
      "pct": 2.7
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 32,
      "pct": 2.7
    },
    {
      "productA": "Makrela v olivovém oleji s citronem a pepřem 5 barev 118 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 32,
      "pct": 2.7
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 32,
      "pct": 2.7
    },
    {
      "productA": "Salát z makrely s mrkví a čočkou Beluga 175 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 32,
      "pct": 2.7
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 32,
      "pct": 2.7
    },
    {
      "productA": "Pomazánka z makrely s limetkou 60 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 31,
      "pct": 2.62
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v arašídovém oleji s citronem 115 g",
      "count": 31,
      "pct": 2.62
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Tuňák ve vlastní šťávě 207 g",
      "count": 31,
      "pct": 2.62
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky s olivovou tapenádou 115 g",
      "count": 31,
      "pct": 2.62
    },
    {
      "productA": "Pěnová pomazánka z humra a koňaku 60 g",
      "productB": "Rillettes z tresky se sečuánským pepřem 60 g",
      "count": 30,
      "pct": 2.53
    },
    {
      "productA": "Pěnová pomazánka z humra a koňaku 60 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 30,
      "pct": 2.53
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 30,
      "pct": 2.53
    },
    {
      "productA": "Sardinky v arašídovém oleji 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 30,
      "pct": 2.53
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 30,
      "pct": 2.53
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 30,
      "pct": 2.53
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v arašídovém oleji 115 g",
      "count": 30,
      "pct": 2.53
    },
    {
      "productA": "Sardinky v arašídovém oleji 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 30,
      "pct": 2.53
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 30,
      "pct": 2.53
    },
    {
      "productA": "Salát z tuňáka s paprikami a černou rýží 175 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 30,
      "pct": 2.53
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 29,
      "pct": 2.45
    },
    {
      "productA": "Sardinky s olivovou tapenádou 115 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 29,
      "pct": 2.45
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "count": 29,
      "pct": 2.45
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Tuňák v olivovém oleji se zeleným pepřem 160 g",
      "count": 29,
      "pct": 2.45
    },
    {
      "productA": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 29,
      "pct": 2.45
    },
    {
      "productA": "Pěnová pomazánka z humra a koňaku 60 g",
      "productB": "Sardinky marinované ve víně Muscadet 115 g",
      "count": 28,
      "pct": 2.36
    }
  ]
};
