// Auto-generated by scripts/updateData.js — last update: 2026-04-08
// CZ: product pair co-occurrence from order export

export interface CrossSellPair {
  productA: string;
  productB: string;
  count: number;   // number of orders containing both products
  pct: number;     // % of total orders
}

export interface CrossSellData {
  totalOrders: number;
  multiItemOrders: number;
  pairs: CrossSellPair[];
}

export const crossSellDataCZ: CrossSellData = {
  "totalOrders": 1228,
  "multiItemOrders": 1015,
  "pairs": [
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 276,
      "pct": 22.48
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 182,
      "pct": 14.82
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 164,
      "pct": 13.36
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 133,
      "pct": 10.83
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 126,
      "pct": 10.26
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 116,
      "pct": 9.45
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 104,
      "pct": 8.47
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 103,
      "pct": 8.39
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 99,
      "pct": 8.06
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Tuňák v olivovém oleji 160 g",
      "count": 88,
      "pct": 7.17
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 86,
      "pct": 7
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 83,
      "pct": 6.76
    },
    {
      "productA": "Makrela v olivovém oleji s citronem a pepřem 5 barev 118 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 83,
      "pct": 6.76
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 81,
      "pct": 6.6
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 81,
      "pct": 6.6
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 76,
      "pct": 6.19
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 75,
      "pct": 6.11
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 72,
      "pct": 5.86
    },
    {
      "productA": "Makrela v olivovém oleji s citronem a pepřem 5 barev 118 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 65,
      "pct": 5.29
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 64,
      "pct": 5.21
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 62,
      "pct": 5.05
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky marinované ve víně Muscadet 115 g",
      "count": 61,
      "pct": 4.97
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 61,
      "pct": 4.97
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v slunečnicovém oleji s rajčaty 115 g",
      "count": 60,
      "pct": 4.89
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 59,
      "pct": 4.8
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 58,
      "pct": 4.72
    },
    {
      "productA": "Pěnová pomazánka z humra a koňaku 60 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 55,
      "pct": 4.48
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 55,
      "pct": 4.48
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 54,
      "pct": 4.4
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 53,
      "pct": 4.32
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 50,
      "pct": 4.07
    },
    {
      "productA": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 49,
      "pct": 3.99
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 49,
      "pct": 3.99
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky s citronem a chilli papričkami 115 g",
      "count": 48,
      "pct": 3.91
    },
    {
      "productA": "Sardinky v olivovém oleji s rajčaty 115 g",
      "productB": "Sardinky v slunečnicovém oleji s rajčaty 115 g",
      "count": 47,
      "pct": 3.83
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 47,
      "pct": 3.83
    },
    {
      "productA": "Pomazánka z tuňáka s parmezánem 60 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 47,
      "pct": 3.83
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v slunečnicovém oleji s rajčaty 115 g",
      "count": 46,
      "pct": 3.75
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Tuňák v olivovém oleji 160 g",
      "count": 46,
      "pct": 3.75
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 46,
      "pct": 3.75
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 46,
      "pct": 3.75
    },
    {
      "productA": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 45,
      "pct": 3.66
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 45,
      "pct": 3.66
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v arašídovém oleji 115 g",
      "count": 44,
      "pct": 3.58
    },
    {
      "productA": "Makrela ve víně s aromatickým kořením 118 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 44,
      "pct": 3.58
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 44,
      "pct": 3.58
    },
    {
      "productA": "Sardinky v olivovém oleji s rajčaty 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 44,
      "pct": 3.58
    },
    {
      "productA": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 42,
      "pct": 3.42
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 41,
      "pct": 3.34
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 40,
      "pct": 3.26
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovém oleji s timutským pepřem 115 g",
      "count": 40,
      "pct": 3.26
    },
    {
      "productA": "Pomazánka z tuňáka s parmezánem 60 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 40,
      "pct": 3.26
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 39,
      "pct": 3.18
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 39,
      "pct": 3.18
    },
    {
      "productA": "Sardinky s olivovou tapenádou 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 38,
      "pct": 3.09
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 38,
      "pct": 3.09
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 38,
      "pct": 3.09
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "count": 37,
      "pct": 3.01
    },
    {
      "productA": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 37,
      "pct": 3.01
    },
    {
      "productA": "Pomazánka z tuňáka s parmezánem 60 g",
      "productB": "Pěnová pomazánka z humra a koňaku 60 g",
      "count": 36,
      "pct": 2.93
    },
    {
      "productA": "Pomazánka ze sardinek a whisky 60 g",
      "productB": "Pěnová pomazánka z humra a koňaku 60 g",
      "count": 36,
      "pct": 2.93
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 36,
      "pct": 2.93
    },
    {
      "productA": "Makrela s rajčaty 112,5 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 35,
      "pct": 2.85
    },
    {
      "productA": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 35,
      "pct": 2.85
    },
    {
      "productA": "Pěnová pomazánka z humra a koňaku 60 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 34,
      "pct": 2.77
    },
    {
      "productA": "Sardinky s pepřem Batak a kurkumou 115 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 34,
      "pct": 2.77
    },
    {
      "productA": "Makrela v olivovém oleji s citronem a pepřem 5 barev 118 g",
      "productB": "Tuňák v olivovém oleji 160 g",
      "count": 34,
      "pct": 2.77
    },
    {
      "productA": "Sardinky v olivovém oleji s rajčaty 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 34,
      "pct": 2.77
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v arašídovém oleji s citronem 115 g",
      "count": 34,
      "pct": 2.77
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Tuňák ve vlastní šťávě 207 g",
      "count": 34,
      "pct": 2.77
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s citronem a chilli papričkami 115 g",
      "count": 34,
      "pct": 2.77
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 34,
      "pct": 2.77
    },
    {
      "productA": "Makrela v olivovém oleji s citronem a pepřem 5 barev 118 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 33,
      "pct": 2.69
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "count": 33,
      "pct": 2.69
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 33,
      "pct": 2.69
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 33,
      "pct": 2.69
    },
    {
      "productA": "Sardinky s olivovou tapenádou 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 33,
      "pct": 2.69
    },
    {
      "productA": "Sardinky s citronem a chilli papričkami 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 33,
      "pct": 2.69
    },
    {
      "productA": "Makrela Diablesse 112,5 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 32,
      "pct": 2.61
    },
    {
      "productA": "Makrela v olivovém oleji s citronem a pepřem 5 barev 118 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 32,
      "pct": 2.61
    },
    {
      "productA": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "productB": "Sardinky v arašídovém oleji s citronem 115 g",
      "count": 32,
      "pct": 2.61
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 32,
      "pct": 2.61
    },
    {
      "productA": "Salát z makrely s mrkví a čočkou Beluga 175 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 32,
      "pct": 2.61
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 31,
      "pct": 2.52
    },
    {
      "productA": "Sardinky v arašídovém oleji 115 g",
      "productB": "Sardinky v slunečnicovém oleji 115 g",
      "count": 31,
      "pct": 2.52
    },
    {
      "productA": "Makrela ve víně s aromatickým kořením 118 g",
      "productB": "Sardinky marinované ve víně Muscadet 115 g",
      "count": 31,
      "pct": 2.52
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovém oleji s aromatickým kořením 115 g",
      "count": 31,
      "pct": 2.52
    },
    {
      "productA": "Pomazánka z makrely s limetkou 60 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 31,
      "pct": 2.52
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v arašídovém oleji 115 g",
      "count": 31,
      "pct": 2.52
    },
    {
      "productA": "Sardinky v arašídovém oleji 115 g",
      "productB": "Sardinky v olivovém oleji s rajčaty 115 g",
      "count": 31,
      "pct": 2.52
    },
    {
      "productA": "Sardinky marinované ve víně Muscadet 115 g",
      "productB": "Sardinky s olivovou tapenádou 115 g",
      "count": 31,
      "pct": 2.52
    },
    {
      "productA": "Salát z tuňáka s paprikami a černou rýží 175 g",
      "productB": "Sardinky sv. Jiří v olivovém oleji 115 g",
      "count": 31,
      "pct": 2.52
    },
    {
      "productA": "Pěnová pomazánka z humra a koňaku 60 g",
      "productB": "Rillettes z tresky se sečuánským pepřem 60 g",
      "count": 30,
      "pct": 2.44
    },
    {
      "productA": "Pěnová pomazánka z humra a koňaku 60 g",
      "productB": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "count": 30,
      "pct": 2.44
    },
    {
      "productA": "Sardinky s olivovou tapenádou 115 g",
      "productB": "Sardinky s olivovým olejem a citronem 115 g",
      "count": 30,
      "pct": 2.44
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky se zeleným pepřem a kumquatem 115 g",
      "count": 30,
      "pct": 2.44
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v slunečnicovém oleji s rajčaty 115 g",
      "count": 30,
      "pct": 2.44
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 30,
      "pct": 2.44
    },
    {
      "productA": "Sardinky s olivovým olejem a citronem 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 29,
      "pct": 2.36
    },
    {
      "productA": "Sardinky s olivovým olejem a zeleným pepřem 115 g",
      "productB": "Sardinky v arašídovém oleji 115 g",
      "count": 29,
      "pct": 2.36
    }
  ]
};
