// Auto-generated by scripts/updateData.js — last update: 2026-04-08
// SK: product pair co-occurrence from order export

export interface CrossSellPair {
  productA: string;
  productB: string;
  count: number;   // number of orders containing both products
  pct: number;     // % of total orders
}

export interface CrossSellData {
  totalOrders: number;
  multiItemOrders: number;
  pairs: CrossSellPair[];
}

export const crossSellDataSK: CrossSellData = {
  "totalOrders": 902,
  "multiItemOrders": 748,
  "pairs": [
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 160,
      "pct": 17.74
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 112,
      "pct": 12.42
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 101,
      "pct": 11.2
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 96,
      "pct": 10.64
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 82,
      "pct": 9.09
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 80,
      "pct": 8.87
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 79,
      "pct": 8.76
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Tuniak v olivovom oleji 160 g",
      "count": 72,
      "pct": 7.98
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 69,
      "pct": 7.65
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 61,
      "pct": 6.76
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 58,
      "pct": 6.43
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 58,
      "pct": 6.43
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 57,
      "pct": 6.32
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v slnečnicovom oleji 115 g",
      "count": 52,
      "pct": 5.76
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 51,
      "pct": 5.65
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 51,
      "pct": 5.65
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 50,
      "pct": 5.54
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 48,
      "pct": 5.32
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 47,
      "pct": 5.21
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Tuniak vo vlastnej šťave 207 g",
      "count": 46,
      "pct": 5.1
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 45,
      "pct": 4.99
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 45,
      "pct": 4.99
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 44,
      "pct": 4.88
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Tuniak v olivovom oleji 160 g",
      "count": 42,
      "pct": 4.66
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky s citrónom a čili papričkami 115 g",
      "count": 42,
      "pct": 4.66
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Tuniak v olivovom oleji 160 g",
      "count": 42,
      "pct": 4.66
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 41,
      "pct": 4.55
    },
    {
      "productA": "Nátierka z makrely s limetkou 60 g",
      "productB": "Nátierka z tuniaka s parmezánom 60 g",
      "count": 41,
      "pct": 4.55
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v slnečnicovom oleji 115 g",
      "count": 40,
      "pct": 4.43
    },
    {
      "productA": "Sardinky v olivovom oleji s paradajkami 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 39,
      "pct": 4.32
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v arašidovom oleji 115 g",
      "count": 39,
      "pct": 4.32
    },
    {
      "productA": "Sardinky s olivami z Nice 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 38,
      "pct": 4.21
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 38,
      "pct": 4.21
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 37,
      "pct": 4.1
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Tuniak v olivovom oleji s cesnakom 160 g",
      "count": 37,
      "pct": 4.1
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 37,
      "pct": 4.1
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 37,
      "pct": 4.1
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Rillettes z tresky so sečuánskym korením 60 g",
      "count": 37,
      "pct": 4.1
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 36,
      "pct": 3.99
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 36,
      "pct": 3.99
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 36,
      "pct": 3.99
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 36,
      "pct": 3.99
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 35,
      "pct": 3.88
    },
    {
      "productA": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 35,
      "pct": 3.88
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 35,
      "pct": 3.88
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky s citrónom a čili papričkami 115 g",
      "count": 35,
      "pct": 3.88
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 34,
      "pct": 3.77
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Tuniak v olivovom oleji so zeleným korením 160 g",
      "count": 34,
      "pct": 3.77
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Penová nátierka z homára s koňakom 60 g",
      "count": 34,
      "pct": 3.77
    },
    {
      "productA": "Nátierka z makrely s limetkou 60 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 34,
      "pct": 3.77
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 33,
      "pct": 3.66
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 33,
      "pct": 3.66
    },
    {
      "productA": "Makrela Diablesse 112,5 g",
      "productB": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "count": 33,
      "pct": 3.66
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 32,
      "pct": 3.55
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Sardinky v slnečnicovom oleji 115 g",
      "count": 32,
      "pct": 3.55
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 31,
      "pct": 3.44
    },
    {
      "productA": "Sardinky Luzienne 115 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 31,
      "pct": 3.44
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 31,
      "pct": 3.44
    },
    {
      "productA": "Sardinky v slnečnicovom oleji 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 31,
      "pct": 3.44
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 31,
      "pct": 3.44
    },
    {
      "productA": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "productB": "Tuniak v olivovom oleji 160 g",
      "count": 30,
      "pct": 3.33
    },
    {
      "productA": "Nátierka zo sardiniek s whisky 60 g",
      "productB": "Penová nátierka z homára s koňakom 60 g",
      "count": 30,
      "pct": 3.33
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 29,
      "pct": 3.22
    },
    {
      "productA": "Sardinky s olivovým olejom a citrónom 115 g",
      "productB": "Tuniak vo vlastnej šťave 207 g",
      "count": 29,
      "pct": 3.22
    },
    {
      "productA": "Makrela Diablesse 112,5 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 29,
      "pct": 3.22
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky marinované vínom Muscadet 115 g",
      "count": 29,
      "pct": 3.22
    },
    {
      "productA": "Penová nátierka z homára s koňakom 60 g",
      "productB": "Rillettes z tresky so sečuánskym korením 60 g",
      "count": 29,
      "pct": 3.22
    },
    {
      "productA": "Sardinky Luzienne 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 28,
      "pct": 3.1
    },
    {
      "productA": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 28,
      "pct": 3.1
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 28,
      "pct": 3.1
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 28,
      "pct": 3.1
    },
    {
      "productA": "Makrela Diablesse 112,5 g",
      "productB": "Sardinky s citrónom a čili papričkami 115 g",
      "count": 28,
      "pct": 3.1
    },
    {
      "productA": "Tuniak v olivovom oleji 160 g",
      "productB": "Tuniak v olivovom oleji s cesnakom 160 g",
      "count": 28,
      "pct": 3.1
    },
    {
      "productA": "Makrela s omáčkou z bergamotu a kôpru 118 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 28,
      "pct": 3.1
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Makrela vo víne s aromatickým korením 118 g",
      "count": 28,
      "pct": 3.1
    },
    {
      "productA": "Makrela s paradajkami 112,5 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 28,
      "pct": 3.1
    },
    {
      "productA": "Nátierka z tuniaka s parmezánom 60 g",
      "productB": "Nátierka zo sardiniek s whisky 60 g",
      "count": 28,
      "pct": 3.1
    },
    {
      "productA": "Krémová nátierka z lososa s estragónom 60 g",
      "productB": "Rillettes z tresky so sečuánskym korením 60 g",
      "count": 28,
      "pct": 3.1
    },
    {
      "productA": "Rillettes z tresky so sečuánskym korením 60 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 28,
      "pct": 3.1
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Nátierka z tuniaka s parmezánom 60 g",
      "count": 28,
      "pct": 3.1
    },
    {
      "productA": "Nátierka z makrely s limetkou 60 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 28,
      "pct": 3.1
    },
    {
      "productA": "Royanské sardinky s omáčkou Ravigote 115 g",
      "productB": "Sardinky Luzienne 115 g",
      "count": 27,
      "pct": 2.99
    },
    {
      "productA": "Sardinky Luzienne 115 g",
      "productB": "Sardinky v oleji s omáčkou Pitomaïl 115 g",
      "count": 27,
      "pct": 2.99
    },
    {
      "productA": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "productB": "Sardinky v olivovom oleji s paradajkami 115 g",
      "count": 27,
      "pct": 2.99
    },
    {
      "productA": "Makrela s omáčkou z bergamotu a kôpru 118 g",
      "productB": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "count": 27,
      "pct": 2.99
    },
    {
      "productA": "Tuniak v olivovom oleji 160 g",
      "productB": "Tuniak vo vlastnej šťave 207 g",
      "count": 27,
      "pct": 2.99
    },
    {
      "productA": "Tuniak v olivovom oleji 160 g",
      "productB": "Tuniak v olivovom oleji so zeleným korením 160 g",
      "count": 27,
      "pct": 2.99
    },
    {
      "productA": "Nátierka z makrely s limetkou 60 g",
      "productB": "Penová nátierka z homára s koňakom 60 g",
      "count": 27,
      "pct": 2.99
    },
    {
      "productA": "Makrela s paradajkami 112,5 g",
      "productB": "Sardinky s olivovým olejom a citrónom 115 g",
      "count": 26,
      "pct": 2.88
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky v olivovom oleji s aromatickým korením 115 g",
      "count": 26,
      "pct": 2.88
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky s olivami z Nice 115 g",
      "count": 26,
      "pct": 2.88
    },
    {
      "productA": "Sardinky s citrónom a čili papričkami 115 g",
      "productB": "Sardinky v slnečnicovom oleji s paradajkami 115 g",
      "count": 26,
      "pct": 2.88
    },
    {
      "productA": "Tuniak v olivovom oleji s cesnakom 160 g",
      "productB": "Tuniak v olivovom oleji so zeleným korením 160 g",
      "count": 26,
      "pct": 2.88
    },
    {
      "productA": "Makrela s omáčkou z bergamotu a kôpru 118 g",
      "productB": "Sardinky s olivovým olejom a zeleným korením 115 g",
      "count": 26,
      "pct": 2.88
    },
    {
      "productA": "Makrela vo víne s aromatickým korením 118 g",
      "productB": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "count": 26,
      "pct": 2.88
    },
    {
      "productA": "Sardinky sv. Juraja v olivovom oleji 115 g",
      "productB": "Tuniak v olivovom oleji so zeleným korením 160 g",
      "count": 26,
      "pct": 2.88
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Tuniak v olivovom oleji s cesnakom 160 g",
      "count": 26,
      "pct": 2.88
    },
    {
      "productA": "Nátierka z makrely s limetkou 60 g",
      "productB": "Rillettes z tresky so sečuánskym korením 60 g",
      "count": 26,
      "pct": 2.88
    },
    {
      "productA": "Makrela v olivovom oleji s citrónom a 5 druhmi korenia 118 g",
      "productB": "Rillettes z tresky so sečuánskym korením 60 g",
      "count": 26,
      "pct": 2.88
    },
    {
      "productA": "Sardinky marinované vínom Muscadet 115 g",
      "productB": "Sardinky s olivovou tapenádou 115 g",
      "count": 25,
      "pct": 2.77
    }
  ]
};
