// Auto-generated by scripts/fetchShoptetDataCZ.js — last update: 2026-04-16
// CZ: hourly purchase behaviour (CZK), all-time

export interface HourlyPoint {
  dayOfWeek:    number;
  hour:         number;
  dayCount:     number;
  totalRevenue: number;
  totalOrders:  number;
  avgRevenue:   number;
  avgOrders:    number;
}

export const hourlyDataCZ: HourlyPoint[] = [
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 6,
    "totalRevenue": 32115.149999999998,
    "totalOrders": 8,
    "avgRevenue": 5352.525,
    "avgOrders": 1.3333333333333333
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 6,
    "totalRevenue": 25186.920000000002,
    "totalOrders": 13,
    "avgRevenue": 4197.820000000001,
    "avgOrders": 2.1666666666666665
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 6,
    "totalRevenue": 47086.33,
    "totalOrders": 26,
    "avgRevenue": 7847.721666666667,
    "avgOrders": 4.333333333333333
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 6,
    "totalRevenue": 55173.43000000001,
    "totalOrders": 16,
    "avgRevenue": 9195.571666666669,
    "avgOrders": 2.6666666666666665
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 6,
    "totalRevenue": 42523.909999999996,
    "totalOrders": 22,
    "avgRevenue": 7087.318333333333,
    "avgOrders": 3.6666666666666665
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 4,
    "totalRevenue": 17786.890000000003,
    "totalOrders": 12,
    "avgRevenue": 4446.722500000001,
    "avgOrders": 3
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 4,
    "totalRevenue": 18101.170000000002,
    "totalOrders": 15,
    "avgRevenue": 4525.2925000000005,
    "avgOrders": 3.75
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 4,
    "totalRevenue": 23172.06,
    "totalOrders": 17,
    "avgRevenue": 5793.015,
    "avgOrders": 4.25
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 4,
    "totalRevenue": 28877.76,
    "totalOrders": 17,
    "avgRevenue": 7219.44,
    "avgOrders": 4.25
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 4,
    "totalRevenue": 24026.89,
    "totalOrders": 18,
    "avgRevenue": 6006.7225,
    "avgOrders": 4.5
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 4,
    "totalRevenue": 56721.659999999996,
    "totalOrders": 25,
    "avgRevenue": 14180.414999999999,
    "avgOrders": 6.25
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 4,
    "totalRevenue": 22607.49,
    "totalOrders": 11,
    "avgRevenue": 5651.8725,
    "avgOrders": 2.75
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 4,
    "totalRevenue": 6722.05,
    "totalOrders": 10,
    "avgRevenue": 1680.5125,
    "avgOrders": 2.5
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 6,
    "totalRevenue": 45860.57000000001,
    "totalOrders": 26,
    "avgRevenue": 7643.428333333334,
    "avgOrders": 4.333333333333333
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 6,
    "totalRevenue": 32695.37,
    "totalOrders": 15,
    "avgRevenue": 5449.2283333333335,
    "avgOrders": 2.5
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 6,
    "totalRevenue": 41635.69,
    "totalOrders": 20,
    "avgRevenue": 6939.281666666667,
    "avgOrders": 3.3333333333333335
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 6,
    "totalRevenue": 34475.64,
    "totalOrders": 20,
    "avgRevenue": 5745.94,
    "avgOrders": 3.3333333333333335
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 4,
    "totalRevenue": 20354.05,
    "totalOrders": 12,
    "avgRevenue": 5088.5125,
    "avgOrders": 3
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 4,
    "totalRevenue": 30072.080000000005,
    "totalOrders": 8,
    "avgRevenue": 7518.020000000001,
    "avgOrders": 2
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 6,
    "totalRevenue": 5765.3099999999995,
    "totalOrders": 3,
    "avgRevenue": 960.8849999999999,
    "avgOrders": 0.5
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 6,
    "totalRevenue": 12412.72,
    "totalOrders": 12,
    "avgRevenue": 2068.7866666666664,
    "avgOrders": 2
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 6,
    "totalRevenue": 24224.079999999994,
    "totalOrders": 15,
    "avgRevenue": 4037.346666666666,
    "avgOrders": 2.5
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 6,
    "totalRevenue": 23569.300000000003,
    "totalOrders": 8,
    "avgRevenue": 3928.216666666667,
    "avgOrders": 1.3333333333333333
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 6,
    "totalRevenue": 25016.54,
    "totalOrders": 7,
    "avgRevenue": 4169.423333333333,
    "avgOrders": 1.1666666666666667
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 6,
    "totalRevenue": 12062.01,
    "totalOrders": 4,
    "avgRevenue": 2010.335,
    "avgOrders": 0.6666666666666666
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 3,
    "totalRevenue": 3414.06,
    "totalOrders": 8,
    "avgRevenue": 1138.02,
    "avgOrders": 2.6666666666666665
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 3,
    "totalRevenue": 11102.459999999997,
    "totalOrders": 5,
    "avgRevenue": 3700.8199999999993,
    "avgOrders": 1.6666666666666667
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 3,
    "totalRevenue": 7748.5199999999995,
    "totalOrders": 5,
    "avgRevenue": 2582.8399999999997,
    "avgOrders": 1.6666666666666667
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 3,
    "totalRevenue": 2110.8999999999996,
    "totalOrders": 1,
    "avgRevenue": 703.6333333333332,
    "avgOrders": 0.3333333333333333
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 3,
    "totalRevenue": 29496.29,
    "totalOrders": 10,
    "avgRevenue": 9832.096666666666,
    "avgOrders": 3.3333333333333335
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 3,
    "totalRevenue": 7798.32,
    "totalOrders": 9,
    "avgRevenue": 2599.44,
    "avgOrders": 3
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 3,
    "totalRevenue": 12409.9,
    "totalOrders": 10,
    "avgRevenue": 4136.633333333333,
    "avgOrders": 3.3333333333333335
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 3,
    "totalRevenue": 3746.3,
    "totalOrders": 6,
    "avgRevenue": 1248.7666666666667,
    "avgOrders": 2
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 4,
    "totalRevenue": 15151.729999999998,
    "totalOrders": 11,
    "avgRevenue": 3787.9324999999994,
    "avgOrders": 2.75
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 4,
    "totalRevenue": 31823.320000000003,
    "totalOrders": 8,
    "avgRevenue": 7955.830000000001,
    "avgOrders": 2
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 4,
    "totalRevenue": 24136.710000000003,
    "totalOrders": 10,
    "avgRevenue": 6034.177500000001,
    "avgOrders": 2.5
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 4,
    "totalRevenue": 14402.65,
    "totalOrders": 11,
    "avgRevenue": 3600.6625,
    "avgOrders": 2.75
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 4,
    "totalRevenue": 13384.87,
    "totalOrders": 13,
    "avgRevenue": 3346.2175,
    "avgOrders": 3.25
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 4,
    "totalRevenue": 7026.29,
    "totalOrders": 9,
    "avgRevenue": 1756.5725,
    "avgOrders": 2.25
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 4,
    "totalRevenue": 24184.61,
    "totalOrders": 19,
    "avgRevenue": 6046.1525,
    "avgOrders": 4.75
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 4,
    "totalRevenue": 36001.15,
    "totalOrders": 21,
    "avgRevenue": 9000.2875,
    "avgOrders": 5.25
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 4,
    "totalRevenue": 49879.729999999996,
    "totalOrders": 27,
    "avgRevenue": 12469.932499999999,
    "avgOrders": 6.75
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 4,
    "totalRevenue": 14388.829999999996,
    "totalOrders": 12,
    "avgRevenue": 3597.207499999999,
    "avgOrders": 3
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 4,
    "totalRevenue": 24131.670000000002,
    "totalOrders": 22,
    "avgRevenue": 6032.9175000000005,
    "avgOrders": 5.5
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 4,
    "totalRevenue": 35503.23,
    "totalOrders": 22,
    "avgRevenue": 8875.8075,
    "avgOrders": 5.5
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 4,
    "totalRevenue": 36807.71000000001,
    "totalOrders": 18,
    "avgRevenue": 9201.927500000002,
    "avgOrders": 4.5
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 4,
    "totalRevenue": 33237.759999999995,
    "totalOrders": 15,
    "avgRevenue": 8309.439999999999,
    "avgOrders": 3.75
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 4,
    "totalRevenue": 24742.19,
    "totalOrders": 17,
    "avgRevenue": 6185.5475,
    "avgOrders": 4.25
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 4,
    "totalRevenue": 8960.31,
    "totalOrders": 10,
    "avgRevenue": 2240.0775,
    "avgOrders": 2.5
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 4,
    "totalRevenue": 2776.8500000000004,
    "totalOrders": 4,
    "avgRevenue": 694.2125000000001,
    "avgOrders": 1
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 4,
    "totalRevenue": 77944.87,
    "totalOrders": 31,
    "avgRevenue": 19486.2175,
    "avgOrders": 7.75
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 4,
    "totalRevenue": 63985.45,
    "totalOrders": 33,
    "avgRevenue": 15996.3625,
    "avgOrders": 8.25
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 4,
    "totalRevenue": 36518.490000000005,
    "totalOrders": 21,
    "avgRevenue": 9129.622500000001,
    "avgOrders": 5.25
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 4,
    "totalRevenue": 57577.50000000001,
    "totalOrders": 32,
    "avgRevenue": 14394.375000000002,
    "avgOrders": 8
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 4,
    "totalRevenue": 35355.24,
    "totalOrders": 21,
    "avgRevenue": 8838.81,
    "avgOrders": 5.25
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 4,
    "totalRevenue": 28373.389999999996,
    "totalOrders": 20,
    "avgRevenue": 7093.347499999999,
    "avgOrders": 5
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 4,
    "totalRevenue": 18804.1,
    "totalOrders": 13,
    "avgRevenue": 4701.025,
    "avgOrders": 3.25
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 4,
    "totalRevenue": 34379.799999999996,
    "totalOrders": 16,
    "avgRevenue": 8594.949999999999,
    "avgOrders": 4
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 4,
    "totalRevenue": 68443.80000000002,
    "totalOrders": 18,
    "avgRevenue": 17110.950000000004,
    "avgOrders": 4.5
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 4,
    "totalRevenue": 16975.2,
    "totalOrders": 12,
    "avgRevenue": 4243.8,
    "avgOrders": 3
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 4,
    "totalRevenue": 21886.679999999997,
    "totalOrders": 8,
    "avgRevenue": 5471.669999999999,
    "avgOrders": 2
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 6,
    "totalRevenue": 5316.24,
    "totalOrders": 3,
    "avgRevenue": 886.04,
    "avgOrders": 0.5
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 6,
    "totalRevenue": 50432.860000000015,
    "totalOrders": 29,
    "avgRevenue": 8405.47666666667,
    "avgOrders": 4.833333333333333
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 6,
    "totalRevenue": 26359.460000000003,
    "totalOrders": 24,
    "avgRevenue": 4393.243333333334,
    "avgOrders": 4
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 6,
    "totalRevenue": 22141.85,
    "totalOrders": 15,
    "avgRevenue": 3690.308333333333,
    "avgOrders": 2.5
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 6,
    "totalRevenue": 46822.53,
    "totalOrders": 24,
    "avgRevenue": 7803.755,
    "avgOrders": 4
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 6,
    "totalRevenue": 15424.759999999998,
    "totalOrders": 14,
    "avgRevenue": 2570.793333333333,
    "avgOrders": 2.3333333333333335
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 6,
    "totalRevenue": 15513.269999999999,
    "totalOrders": 13,
    "avgRevenue": 2585.5449999999996,
    "avgOrders": 2.1666666666666665
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 6,
    "totalRevenue": 52361.759999999995,
    "totalOrders": 25,
    "avgRevenue": 8726.96,
    "avgOrders": 4.166666666666667
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 4,
    "totalRevenue": 1976.8600000000001,
    "totalOrders": 3,
    "avgRevenue": 494.21500000000003,
    "avgOrders": 0.75
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 4,
    "totalRevenue": 3898.3500000000004,
    "totalOrders": 3,
    "avgRevenue": 974.5875000000001,
    "avgOrders": 0.75
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 4,
    "totalRevenue": 1425.6100000000001,
    "totalOrders": 3,
    "avgRevenue": 356.40250000000003,
    "avgOrders": 0.75
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 4,
    "totalRevenue": 13292.64,
    "totalOrders": 11,
    "avgRevenue": 3323.16,
    "avgOrders": 2.75
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 4,
    "totalRevenue": 13055.400000000001,
    "totalOrders": 12,
    "avgRevenue": 3263.8500000000004,
    "avgOrders": 3
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 4,
    "totalRevenue": 44986.130000000005,
    "totalOrders": 21,
    "avgRevenue": 11246.532500000001,
    "avgOrders": 5.25
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 4,
    "totalRevenue": 24057.989999999998,
    "totalOrders": 17,
    "avgRevenue": 6014.4974999999995,
    "avgOrders": 4.25
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 4,
    "totalRevenue": 20521.12,
    "totalOrders": 10,
    "avgRevenue": 5130.28,
    "avgOrders": 2.5
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 4,
    "totalRevenue": 31845.629999999994,
    "totalOrders": 19,
    "avgRevenue": 7961.407499999998,
    "avgOrders": 4.75
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 4,
    "totalRevenue": 45869.99,
    "totalOrders": 18,
    "avgRevenue": 11467.4975,
    "avgOrders": 4.5
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 4,
    "totalRevenue": 19895.420000000006,
    "totalOrders": 7,
    "avgRevenue": 4973.855000000001,
    "avgOrders": 1.75
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 4,
    "totalRevenue": 6012.610000000001,
    "totalOrders": 7,
    "avgRevenue": 1503.1525000000001,
    "avgOrders": 1.75
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 4,
    "totalRevenue": 5424.75,
    "totalOrders": 11,
    "avgRevenue": 1356.1875,
    "avgOrders": 2.75
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 4,
    "totalRevenue": 5410.740000000001,
    "totalOrders": 6,
    "avgRevenue": 1352.6850000000002,
    "avgOrders": 1.5
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 4,
    "totalRevenue": 39729.79,
    "totalOrders": 10,
    "avgRevenue": 9932.4475,
    "avgOrders": 2.5
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 4,
    "totalRevenue": 16290.990000000002,
    "totalOrders": 10,
    "avgRevenue": 4072.7475000000004,
    "avgOrders": 2.5
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 4,
    "totalRevenue": 10780.16,
    "totalOrders": 4,
    "avgRevenue": 2695.04,
    "avgOrders": 1
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 4,
    "totalRevenue": 3395.45,
    "totalOrders": 2,
    "avgRevenue": 848.8625,
    "avgOrders": 0.5
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 6,
    "totalRevenue": 866.1199999999999,
    "totalOrders": 2,
    "avgRevenue": 144.35333333333332,
    "avgOrders": 0.3333333333333333
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 6,
    "totalRevenue": 4701.65,
    "totalOrders": 1,
    "avgRevenue": 783.6083333333332,
    "avgOrders": 0.16666666666666666
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 6,
    "totalRevenue": 1387.6100000000001,
    "totalOrders": 2,
    "avgRevenue": 231.26833333333335,
    "avgOrders": 0.3333333333333333
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 6,
    "totalRevenue": 3152.91,
    "totalOrders": 4,
    "avgRevenue": 525.485,
    "avgOrders": 0.6666666666666666
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 6,
    "totalRevenue": 28261.430000000004,
    "totalOrders": 11,
    "avgRevenue": 4710.238333333334,
    "avgOrders": 1.8333333333333333
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 6,
    "totalRevenue": 12165.66,
    "totalOrders": 11,
    "avgRevenue": 2027.61,
    "avgOrders": 1.8333333333333333
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 6,
    "totalRevenue": 10289.94,
    "totalOrders": 9,
    "avgRevenue": 1714.99,
    "avgOrders": 1.5
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 6,
    "totalRevenue": 16772.72,
    "totalOrders": 4,
    "avgRevenue": 2795.4533333333334,
    "avgOrders": 0.6666666666666666
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 6,
    "totalRevenue": 5807.46,
    "totalOrders": 5,
    "avgRevenue": 967.91,
    "avgOrders": 0.8333333333333334
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 6,
    "totalRevenue": 8536.17,
    "totalOrders": 7,
    "avgRevenue": 1422.695,
    "avgOrders": 1.1666666666666667
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 6,
    "totalRevenue": 16895.03,
    "totalOrders": 9,
    "avgRevenue": 2815.838333333333,
    "avgOrders": 1.5
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 6,
    "totalRevenue": 8662,
    "totalOrders": 3,
    "avgRevenue": 1443.6666666666667,
    "avgOrders": 0.5
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 3,
    "totalRevenue": 3293.4,
    "totalOrders": 3,
    "avgRevenue": 1097.8,
    "avgOrders": 1
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 3,
    "totalRevenue": 988.43,
    "totalOrders": 1,
    "avgRevenue": 329.47666666666663,
    "avgOrders": 0.3333333333333333
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 3,
    "totalRevenue": 728.0899999999999,
    "totalOrders": 2,
    "avgRevenue": 242.69666666666663,
    "avgOrders": 0.6666666666666666
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 3,
    "totalRevenue": 7003.3,
    "totalOrders": 8,
    "avgRevenue": 2334.4333333333334,
    "avgOrders": 2.6666666666666665
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 3,
    "totalRevenue": 13920.67,
    "totalOrders": 4,
    "avgRevenue": 4640.223333333333,
    "avgOrders": 1.3333333333333333
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 3,
    "totalRevenue": 11353.71,
    "totalOrders": 2,
    "avgRevenue": 3784.5699999999997,
    "avgOrders": 0.6666666666666666
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 3,
    "totalRevenue": 6158.66,
    "totalOrders": 7,
    "avgRevenue": 2052.8866666666668,
    "avgOrders": 2.3333333333333335
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 3,
    "totalRevenue": 2806.6099999999997,
    "totalOrders": 2,
    "avgRevenue": 935.5366666666665,
    "avgOrders": 0.6666666666666666
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 3,
    "totalRevenue": 2509.5899999999997,
    "totalOrders": 3,
    "avgRevenue": 836.5299999999999,
    "avgOrders": 1
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 3,
    "totalRevenue": 6373.59,
    "totalOrders": 8,
    "avgRevenue": 2124.53,
    "avgOrders": 2.6666666666666665
  },
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 4,
    "totalRevenue": 446.28,
    "totalOrders": 1,
    "avgRevenue": 111.57,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 4,
    "totalRevenue": 843.7900000000001,
    "totalOrders": 1,
    "avgRevenue": 210.94750000000002,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 4,
    "totalRevenue": 287.61,
    "totalOrders": 1,
    "avgRevenue": 71.9025,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 4,
    "totalRevenue": 7662.799999999999,
    "totalOrders": 4,
    "avgRevenue": 1915.6999999999998,
    "avgOrders": 1
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 4,
    "totalRevenue": 2240.49,
    "totalOrders": 2,
    "avgRevenue": 560.1225,
    "avgOrders": 0.5
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 4,
    "totalRevenue": 5733.950000000001,
    "totalOrders": 5,
    "avgRevenue": 1433.4875000000002,
    "avgOrders": 1.25
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 4,
    "totalRevenue": 4869.41,
    "totalOrders": 7,
    "avgRevenue": 1217.3525,
    "avgOrders": 1.75
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 4,
    "totalRevenue": 10640.669999999998,
    "totalOrders": 9,
    "avgRevenue": 2660.1674999999996,
    "avgOrders": 2.25
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 4,
    "totalRevenue": 8836.68,
    "totalOrders": 9,
    "avgRevenue": 2209.17,
    "avgOrders": 2.25
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 4,
    "totalRevenue": 11604.14,
    "totalOrders": 7,
    "avgRevenue": 2901.035,
    "avgOrders": 1.75
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 4,
    "totalRevenue": 1127.27,
    "totalOrders": 5,
    "avgRevenue": 281.8175,
    "avgOrders": 1.25
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 4,
    "totalRevenue": 1787.6,
    "totalOrders": 3,
    "avgRevenue": 446.9,
    "avgOrders": 0.75
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 4,
    "totalRevenue": 2379.34,
    "totalOrders": 2,
    "avgRevenue": 594.835,
    "avgOrders": 0.5
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 4,
    "totalRevenue": 9685.320000000002,
    "totalOrders": 8,
    "avgRevenue": 2421.3300000000004,
    "avgOrders": 2
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 4,
    "totalRevenue": 57664.15,
    "totalOrders": 21,
    "avgRevenue": 14416.0375,
    "avgOrders": 5.25
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 4,
    "totalRevenue": 23894.05,
    "totalOrders": 13,
    "avgRevenue": 5973.5125,
    "avgOrders": 3.25
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 4,
    "totalRevenue": 24544.890000000003,
    "totalOrders": 9,
    "avgRevenue": 6136.222500000001,
    "avgOrders": 2.25
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 4,
    "totalRevenue": 7388.4,
    "totalOrders": 5,
    "avgRevenue": 1847.1,
    "avgOrders": 1.25
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 4,
    "totalRevenue": 4337.16,
    "totalOrders": 2,
    "avgRevenue": 1084.29,
    "avgOrders": 0.5
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 4,
    "totalRevenue": 960.3100000000001,
    "totalOrders": 3,
    "avgRevenue": 240.07750000000001,
    "avgOrders": 0.75
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 4,
    "totalRevenue": 7251.18,
    "totalOrders": 9,
    "avgRevenue": 1812.795,
    "avgOrders": 2.25
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 4,
    "totalRevenue": 27010.110000000004,
    "totalOrders": 22,
    "avgRevenue": 6752.527500000001,
    "avgOrders": 5.5
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 6,
    "totalRevenue": 247.11,
    "totalOrders": 1,
    "avgRevenue": 41.185,
    "avgOrders": 0.16666666666666666
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 6,
    "totalRevenue": 3519.01,
    "totalOrders": 3,
    "avgRevenue": 586.5016666666667,
    "avgOrders": 0.5
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 6,
    "totalRevenue": 3468.9799999999996,
    "totalOrders": 5,
    "avgRevenue": 578.1633333333333,
    "avgOrders": 0.8333333333333334
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 6,
    "totalRevenue": 23028.859999999997,
    "totalOrders": 11,
    "avgRevenue": 3838.143333333333,
    "avgOrders": 1.8333333333333333
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 6,
    "totalRevenue": 45518.41999999999,
    "totalOrders": 19,
    "avgRevenue": 7586.403333333332,
    "avgOrders": 3.1666666666666665
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 6,
    "totalRevenue": 33819.67999999999,
    "totalOrders": 24,
    "avgRevenue": 5636.613333333332,
    "avgOrders": 4
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 6,
    "totalRevenue": 19099.99,
    "totalOrders": 5,
    "avgRevenue": 3183.331666666667,
    "avgOrders": 0.8333333333333334
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 4,
    "totalRevenue": 1941.32,
    "totalOrders": 2,
    "avgRevenue": 485.33,
    "avgOrders": 0.5
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 4,
    "totalRevenue": 8931.439999999999,
    "totalOrders": 2,
    "avgRevenue": 2232.8599999999997,
    "avgOrders": 0.5
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 6,
    "totalRevenue": 1415.71,
    "totalOrders": 1,
    "avgRevenue": 235.95166666666668,
    "avgOrders": 0.16666666666666666
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 6,
    "totalRevenue": 1671.08,
    "totalOrders": 1,
    "avgRevenue": 278.5133333333333,
    "avgOrders": 0.16666666666666666
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 3,
    "totalRevenue": 577.69,
    "totalOrders": 1,
    "avgRevenue": 192.56333333333336,
    "avgOrders": 0.3333333333333333
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 3,
    "totalRevenue": 163.64,
    "totalOrders": 1,
    "avgRevenue": 54.54666666666666,
    "avgOrders": 0.3333333333333333
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 3,
    "totalRevenue": 219.84,
    "totalOrders": 1,
    "avgRevenue": 73.28,
    "avgOrders": 0.3333333333333333
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 3,
    "totalRevenue": 4982.639999999999,
    "totalOrders": 5,
    "avgRevenue": 1660.8799999999999,
    "avgOrders": 1.6666666666666667
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 4,
    "totalRevenue": 118.17999999999999,
    "totalOrders": 1,
    "avgRevenue": 29.544999999999998,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 4,
    "totalRevenue": 408.26,
    "totalOrders": 1,
    "avgRevenue": 102.065,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 4,
    "totalRevenue": 2314.04,
    "totalOrders": 4,
    "avgRevenue": 578.51,
    "avgOrders": 1
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 4,
    "totalRevenue": 14174.380000000001,
    "totalOrders": 8,
    "avgRevenue": 3543.5950000000003,
    "avgOrders": 2
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 4,
    "totalRevenue": 325.61000000000007,
    "totalOrders": 1,
    "avgRevenue": 81.40250000000002,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 4,
    "totalRevenue": 163.64,
    "totalOrders": 1,
    "avgRevenue": 40.91,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 4,
    "totalRevenue": 20751.4,
    "totalOrders": 1,
    "avgRevenue": 5187.85,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 4,
    "totalRevenue": 4132.24,
    "totalOrders": 1,
    "avgRevenue": 1033.06,
    "avgOrders": 0.25
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 6,
    "totalRevenue": 633.06,
    "totalOrders": 2,
    "avgRevenue": 105.50999999999999,
    "avgOrders": 0.3333333333333333
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 4,
    "totalRevenue": 6866.110000000001,
    "totalOrders": 3,
    "avgRevenue": 1716.5275000000001,
    "avgOrders": 0.75
  }
];
