// Auto-generated by scripts/fetchShoptetDataDE.js — last update: 2026-04-17
// DE: hourly purchase behaviour (EUR), all-time

export interface HourlyPoint {
  dayOfWeek:    number;  // 0 = Sunday … 6 = Saturday
  hour:         number;  // 0–23
  dayCount:     number;
  totalRevenue: number;
  totalOrders:  number;
  avgRevenue:   number;
  avgOrders:    number;
}

export const hourlyDataDE: HourlyPoint[] = [
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 167,
    "totalRevenue": 17807.86999999999,
    "totalOrders": 175,
    "avgRevenue": 106.63395209580834,
    "avgOrders": 1.0479041916167664
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 165,
    "totalRevenue": 16582.599999999988,
    "totalOrders": 176,
    "avgRevenue": 100.50060606060599,
    "avgOrders": 1.0666666666666667
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 161,
    "totalRevenue": 13626.11,
    "totalOrders": 161,
    "avgRevenue": 84.63422360248448,
    "avgOrders": 1
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 165,
    "totalRevenue": 6464.650000000003,
    "totalOrders": 71,
    "avgRevenue": 39.17969696969699,
    "avgOrders": 0.4303030303030303
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 165,
    "totalRevenue": 12718.19,
    "totalOrders": 129,
    "avgRevenue": 77.0799393939394,
    "avgOrders": 0.7818181818181819
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 165,
    "totalRevenue": 20205.45,
    "totalOrders": 182,
    "avgRevenue": 122.45727272727274,
    "avgOrders": 1.103030303030303
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 163,
    "totalRevenue": 14662.309999999998,
    "totalOrders": 160,
    "avgRevenue": 89.95282208588955,
    "avgOrders": 0.9815950920245399
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 167,
    "totalRevenue": 20363.23999999999,
    "totalOrders": 189,
    "avgRevenue": 121.93556886227539,
    "avgOrders": 1.1317365269461077
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 163,
    "totalRevenue": 10726.749999999996,
    "totalOrders": 142,
    "avgRevenue": 65.80828220858893,
    "avgOrders": 0.8711656441717791
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 163,
    "totalRevenue": 20754.240000000005,
    "totalOrders": 194,
    "avgRevenue": 127.3266257668712,
    "avgOrders": 1.1901840490797546
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 165,
    "totalRevenue": 17759.570000000003,
    "totalOrders": 171,
    "avgRevenue": 107.6337575757576,
    "avgOrders": 1.0363636363636364
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 165,
    "totalRevenue": 19014.089999999997,
    "totalOrders": 182,
    "avgRevenue": 115.23690909090907,
    "avgOrders": 1.103030303030303
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 167,
    "totalRevenue": 22067.999999999993,
    "totalOrders": 141,
    "avgRevenue": 132.14371257485027,
    "avgOrders": 0.844311377245509
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 167,
    "totalRevenue": 16674.350000000002,
    "totalOrders": 163,
    "avgRevenue": 99.84640718562875,
    "avgOrders": 0.9760479041916168
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 161,
    "totalRevenue": 8077.680000000001,
    "totalOrders": 128,
    "avgRevenue": 50.17192546583852,
    "avgOrders": 0.7950310559006211
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 163,
    "totalRevenue": 10167.689999999995,
    "totalOrders": 118,
    "avgRevenue": 62.378466257668684,
    "avgOrders": 0.7239263803680982
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 163,
    "totalRevenue": 22411.41,
    "totalOrders": 201,
    "avgRevenue": 137.49331288343558,
    "avgOrders": 1.2331288343558282
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 165,
    "totalRevenue": 4574.449999999999,
    "totalOrders": 67,
    "avgRevenue": 27.723939393939386,
    "avgOrders": 0.40606060606060607
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 165,
    "totalRevenue": 17732.300000000003,
    "totalOrders": 180,
    "avgRevenue": 107.46848484848486,
    "avgOrders": 1.0909090909090908
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 167,
    "totalRevenue": 14881.480000000003,
    "totalOrders": 143,
    "avgRevenue": 89.11065868263475,
    "avgOrders": 0.8562874251497006
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 165,
    "totalRevenue": 17950.300000000003,
    "totalOrders": 169,
    "avgRevenue": 108.78969696969699,
    "avgOrders": 1.0242424242424242
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 161,
    "totalRevenue": 3476.77,
    "totalOrders": 39,
    "avgRevenue": 21.594844720496894,
    "avgOrders": 0.2422360248447205
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 158,
    "totalRevenue": 8064.949999999999,
    "totalOrders": 111,
    "avgRevenue": 51.043987341772144,
    "avgOrders": 0.7025316455696202
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 158,
    "totalRevenue": 9400.640000000001,
    "totalOrders": 106,
    "avgRevenue": 59.49772151898735,
    "avgOrders": 0.6708860759493671
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 163,
    "totalRevenue": 16133.359999999999,
    "totalOrders": 156,
    "avgRevenue": 98.97766871165643,
    "avgOrders": 0.9570552147239264
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 165,
    "totalRevenue": 14697.54,
    "totalOrders": 185,
    "avgRevenue": 89.07600000000001,
    "avgOrders": 1.121212121212121
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 165,
    "totalRevenue": 12404.529999999997,
    "totalOrders": 176,
    "avgRevenue": 75.17896969696967,
    "avgOrders": 1.0666666666666667
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 165,
    "totalRevenue": 17403.049999999996,
    "totalOrders": 178,
    "avgRevenue": 105.47303030303027,
    "avgOrders": 1.0787878787878789
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 165,
    "totalRevenue": 655.8399999999999,
    "totalOrders": 11,
    "avgRevenue": 3.974787878787878,
    "avgOrders": 0.06666666666666667
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 165,
    "totalRevenue": 1026.84,
    "totalOrders": 18,
    "avgRevenue": 6.223272727272727,
    "avgOrders": 0.10909090909090909
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 165,
    "totalRevenue": 13608.050000000007,
    "totalOrders": 158,
    "avgRevenue": 82.47303030303034,
    "avgOrders": 0.9575757575757575
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 165,
    "totalRevenue": 14487.03,
    "totalOrders": 152,
    "avgRevenue": 87.80018181818183,
    "avgOrders": 0.9212121212121213
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 158,
    "totalRevenue": 11268.950000000003,
    "totalOrders": 109,
    "avgRevenue": 71.3224683544304,
    "avgOrders": 0.689873417721519
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 165,
    "totalRevenue": 7869.75,
    "totalOrders": 96,
    "avgRevenue": 47.695454545454545,
    "avgOrders": 0.5818181818181818
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 165,
    "totalRevenue": 19594.879999999997,
    "totalOrders": 210,
    "avgRevenue": 118.75684848484848,
    "avgOrders": 1.2727272727272727
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 165,
    "totalRevenue": 12323.66,
    "totalOrders": 150,
    "avgRevenue": 74.68884848484848,
    "avgOrders": 0.9090909090909091
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 161,
    "totalRevenue": 14410.530000000006,
    "totalOrders": 151,
    "avgRevenue": 89.506397515528,
    "avgOrders": 0.937888198757764
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 163,
    "totalRevenue": 16308.149999999996,
    "totalOrders": 211,
    "avgRevenue": 100.04999999999997,
    "avgOrders": 1.294478527607362
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 165,
    "totalRevenue": 22552.530000000002,
    "totalOrders": 185,
    "avgRevenue": 136.68200000000002,
    "avgOrders": 1.121212121212121
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 165,
    "totalRevenue": 17424.62999999999,
    "totalOrders": 231,
    "avgRevenue": 105.60381818181813,
    "avgOrders": 1.4
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 165,
    "totalRevenue": 15817.050000000001,
    "totalOrders": 176,
    "avgRevenue": 95.8609090909091,
    "avgOrders": 1.0666666666666667
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 165,
    "totalRevenue": 14150.980000000001,
    "totalOrders": 135,
    "avgRevenue": 85.76351515151516,
    "avgOrders": 0.8181818181818182
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 167,
    "totalRevenue": 1599.94,
    "totalOrders": 17,
    "avgRevenue": 9.580479041916169,
    "avgOrders": 0.10179640718562874
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 165,
    "totalRevenue": 2319.38,
    "totalOrders": 42,
    "avgRevenue": 14.056848484848485,
    "avgOrders": 0.2545454545454545
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 165,
    "totalRevenue": 14097.799999999996,
    "totalOrders": 145,
    "avgRevenue": 85.44121212121209,
    "avgOrders": 0.8787878787878788
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 161,
    "totalRevenue": 11637.600000000002,
    "totalOrders": 116,
    "avgRevenue": 72.2832298136646,
    "avgOrders": 0.7204968944099379
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 158,
    "totalRevenue": 11977.239999999998,
    "totalOrders": 125,
    "avgRevenue": 75.80531645569619,
    "avgOrders": 0.7911392405063291
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 158,
    "totalRevenue": 5341.209999999999,
    "totalOrders": 85,
    "avgRevenue": 33.805126582278476,
    "avgOrders": 0.5379746835443038
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 165,
    "totalRevenue": 23949.309999999998,
    "totalOrders": 219,
    "avgRevenue": 145.1473333333333,
    "avgOrders": 1.3272727272727274
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 167,
    "totalRevenue": 23040.550000000003,
    "totalOrders": 214,
    "avgRevenue": 137.96736526946108,
    "avgOrders": 1.281437125748503
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 167,
    "totalRevenue": 16278.020000000002,
    "totalOrders": 196,
    "avgRevenue": 97.47317365269463,
    "avgOrders": 1.1736526946107784
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 161,
    "totalRevenue": 7411.089999999999,
    "totalOrders": 74,
    "avgRevenue": 46.031614906832296,
    "avgOrders": 0.45962732919254656
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 158,
    "totalRevenue": 9450.98,
    "totalOrders": 112,
    "avgRevenue": 59.81632911392405,
    "avgOrders": 0.7088607594936709
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 165,
    "totalRevenue": 13643.509999999997,
    "totalOrders": 127,
    "avgRevenue": 82.68793939393937,
    "avgOrders": 0.7696969696969697
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 161,
    "totalRevenue": 13161.349999999997,
    "totalOrders": 158,
    "avgRevenue": 81.74751552795028,
    "avgOrders": 0.9813664596273292
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 161,
    "totalRevenue": 11317.390000000003,
    "totalOrders": 123,
    "avgRevenue": 70.29434782608698,
    "avgOrders": 0.7639751552795031
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 158,
    "totalRevenue": 5408.829999999998,
    "totalOrders": 59,
    "avgRevenue": 34.233101265822775,
    "avgOrders": 0.37341772151898733
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 158,
    "totalRevenue": 8821.400000000001,
    "totalOrders": 104,
    "avgRevenue": 55.831645569620264,
    "avgOrders": 0.6582278481012658
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 165,
    "totalRevenue": 13366.890000000001,
    "totalOrders": 181,
    "avgRevenue": 81.01145454545455,
    "avgOrders": 1.096969696969697
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 165,
    "totalRevenue": 13287.960000000005,
    "totalOrders": 139,
    "avgRevenue": 80.53309090909093,
    "avgOrders": 0.8424242424242424
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 165,
    "totalRevenue": 15200.37,
    "totalOrders": 168,
    "avgRevenue": 92.12345454545455,
    "avgOrders": 1.018181818181818
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 167,
    "totalRevenue": 17138.700000000008,
    "totalOrders": 161,
    "avgRevenue": 102.62694610778448,
    "avgOrders": 0.9640718562874252
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 161,
    "totalRevenue": 11667.45,
    "totalOrders": 148,
    "avgRevenue": 72.46863354037268,
    "avgOrders": 0.9192546583850931
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 161,
    "totalRevenue": 11882.539999999999,
    "totalOrders": 115,
    "avgRevenue": 73.80459627329192,
    "avgOrders": 0.7142857142857143
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 158,
    "totalRevenue": 10741.439999999999,
    "totalOrders": 102,
    "avgRevenue": 67.98379746835442,
    "avgOrders": 0.6455696202531646
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 165,
    "totalRevenue": 7677.530000000001,
    "totalOrders": 96,
    "avgRevenue": 46.53048484848485,
    "avgOrders": 0.5818181818181818
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 165,
    "totalRevenue": 15717.369999999994,
    "totalOrders": 154,
    "avgRevenue": 95.25678787878783,
    "avgOrders": 0.9333333333333333
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 161,
    "totalRevenue": 12345.840000000002,
    "totalOrders": 149,
    "avgRevenue": 76.68223602484473,
    "avgOrders": 0.9254658385093167
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 158,
    "totalRevenue": 13081.509999999998,
    "totalOrders": 127,
    "avgRevenue": 82.79436708860759,
    "avgOrders": 0.8037974683544303
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 163,
    "totalRevenue": 12352.800000000003,
    "totalOrders": 141,
    "avgRevenue": 75.78404907975462,
    "avgOrders": 0.8650306748466258
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 165,
    "totalRevenue": 19985.94999999999,
    "totalOrders": 186,
    "avgRevenue": 121.12696969696964,
    "avgOrders": 1.1272727272727272
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 165,
    "totalRevenue": 16464.589999999997,
    "totalOrders": 186,
    "avgRevenue": 99.78539393939391,
    "avgOrders": 1.1272727272727272
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 165,
    "totalRevenue": 12966.950000000004,
    "totalOrders": 169,
    "avgRevenue": 78.58757575757578,
    "avgOrders": 1.0242424242424242
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 165,
    "totalRevenue": 3236.8999999999996,
    "totalOrders": 30,
    "avgRevenue": 19.617575757575754,
    "avgOrders": 0.18181818181818182
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 165,
    "totalRevenue": 16931.1,
    "totalOrders": 195,
    "avgRevenue": 102.61272727272727,
    "avgOrders": 1.1818181818181819
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 167,
    "totalRevenue": 15574.300000000001,
    "totalOrders": 149,
    "avgRevenue": 93.25928143712575,
    "avgOrders": 0.8922155688622755
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 167,
    "totalRevenue": 19282.280000000017,
    "totalOrders": 173,
    "avgRevenue": 115.46275449101806,
    "avgOrders": 1.035928143712575
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 165,
    "totalRevenue": 6783.339999999998,
    "totalOrders": 99,
    "avgRevenue": 41.111151515151505,
    "avgOrders": 0.6
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 165,
    "totalRevenue": 12794.360000000008,
    "totalOrders": 142,
    "avgRevenue": 77.5415757575758,
    "avgOrders": 0.8606060606060606
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 165,
    "totalRevenue": 17280.15999999999,
    "totalOrders": 161,
    "avgRevenue": 104.72824242424235,
    "avgOrders": 0.9757575757575757
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 158,
    "totalRevenue": 9954.220000000001,
    "totalOrders": 113,
    "avgRevenue": 63.0013924050633,
    "avgOrders": 0.7151898734177216
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 163,
    "totalRevenue": 10007.960000000003,
    "totalOrders": 146,
    "avgRevenue": 61.39852760736198,
    "avgOrders": 0.8957055214723927
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 165,
    "totalRevenue": 529.4599999999999,
    "totalOrders": 11,
    "avgRevenue": 3.208848484848484,
    "avgOrders": 0.06666666666666667
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 165,
    "totalRevenue": 2784.6900000000005,
    "totalOrders": 43,
    "avgRevenue": 16.876909090909095,
    "avgOrders": 0.2606060606060606
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 165,
    "totalRevenue": 7925.0199999999995,
    "totalOrders": 88,
    "avgRevenue": 48.03042424242424,
    "avgOrders": 0.5333333333333333
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 161,
    "totalRevenue": 12369.890000000003,
    "totalOrders": 126,
    "avgRevenue": 76.83161490683231,
    "avgOrders": 0.782608695652174
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 158,
    "totalRevenue": 8408.64,
    "totalOrders": 67,
    "avgRevenue": 53.21924050632911,
    "avgOrders": 0.4240506329113924
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 158,
    "totalRevenue": 13782.899999999992,
    "totalOrders": 115,
    "avgRevenue": 87.23354430379742,
    "avgOrders": 0.7278481012658228
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 165,
    "totalRevenue": 517.76,
    "totalOrders": 10,
    "avgRevenue": 3.137939393939394,
    "avgOrders": 0.06060606060606061
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 167,
    "totalRevenue": 6931.520000000001,
    "totalOrders": 74,
    "avgRevenue": 41.506107784431144,
    "avgOrders": 0.4431137724550898
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 167,
    "totalRevenue": 984.7600000000001,
    "totalOrders": 16,
    "avgRevenue": 5.896766467065869,
    "avgOrders": 0.09580838323353294
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 165,
    "totalRevenue": 14590.959999999992,
    "totalOrders": 148,
    "avgRevenue": 88.43006060606055,
    "avgOrders": 0.896969696969697
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 163,
    "totalRevenue": 1749.22,
    "totalOrders": 18,
    "avgRevenue": 10.731411042944785,
    "avgOrders": 0.11042944785276074
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 167,
    "totalRevenue": 3364.5299999999993,
    "totalOrders": 47,
    "avgRevenue": 20.146886227544908,
    "avgOrders": 0.281437125748503
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 167,
    "totalRevenue": 17077.649999999994,
    "totalOrders": 135,
    "avgRevenue": 102.26137724550895,
    "avgOrders": 0.8083832335329342
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 167,
    "totalRevenue": 14675.970000000003,
    "totalOrders": 172,
    "avgRevenue": 87.88005988023954,
    "avgOrders": 1.029940119760479
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 158,
    "totalRevenue": 5275.68,
    "totalOrders": 41,
    "avgRevenue": 33.39037974683544,
    "avgOrders": 0.25949367088607594
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 165,
    "totalRevenue": 14348.38,
    "totalOrders": 159,
    "avgRevenue": 86.95987878787878,
    "avgOrders": 0.9636363636363636
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 161,
    "totalRevenue": 10968.7,
    "totalOrders": 99,
    "avgRevenue": 68.12857142857143,
    "avgOrders": 0.6149068322981367
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 163,
    "totalRevenue": 14767.699999999995,
    "totalOrders": 149,
    "avgRevenue": 90.59938650306745,
    "avgOrders": 0.9141104294478528
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 167,
    "totalRevenue": 9717.460000000006,
    "totalOrders": 120,
    "avgRevenue": 58.188383233532974,
    "avgOrders": 0.718562874251497
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 165,
    "totalRevenue": 15609.700000000006,
    "totalOrders": 147,
    "avgRevenue": 94.60424242424246,
    "avgOrders": 0.8909090909090909
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 165,
    "totalRevenue": 11540.200000000003,
    "totalOrders": 147,
    "avgRevenue": 69.94060606060607,
    "avgOrders": 0.8909090909090909
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 161,
    "totalRevenue": 14540.060000000003,
    "totalOrders": 141,
    "avgRevenue": 90.31093167701866,
    "avgOrders": 0.8757763975155279
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 163,
    "totalRevenue": 10180.410000000003,
    "totalOrders": 144,
    "avgRevenue": 62.45650306748468,
    "avgOrders": 0.8834355828220859
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 167,
    "totalRevenue": 16826.799999999992,
    "totalOrders": 168,
    "avgRevenue": 100.7592814371257,
    "avgOrders": 1.0059880239520957
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 161,
    "totalRevenue": 8563.659999999996,
    "totalOrders": 102,
    "avgRevenue": 53.19043478260867,
    "avgOrders": 0.6335403726708074
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 158,
    "totalRevenue": 11743.979999999998,
    "totalOrders": 94,
    "avgRevenue": 74.32898734177213,
    "avgOrders": 0.5949367088607594
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 163,
    "totalRevenue": 12823.619999999997,
    "totalOrders": 135,
    "avgRevenue": 78.67251533742329,
    "avgOrders": 0.8282208588957055
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 165,
    "totalRevenue": 13349.999999999998,
    "totalOrders": 152,
    "avgRevenue": 80.90909090909089,
    "avgOrders": 0.9212121212121213
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 165,
    "totalRevenue": 13073.9,
    "totalOrders": 138,
    "avgRevenue": 79.23575757575757,
    "avgOrders": 0.8363636363636363
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 165,
    "totalRevenue": 17107.929999999993,
    "totalOrders": 170,
    "avgRevenue": 103.6844242424242,
    "avgOrders": 1.0303030303030303
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 163,
    "totalRevenue": 7810.76,
    "totalOrders": 101,
    "avgRevenue": 47.91877300613497,
    "avgOrders": 0.6196319018404908
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 165,
    "totalRevenue": 14407.769999999997,
    "totalOrders": 114,
    "avgRevenue": 87.31981818181816,
    "avgOrders": 0.6909090909090909
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 165,
    "totalRevenue": 942.12,
    "totalOrders": 28,
    "avgRevenue": 5.709818181818182,
    "avgOrders": 0.1696969696969697
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 165,
    "totalRevenue": 13668.24,
    "totalOrders": 180,
    "avgRevenue": 82.83781818181818,
    "avgOrders": 1.0909090909090908
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 161,
    "totalRevenue": 15021.199999999999,
    "totalOrders": 157,
    "avgRevenue": 93.29937888198756,
    "avgOrders": 0.9751552795031055
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 161,
    "totalRevenue": 10928.060000000003,
    "totalOrders": 117,
    "avgRevenue": 67.876149068323,
    "avgOrders": 0.7267080745341615
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 165,
    "totalRevenue": 15188.989999999996,
    "totalOrders": 174,
    "avgRevenue": 92.05448484848482,
    "avgOrders": 1.0545454545454545
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 158,
    "totalRevenue": 11423.520000000002,
    "totalOrders": 100,
    "avgRevenue": 72.3007594936709,
    "avgOrders": 0.6329113924050633
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 165,
    "totalRevenue": 12974.67,
    "totalOrders": 147,
    "avgRevenue": 78.63436363636363,
    "avgOrders": 0.8909090909090909
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 165,
    "totalRevenue": 2914.8599999999997,
    "totalOrders": 35,
    "avgRevenue": 17.665818181818178,
    "avgOrders": 0.21212121212121213
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 165,
    "totalRevenue": 3806.5800000000004,
    "totalOrders": 49,
    "avgRevenue": 23.07018181818182,
    "avgOrders": 0.296969696969697
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 165,
    "totalRevenue": 12574.07,
    "totalOrders": 171,
    "avgRevenue": 76.20648484848485,
    "avgOrders": 1.0363636363636364
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 161,
    "totalRevenue": 10882.709999999997,
    "totalOrders": 124,
    "avgRevenue": 67.59447204968943,
    "avgOrders": 0.7701863354037267
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 165,
    "totalRevenue": 12772.550000000003,
    "totalOrders": 157,
    "avgRevenue": 77.40939393939395,
    "avgOrders": 0.9515151515151515
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 165,
    "totalRevenue": 21798.129999999994,
    "totalOrders": 233,
    "avgRevenue": 132.10987878787876,
    "avgOrders": 1.412121212121212
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 167,
    "totalRevenue": 3217.7899999999995,
    "totalOrders": 20,
    "avgRevenue": 19.26820359281437,
    "avgOrders": 0.11976047904191617
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 167,
    "totalRevenue": 6386.149999999998,
    "totalOrders": 66,
    "avgRevenue": 38.240419161676634,
    "avgOrders": 0.39520958083832336
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 167,
    "totalRevenue": 16614.63,
    "totalOrders": 144,
    "avgRevenue": 99.48880239520959,
    "avgOrders": 0.8622754491017964
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 163,
    "totalRevenue": 1487.5699999999997,
    "totalOrders": 29,
    "avgRevenue": 9.126196319018403,
    "avgOrders": 0.17791411042944785
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 163,
    "totalRevenue": 14432.800000000001,
    "totalOrders": 137,
    "avgRevenue": 88.54478527607363,
    "avgOrders": 0.8404907975460123
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 158,
    "totalRevenue": 816.64,
    "totalOrders": 6,
    "avgRevenue": 5.1686075949367085,
    "avgOrders": 0.0379746835443038
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 167,
    "totalRevenue": 17341.68,
    "totalOrders": 169,
    "avgRevenue": 103.84239520958084,
    "avgOrders": 1.0119760479041917
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 165,
    "totalRevenue": 11066.7,
    "totalOrders": 107,
    "avgRevenue": 67.0709090909091,
    "avgOrders": 0.6484848484848484
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 167,
    "totalRevenue": 2834.1099999999997,
    "totalOrders": 38,
    "avgRevenue": 16.97071856287425,
    "avgOrders": 0.2275449101796407
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 158,
    "totalRevenue": 4350.379999999999,
    "totalOrders": 44,
    "avgRevenue": 27.534050632911388,
    "avgOrders": 0.27848101265822783
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 163,
    "totalRevenue": 10397.540000000005,
    "totalOrders": 98,
    "avgRevenue": 63.78858895705524,
    "avgOrders": 0.6012269938650306
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 161,
    "totalRevenue": 356.40999999999997,
    "totalOrders": 10,
    "avgRevenue": 2.213726708074534,
    "avgOrders": 0.062111801242236024
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 161,
    "totalRevenue": 1172.33,
    "totalOrders": 17,
    "avgRevenue": 7.281552795031056,
    "avgOrders": 0.10559006211180125
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 165,
    "totalRevenue": 12631.670000000007,
    "totalOrders": 160,
    "avgRevenue": 76.5555757575758,
    "avgOrders": 0.9696969696969697
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 158,
    "totalRevenue": 8904.71,
    "totalOrders": 97,
    "avgRevenue": 56.35892405063291,
    "avgOrders": 0.6139240506329114
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 163,
    "totalRevenue": 5039.89,
    "totalOrders": 71,
    "avgRevenue": 30.919570552147242,
    "avgOrders": 0.43558282208588955
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 163,
    "totalRevenue": 3568.5799999999995,
    "totalOrders": 36,
    "avgRevenue": 21.893128834355824,
    "avgOrders": 0.22085889570552147
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 161,
    "totalRevenue": 5485.59,
    "totalOrders": 64,
    "avgRevenue": 34.07198757763975,
    "avgOrders": 0.39751552795031053
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 158,
    "totalRevenue": 334.66,
    "totalOrders": 8,
    "avgRevenue": 2.118101265822785,
    "avgOrders": 0.05063291139240506
  },
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 163,
    "totalRevenue": 4566.160000000001,
    "totalOrders": 49,
    "avgRevenue": 28.013251533742334,
    "avgOrders": 0.3006134969325153
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 158,
    "totalRevenue": 1399.8300000000002,
    "totalOrders": 15,
    "avgRevenue": 8.859683544303799,
    "avgOrders": 0.0949367088607595
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 163,
    "totalRevenue": 1593.0099999999998,
    "totalOrders": 11,
    "avgRevenue": 9.773067484662576,
    "avgOrders": 0.06748466257668712
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 165,
    "totalRevenue": 1153.84,
    "totalOrders": 6,
    "avgRevenue": 6.992969696969697,
    "avgOrders": 0.03636363636363636
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 165,
    "totalRevenue": 4873.350000000001,
    "totalOrders": 67,
    "avgRevenue": 29.535454545454552,
    "avgOrders": 0.40606060606060607
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 161,
    "totalRevenue": 2603.6299999999997,
    "totalOrders": 34,
    "avgRevenue": 16.171614906832296,
    "avgOrders": 0.2111801242236025
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 165,
    "totalRevenue": 1824.4700000000005,
    "totalOrders": 18,
    "avgRevenue": 11.057393939393942,
    "avgOrders": 0.10909090909090909
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 161,
    "totalRevenue": 346.39000000000004,
    "totalOrders": 8,
    "avgRevenue": 2.151490683229814,
    "avgOrders": 0.049689440993788817
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 158,
    "totalRevenue": 2556.6200000000003,
    "totalOrders": 14,
    "avgRevenue": 16.181139240506333,
    "avgOrders": 0.08860759493670886
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 158,
    "totalRevenue": 7988.710000000002,
    "totalOrders": 107,
    "avgRevenue": 50.56145569620254,
    "avgOrders": 0.6772151898734177
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 165,
    "totalRevenue": 5832.669999999998,
    "totalOrders": 54,
    "avgRevenue": 35.34951515151514,
    "avgOrders": 0.32727272727272727
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 165,
    "totalRevenue": 1735.02,
    "totalOrders": 20,
    "avgRevenue": 10.515272727272727,
    "avgOrders": 0.12121212121212122
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 165,
    "totalRevenue": 1172.04,
    "totalOrders": 11,
    "avgRevenue": 7.103272727272727,
    "avgOrders": 0.06666666666666667
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 165,
    "totalRevenue": 2743.7100000000005,
    "totalOrders": 42,
    "avgRevenue": 16.628545454545456,
    "avgOrders": 0.2545454545454545
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 165,
    "totalRevenue": 1624.8899999999999,
    "totalOrders": 14,
    "avgRevenue": 9.84781818181818,
    "avgOrders": 0.08484848484848485
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 163,
    "totalRevenue": 2445.190000000001,
    "totalOrders": 11,
    "avgRevenue": 15.001165644171785,
    "avgOrders": 0.06748466257668712
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 163,
    "totalRevenue": 169.17000000000002,
    "totalOrders": 5,
    "avgRevenue": 1.0378527607361965,
    "avgOrders": 0.03067484662576687
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 158,
    "totalRevenue": 100.22999999999999,
    "totalOrders": 4,
    "avgRevenue": 0.6343670886075948,
    "avgOrders": 0.02531645569620253
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 165,
    "totalRevenue": 964.49,
    "totalOrders": 20,
    "avgRevenue": 5.845393939393939,
    "avgOrders": 0.12121212121212122
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 163,
    "totalRevenue": 546.62,
    "totalOrders": 4,
    "avgRevenue": 3.3534969325153376,
    "avgOrders": 0.024539877300613498
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 167,
    "totalRevenue": 484.09000000000003,
    "totalOrders": 9,
    "avgRevenue": 2.89874251497006,
    "avgOrders": 0.05389221556886228
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 161,
    "totalRevenue": 224.67,
    "totalOrders": 9,
    "avgRevenue": 1.3954658385093166,
    "avgOrders": 0.055900621118012424
  }
];
