// Auto-generated by scripts/updateData.js — last update: 2026-03-19
// CZ: hourly purchase behaviour (CZK), all-time

export interface HourlyPoint {
  dayOfWeek:    number;  // 0 = neděle … 6 = sobota
  hour:         number;  // 0–23
  dayCount:     number;  // počet dnů s daným dnem v týdnu v datasetu
  totalRevenue: number;  // celkové tržby bez DPH za (dow, hour)
  totalOrders:  number;  // celkový počet objednávek za (dow, hour)
  avgRevenue:   number;  // průměrné tržby bez DPH / den
  avgOrders:    number;  // průměrný počet objednávek / den
}

export const hourlyDataCZ: HourlyPoint[] = [
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 38,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 38,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 38,
    "totalRevenue": 845.54,
    "totalOrders": 1,
    "avgRevenue": 22.25,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 38,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 38,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 38,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 38,
    "totalRevenue": 2241.06,
    "totalOrders": 2,
    "avgRevenue": 58.98,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 38,
    "totalRevenue": 3149.99,
    "totalOrders": 4,
    "avgRevenue": 82.89,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 38,
    "totalRevenue": 2127.46,
    "totalOrders": 2,
    "avgRevenue": 55.99,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 38,
    "totalRevenue": 8444.81,
    "totalOrders": 7,
    "avgRevenue": 222.23,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 38,
    "totalRevenue": 5959.25,
    "totalOrders": 7,
    "avgRevenue": 156.82,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 38,
    "totalRevenue": 11927.4,
    "totalOrders": 10,
    "avgRevenue": 313.88,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 38,
    "totalRevenue": 13092.55,
    "totalOrders": 12,
    "avgRevenue": 344.54,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 38,
    "totalRevenue": 18110.14,
    "totalOrders": 14,
    "avgRevenue": 476.58,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 38,
    "totalRevenue": 32908.87,
    "totalOrders": 14,
    "avgRevenue": 866.02,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 38,
    "totalRevenue": 9158.8,
    "totalOrders": 7,
    "avgRevenue": 241.02,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 38,
    "totalRevenue": 6644.41,
    "totalOrders": 8,
    "avgRevenue": 174.85,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 38,
    "totalRevenue": 8573.43,
    "totalOrders": 9,
    "avgRevenue": 225.62,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 38,
    "totalRevenue": 23804.54,
    "totalOrders": 15,
    "avgRevenue": 626.44,
    "avgOrders": 0.39
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 38,
    "totalRevenue": 19580.59,
    "totalOrders": 16,
    "avgRevenue": 515.28,
    "avgOrders": 0.42
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 38,
    "totalRevenue": 17494.64,
    "totalOrders": 14,
    "avgRevenue": 460.39,
    "avgOrders": 0.37
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 38,
    "totalRevenue": 8530.18,
    "totalOrders": 7,
    "avgRevenue": 224.48,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 38,
    "totalRevenue": 12438.1,
    "totalOrders": 8,
    "avgRevenue": 327.32,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 38,
    "totalRevenue": 10749.47,
    "totalOrders": 9,
    "avgRevenue": 282.88,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 39,
    "totalRevenue": 4386.62,
    "totalOrders": 2,
    "avgRevenue": 112.48,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 39,
    "totalRevenue": 1690.91,
    "totalOrders": 1,
    "avgRevenue": 43.36,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 39,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 39,
    "totalRevenue": 2041.07,
    "totalOrders": 1,
    "avgRevenue": 52.34,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 39,
    "totalRevenue": 1069.64,
    "totalOrders": 1,
    "avgRevenue": 27.43,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 39,
    "totalRevenue": 1315.18,
    "totalOrders": 1,
    "avgRevenue": 33.72,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 39,
    "totalRevenue": 5482.14,
    "totalOrders": 3,
    "avgRevenue": 140.57,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 39,
    "totalRevenue": 2489.3,
    "totalOrders": 2,
    "avgRevenue": 63.83,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 39,
    "totalRevenue": 6725.4,
    "totalOrders": 4,
    "avgRevenue": 172.45,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 39,
    "totalRevenue": 3635.17,
    "totalOrders": 2,
    "avgRevenue": 93.21,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 39,
    "totalRevenue": 16674.98,
    "totalOrders": 13,
    "avgRevenue": 427.56,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 39,
    "totalRevenue": 9995.91,
    "totalOrders": 9,
    "avgRevenue": 256.31,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 39,
    "totalRevenue": 8946.96,
    "totalOrders": 7,
    "avgRevenue": 229.41,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 39,
    "totalRevenue": 9737.2,
    "totalOrders": 9,
    "avgRevenue": 249.67,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 39,
    "totalRevenue": 5900.38,
    "totalOrders": 6,
    "avgRevenue": 151.29,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 39,
    "totalRevenue": 12767.15,
    "totalOrders": 9,
    "avgRevenue": 327.36,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 39,
    "totalRevenue": 15085.4,
    "totalOrders": 13,
    "avgRevenue": 386.81,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 39,
    "totalRevenue": 11307.63,
    "totalOrders": 6,
    "avgRevenue": 289.94,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 39,
    "totalRevenue": 17994.21,
    "totalOrders": 15,
    "avgRevenue": 461.39,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 39,
    "totalRevenue": 29159.96,
    "totalOrders": 16,
    "avgRevenue": 747.69,
    "avgOrders": 0.41
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 39,
    "totalRevenue": 3075.02,
    "totalOrders": 4,
    "avgRevenue": 78.85,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 39,
    "totalRevenue": 32956.76,
    "totalOrders": 23,
    "avgRevenue": 845.05,
    "avgOrders": 0.59
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 39,
    "totalRevenue": 25498.54,
    "totalOrders": 17,
    "avgRevenue": 653.81,
    "avgOrders": 0.44
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 39,
    "totalRevenue": 4692,
    "totalOrders": 3,
    "avgRevenue": 120.31,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 38,
    "totalRevenue": 1742.49,
    "totalOrders": 2,
    "avgRevenue": 45.86,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 38,
    "totalRevenue": 3798.89,
    "totalOrders": 3,
    "avgRevenue": 99.97,
    "avgOrders": 0.08
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 38,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 38,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 38,
    "totalRevenue": 2886.61,
    "totalOrders": 2,
    "avgRevenue": 75.96,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 38,
    "totalRevenue": 1832.14,
    "totalOrders": 1,
    "avgRevenue": 48.21,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 38,
    "totalRevenue": 5427.91,
    "totalOrders": 5,
    "avgRevenue": 142.84,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 38,
    "totalRevenue": 5696.46,
    "totalOrders": 5,
    "avgRevenue": 149.91,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 38,
    "totalRevenue": 6653.86,
    "totalOrders": 6,
    "avgRevenue": 175.1,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 38,
    "totalRevenue": 14501.2,
    "totalOrders": 11,
    "avgRevenue": 381.61,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 38,
    "totalRevenue": 17608.9,
    "totalOrders": 12,
    "avgRevenue": 463.39,
    "avgOrders": 0.32
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 38,
    "totalRevenue": 25081.21,
    "totalOrders": 20,
    "avgRevenue": 660.03,
    "avgOrders": 0.53
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 38,
    "totalRevenue": 10209.95,
    "totalOrders": 9,
    "avgRevenue": 268.68,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 38,
    "totalRevenue": 12039.34,
    "totalOrders": 8,
    "avgRevenue": 316.82,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 38,
    "totalRevenue": 15095.17,
    "totalOrders": 10,
    "avgRevenue": 397.24,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 38,
    "totalRevenue": 13145.12,
    "totalOrders": 8,
    "avgRevenue": 345.92,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 38,
    "totalRevenue": 7109.88,
    "totalOrders": 4,
    "avgRevenue": 187.1,
    "avgOrders": 0.11
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 38,
    "totalRevenue": 12059.73,
    "totalOrders": 8,
    "avgRevenue": 317.36,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 38,
    "totalRevenue": 14647.4,
    "totalOrders": 9,
    "avgRevenue": 385.46,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 38,
    "totalRevenue": 22459.02,
    "totalOrders": 16,
    "avgRevenue": 591.03,
    "avgOrders": 0.42
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 38,
    "totalRevenue": 20631.28,
    "totalOrders": 18,
    "avgRevenue": 542.93,
    "avgOrders": 0.47
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 38,
    "totalRevenue": 18491.7,
    "totalOrders": 19,
    "avgRevenue": 486.62,
    "avgOrders": 0.5
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 38,
    "totalRevenue": 21708.1,
    "totalOrders": 19,
    "avgRevenue": 571.27,
    "avgOrders": 0.5
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 38,
    "totalRevenue": 13955.84,
    "totalOrders": 9,
    "avgRevenue": 367.26,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 39,
    "totalRevenue": 5352.25,
    "totalOrders": 5,
    "avgRevenue": 137.24,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 39,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 39,
    "totalRevenue": 1575.08,
    "totalOrders": 2,
    "avgRevenue": 40.39,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 39,
    "totalRevenue": 1105.36,
    "totalOrders": 1,
    "avgRevenue": 28.34,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 39,
    "totalRevenue": 1147.94,
    "totalOrders": 1,
    "avgRevenue": 29.43,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 39,
    "totalRevenue": 2121.42,
    "totalOrders": 1,
    "avgRevenue": 54.4,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 39,
    "totalRevenue": 2053.57,
    "totalOrders": 1,
    "avgRevenue": 52.66,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 39,
    "totalRevenue": 3994.35,
    "totalOrders": 4,
    "avgRevenue": 102.42,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 39,
    "totalRevenue": 9226.46,
    "totalOrders": 7,
    "avgRevenue": 236.58,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 39,
    "totalRevenue": 8201.33,
    "totalOrders": 7,
    "avgRevenue": 210.29,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 39,
    "totalRevenue": 11375.05,
    "totalOrders": 10,
    "avgRevenue": 291.67,
    "avgOrders": 0.26
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 39,
    "totalRevenue": 10254.62,
    "totalOrders": 7,
    "avgRevenue": 262.94,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 39,
    "totalRevenue": 10494.47,
    "totalOrders": 8,
    "avgRevenue": 269.09,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 39,
    "totalRevenue": 6129.27,
    "totalOrders": 6,
    "avgRevenue": 157.16,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 39,
    "totalRevenue": 9837.09,
    "totalOrders": 9,
    "avgRevenue": 252.23,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 39,
    "totalRevenue": 17808.4,
    "totalOrders": 8,
    "avgRevenue": 456.63,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 39,
    "totalRevenue": 11832.13,
    "totalOrders": 9,
    "avgRevenue": 303.39,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 39,
    "totalRevenue": 14330.14,
    "totalOrders": 9,
    "avgRevenue": 367.44,
    "avgOrders": 0.23
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 39,
    "totalRevenue": 6080.32,
    "totalOrders": 5,
    "avgRevenue": 155.91,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 39,
    "totalRevenue": 16892.34,
    "totalOrders": 11,
    "avgRevenue": 433.14,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 39,
    "totalRevenue": 20909.01,
    "totalOrders": 18,
    "avgRevenue": 536.13,
    "avgOrders": 0.46
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 39,
    "totalRevenue": 16043.88,
    "totalOrders": 13,
    "avgRevenue": 411.38,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 39,
    "totalRevenue": 13352.63,
    "totalOrders": 13,
    "avgRevenue": 342.38,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 39,
    "totalRevenue": 6011.94,
    "totalOrders": 6,
    "avgRevenue": 154.15,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 41,
    "totalRevenue": 6444.49,
    "totalOrders": 3,
    "avgRevenue": 157.18,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 41,
    "totalRevenue": 606.62,
    "totalOrders": 1,
    "avgRevenue": 14.8,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 41,
    "totalRevenue": 1907.14,
    "totalOrders": 2,
    "avgRevenue": 46.52,
    "avgOrders": 0.05
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 41,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 41,
    "totalRevenue": 1214.06,
    "totalOrders": 1,
    "avgRevenue": 29.61,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 41,
    "totalRevenue": 1884.82,
    "totalOrders": 1,
    "avgRevenue": 45.97,
    "avgOrders": 0.02
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 41,
    "totalRevenue": 5091.8,
    "totalOrders": 3,
    "avgRevenue": 124.19,
    "avgOrders": 0.07
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 41,
    "totalRevenue": 7080.02,
    "totalOrders": 5,
    "avgRevenue": 172.68,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 41,
    "totalRevenue": 7569.17,
    "totalOrders": 5,
    "avgRevenue": 184.61,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 41,
    "totalRevenue": 13635.8,
    "totalOrders": 9,
    "avgRevenue": 332.58,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 41,
    "totalRevenue": 13303.56,
    "totalOrders": 11,
    "avgRevenue": 324.48,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 41,
    "totalRevenue": 14331.08,
    "totalOrders": 12,
    "avgRevenue": 349.54,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 41,
    "totalRevenue": 5095.08,
    "totalOrders": 4,
    "avgRevenue": 124.27,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 41,
    "totalRevenue": 8232.98,
    "totalOrders": 5,
    "avgRevenue": 200.8,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 41,
    "totalRevenue": 16664.01,
    "totalOrders": 12,
    "avgRevenue": 406.44,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 41,
    "totalRevenue": 6937.75,
    "totalOrders": 7,
    "avgRevenue": 169.21,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 41,
    "totalRevenue": 8001.6,
    "totalOrders": 7,
    "avgRevenue": 195.16,
    "avgOrders": 0.17
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 41,
    "totalRevenue": 14306.48,
    "totalOrders": 12,
    "avgRevenue": 348.94,
    "avgOrders": 0.29
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 41,
    "totalRevenue": 10298.07,
    "totalOrders": 8,
    "avgRevenue": 251.17,
    "avgOrders": 0.2
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 41,
    "totalRevenue": 14174.05,
    "totalOrders": 11,
    "avgRevenue": 345.71,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 41,
    "totalRevenue": 11183.38,
    "totalOrders": 9,
    "avgRevenue": 272.77,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 41,
    "totalRevenue": 15205.13,
    "totalOrders": 14,
    "avgRevenue": 370.86,
    "avgOrders": 0.34
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 41,
    "totalRevenue": 3840.55,
    "totalOrders": 5,
    "avgRevenue": 93.67,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 41,
    "totalRevenue": 5049.89,
    "totalOrders": 4,
    "avgRevenue": 123.17,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 33,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 33,
    "totalRevenue": 2922.32,
    "totalOrders": 2,
    "avgRevenue": 88.56,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 33,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 33,
    "totalRevenue": 1080.37,
    "totalOrders": 1,
    "avgRevenue": 32.74,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 33,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 33,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 33,
    "totalRevenue": 5161.62,
    "totalOrders": 4,
    "avgRevenue": 156.41,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 33,
    "totalRevenue": 5351.76,
    "totalOrders": 4,
    "avgRevenue": 162.17,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 33,
    "totalRevenue": 7817.6,
    "totalOrders": 8,
    "avgRevenue": 236.9,
    "avgOrders": 0.24
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 33,
    "totalRevenue": 5928.43,
    "totalOrders": 6,
    "avgRevenue": 179.65,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 33,
    "totalRevenue": 11351.43,
    "totalOrders": 10,
    "avgRevenue": 343.98,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 33,
    "totalRevenue": 20843.55,
    "totalOrders": 11,
    "avgRevenue": 631.62,
    "avgOrders": 0.33
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 33,
    "totalRevenue": 7969.12,
    "totalOrders": 6,
    "avgRevenue": 241.49,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 33,
    "totalRevenue": 9058.3,
    "totalOrders": 9,
    "avgRevenue": 274.49,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 33,
    "totalRevenue": 6549.35,
    "totalOrders": 4,
    "avgRevenue": 198.47,
    "avgOrders": 0.12
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 33,
    "totalRevenue": 7533.59,
    "totalOrders": 7,
    "avgRevenue": 228.29,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 33,
    "totalRevenue": 5274.09,
    "totalOrders": 6,
    "avgRevenue": 159.82,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 33,
    "totalRevenue": 12635.5,
    "totalOrders": 9,
    "avgRevenue": 382.89,
    "avgOrders": 0.27
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 33,
    "totalRevenue": 9954.43,
    "totalOrders": 12,
    "avgRevenue": 301.65,
    "avgOrders": 0.36
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 33,
    "totalRevenue": 9694.31,
    "totalOrders": 7,
    "avgRevenue": 293.77,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 33,
    "totalRevenue": 6260.99,
    "totalOrders": 7,
    "avgRevenue": 189.73,
    "avgOrders": 0.21
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 33,
    "totalRevenue": 6635.72,
    "totalOrders": 5,
    "avgRevenue": 201.08,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 33,
    "totalRevenue": 7642.63,
    "totalOrders": 6,
    "avgRevenue": 231.59,
    "avgOrders": 0.18
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 33,
    "totalRevenue": 5331.44,
    "totalOrders": 5,
    "avgRevenue": 161.56,
    "avgOrders": 0.15
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 32,
    "totalRevenue": 3050.89,
    "totalOrders": 2,
    "avgRevenue": 95.34,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 32,
    "totalRevenue": 562.51,
    "totalOrders": 1,
    "avgRevenue": 17.58,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 32,
    "totalRevenue": 830.36,
    "totalOrders": 1,
    "avgRevenue": 25.95,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 32,
    "totalRevenue": 2084.82,
    "totalOrders": 1,
    "avgRevenue": 65.15,
    "avgOrders": 0.03
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 32,
    "totalRevenue": 0,
    "totalOrders": 0,
    "avgRevenue": 0,
    "avgOrders": 0
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 32,
    "totalRevenue": 2883.93,
    "totalOrders": 3,
    "avgRevenue": 90.12,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 32,
    "totalRevenue": 1837.49,
    "totalOrders": 2,
    "avgRevenue": 57.42,
    "avgOrders": 0.06
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 32,
    "totalRevenue": 10616.15,
    "totalOrders": 5,
    "avgRevenue": 331.75,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 32,
    "totalRevenue": 4280.26,
    "totalOrders": 4,
    "avgRevenue": 133.76,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 32,
    "totalRevenue": 16347.25,
    "totalOrders": 10,
    "avgRevenue": 510.85,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 32,
    "totalRevenue": 5839.29,
    "totalOrders": 4,
    "avgRevenue": 182.48,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 32,
    "totalRevenue": 4619.3,
    "totalOrders": 5,
    "avgRevenue": 144.35,
    "avgOrders": 0.16
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 32,
    "totalRevenue": 16466.64,
    "totalOrders": 12,
    "avgRevenue": 514.58,
    "avgOrders": 0.38
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 32,
    "totalRevenue": 10762.53,
    "totalOrders": 9,
    "avgRevenue": 336.33,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 32,
    "totalRevenue": 8169.65,
    "totalOrders": 7,
    "avgRevenue": 255.3,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 32,
    "totalRevenue": 12262.71,
    "totalOrders": 7,
    "avgRevenue": 383.21,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 32,
    "totalRevenue": 4167.33,
    "totalOrders": 3,
    "avgRevenue": 130.23,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 32,
    "totalRevenue": 11533.27,
    "totalOrders": 10,
    "avgRevenue": 360.41,
    "avgOrders": 0.31
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 32,
    "totalRevenue": 8763.27,
    "totalOrders": 7,
    "avgRevenue": 273.85,
    "avgOrders": 0.22
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 32,
    "totalRevenue": 3225.93,
    "totalOrders": 3,
    "avgRevenue": 100.81,
    "avgOrders": 0.09
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 32,
    "totalRevenue": 16328.91,
    "totalOrders": 13,
    "avgRevenue": 510.28,
    "avgOrders": 0.41
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 32,
    "totalRevenue": 13076.26,
    "totalOrders": 9,
    "avgRevenue": 408.63,
    "avgOrders": 0.28
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 32,
    "totalRevenue": 6122.34,
    "totalOrders": 4,
    "avgRevenue": 191.32,
    "avgOrders": 0.13
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 32,
    "totalRevenue": 2992.44,
    "totalOrders": 2,
    "avgRevenue": 93.51,
    "avgOrders": 0.06
  }
];
