// Auto-generated by scripts/fetchShoptetDataCZ.js — last update: 2026-04-18
// CZ: hourly purchase behaviour (CZK), all-time

export interface HourlyPoint {
  dayOfWeek:    number;
  hour:         number;
  dayCount:     number;
  totalRevenue: number;
  totalOrders:  number;
  avgRevenue:   number;
  avgOrders:    number;
}

export const hourlyDataCZ: HourlyPoint[] = [
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 80,
    "totalRevenue": 275319.49,
    "totalOrders": 163,
    "avgRevenue": 3441.493625,
    "avgOrders": 2.0375
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 89,
    "totalRevenue": 722715.6500000001,
    "totalOrders": 409,
    "avgRevenue": 8120.400561797755,
    "avgOrders": 4.595505617977528
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 95,
    "totalRevenue": 724674.3200000004,
    "totalOrders": 378,
    "avgRevenue": 7628.15073684211,
    "avgOrders": 3.9789473684210526
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 86,
    "totalRevenue": 770268.7700000003,
    "totalOrders": 378,
    "avgRevenue": 8956.613604651166,
    "avgOrders": 4.395348837209302
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 89,
    "totalRevenue": 796956.6400000001,
    "totalOrders": 424,
    "avgRevenue": 8954.568988764046,
    "avgOrders": 4.764044943820225
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 95,
    "totalRevenue": 1032032.1399999999,
    "totalOrders": 518,
    "avgRevenue": 10863.496210526315,
    "avgOrders": 5.4526315789473685
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 95,
    "totalRevenue": 963211.3899999998,
    "totalOrders": 528,
    "avgRevenue": 10139.067263157893,
    "avgOrders": 5.557894736842106
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 86,
    "totalRevenue": 919390.6599999998,
    "totalOrders": 516,
    "avgRevenue": 10690.58906976744,
    "avgOrders": 6
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 86,
    "totalRevenue": 697282.1299999993,
    "totalOrders": 347,
    "avgRevenue": 8107.9317441860385,
    "avgOrders": 4.034883720930233
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 90,
    "totalRevenue": 1152555.5100000002,
    "totalOrders": 586,
    "avgRevenue": 12806.172333333336,
    "avgOrders": 6.511111111111111
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 86,
    "totalRevenue": 556130.5000000001,
    "totalOrders": 329,
    "avgRevenue": 6466.633720930234,
    "avgOrders": 3.8255813953488373
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 80,
    "totalRevenue": 14629.81,
    "totalOrders": 13,
    "avgRevenue": 182.872625,
    "avgOrders": 0.1625
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 89,
    "totalRevenue": 292377.0600000001,
    "totalOrders": 105,
    "avgRevenue": 3285.1355056179787,
    "avgOrders": 1.1797752808988764
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 79,
    "totalRevenue": 474762.94999999995,
    "totalOrders": 273,
    "avgRevenue": 6009.657594936708,
    "avgOrders": 3.4556962025316458
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 89,
    "totalRevenue": 1201194.5299999996,
    "totalOrders": 558,
    "avgRevenue": 13496.567752808984,
    "avgOrders": 6.269662921348314
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 90,
    "totalRevenue": 610702.4000000004,
    "totalOrders": 352,
    "avgRevenue": 6785.582222222226,
    "avgOrders": 3.911111111111111
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 86,
    "totalRevenue": 827419.2399999999,
    "totalOrders": 443,
    "avgRevenue": 9621.15395348837,
    "avgOrders": 5.151162790697675
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 95,
    "totalRevenue": 880199.8299999994,
    "totalOrders": 397,
    "avgRevenue": 9265.261368421046,
    "avgOrders": 4.178947368421053
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 90,
    "totalRevenue": 1254972.2899999984,
    "totalOrders": 624,
    "avgRevenue": 13944.136555555539,
    "avgOrders": 6.933333333333334
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 86,
    "totalRevenue": 345337.38999999996,
    "totalOrders": 215,
    "avgRevenue": 4015.551046511627,
    "avgOrders": 2.5
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 86,
    "totalRevenue": 506037.40000000014,
    "totalOrders": 292,
    "avgRevenue": 5884.15581395349,
    "avgOrders": 3.395348837209302
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 86,
    "totalRevenue": 750570.2299999999,
    "totalOrders": 399,
    "avgRevenue": 8727.560813953487,
    "avgOrders": 4.6395348837209305
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 95,
    "totalRevenue": 993953.77,
    "totalOrders": 509,
    "avgRevenue": 10462.671263157896,
    "avgOrders": 5.3578947368421055
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 79,
    "totalRevenue": 660163.5700000006,
    "totalOrders": 350,
    "avgRevenue": 8356.500886075957,
    "avgOrders": 4.430379746835443
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 95,
    "totalRevenue": 56969.649999999994,
    "totalOrders": 26,
    "avgRevenue": 599.6805263157894,
    "avgOrders": 0.2736842105263158
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 95,
    "totalRevenue": 345820.2700000001,
    "totalOrders": 202,
    "avgRevenue": 3640.2133684210535,
    "avgOrders": 2.126315789473684
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 89,
    "totalRevenue": 1236697.71,
    "totalOrders": 597,
    "avgRevenue": 13895.47988764045,
    "avgOrders": 6.707865168539326
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 95,
    "totalRevenue": 36266.87,
    "totalOrders": 33,
    "avgRevenue": 381.75652631578953,
    "avgOrders": 0.3473684210526316
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 79,
    "totalRevenue": 423362.3100000003,
    "totalOrders": 233,
    "avgRevenue": 5359.016582278485,
    "avgOrders": 2.949367088607595
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 86,
    "totalRevenue": 835421.9199999998,
    "totalOrders": 380,
    "avgRevenue": 9714.20837209302,
    "avgOrders": 4.4186046511627906
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 90,
    "totalRevenue": 917705.3400000004,
    "totalOrders": 518,
    "avgRevenue": 10196.726000000004,
    "avgOrders": 5.7555555555555555
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 80,
    "totalRevenue": 360878.81000000023,
    "totalOrders": 176,
    "avgRevenue": 4510.985125000003,
    "avgOrders": 2.2
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 89,
    "totalRevenue": 1274787.5000000007,
    "totalOrders": 614,
    "avgRevenue": 14323.455056179782,
    "avgOrders": 6.898876404494382
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 89,
    "totalRevenue": 645000.6300000001,
    "totalOrders": 359,
    "avgRevenue": 7247.198089887642,
    "avgOrders": 4.033707865168539
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 90,
    "totalRevenue": 1088888.6099999999,
    "totalOrders": 535,
    "avgRevenue": 12098.762333333332,
    "avgOrders": 5.944444444444445
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 86,
    "totalRevenue": 768005.8799999994,
    "totalOrders": 372,
    "avgRevenue": 8930.300930232552,
    "avgOrders": 4.325581395348837
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 86,
    "totalRevenue": 517585.0699999998,
    "totalOrders": 311,
    "avgRevenue": 6018.431046511625,
    "avgOrders": 3.616279069767442
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 89,
    "totalRevenue": 85756.60999999999,
    "totalOrders": 46,
    "avgRevenue": 963.557415730337,
    "avgOrders": 0.5168539325842697
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 90,
    "totalRevenue": 647769.8299999995,
    "totalOrders": 352,
    "avgRevenue": 7197.44255555555,
    "avgOrders": 3.911111111111111
  },
  {
    "dayOfWeek": 3,
    "hour": 4,
    "dayCount": 86,
    "totalRevenue": 37255.909999999996,
    "totalOrders": 21,
    "avgRevenue": 433.20825581395343,
    "avgOrders": 0.2441860465116279
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 86,
    "totalRevenue": 784917.8500000003,
    "totalOrders": 403,
    "avgRevenue": 9126.95174418605,
    "avgOrders": 4.686046511627907
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 95,
    "totalRevenue": 513267.2299999997,
    "totalOrders": 243,
    "avgRevenue": 5402.812947368418,
    "avgOrders": 2.557894736842105
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 95,
    "totalRevenue": 923105.8600000001,
    "totalOrders": 462,
    "avgRevenue": 9716.903789473685,
    "avgOrders": 4.863157894736842
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 86,
    "totalRevenue": 375780.0599999998,
    "totalOrders": 209,
    "avgRevenue": 4369.5355813953465,
    "avgOrders": 2.4302325581395348
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 80,
    "totalRevenue": 301345.1800000002,
    "totalOrders": 193,
    "avgRevenue": 3766.8147500000027,
    "avgOrders": 2.4125
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 90,
    "totalRevenue": 804998.15,
    "totalOrders": 417,
    "avgRevenue": 8944.423888888889,
    "avgOrders": 4.633333333333334
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 86,
    "totalRevenue": 1074072.5599999996,
    "totalOrders": 525,
    "avgRevenue": 12489.215813953484,
    "avgOrders": 6.104651162790698
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 80,
    "totalRevenue": 305516.65,
    "totalOrders": 196,
    "avgRevenue": 3818.958125,
    "avgOrders": 2.45
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 89,
    "totalRevenue": 638253.21,
    "totalOrders": 377,
    "avgRevenue": 7171.384382022471,
    "avgOrders": 4.235955056179775
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 95,
    "totalRevenue": 491853.9700000003,
    "totalOrders": 241,
    "avgRevenue": 5177.410210526319,
    "avgOrders": 2.536842105263158
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 89,
    "totalRevenue": 625162.6999999997,
    "totalOrders": 348,
    "avgRevenue": 7024.2999999999965,
    "avgOrders": 3.9101123595505616
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 90,
    "totalRevenue": 1305636.4799999997,
    "totalOrders": 681,
    "avgRevenue": 14507.071999999996,
    "avgOrders": 7.566666666666666
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 89,
    "totalRevenue": 929407.7599999998,
    "totalOrders": 530,
    "avgRevenue": 10442.783820224717,
    "avgOrders": 5.955056179775281
  },
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 89,
    "totalRevenue": 722397.3299999995,
    "totalOrders": 403,
    "avgRevenue": 8116.823932584264,
    "avgOrders": 4.52808988764045
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 90,
    "totalRevenue": 725583.4299999994,
    "totalOrders": 396,
    "avgRevenue": 8062.038111111104,
    "avgOrders": 4.4
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 80,
    "totalRevenue": 321048.5399999999,
    "totalOrders": 158,
    "avgRevenue": 4013.106749999999,
    "avgOrders": 1.975
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 89,
    "totalRevenue": 1150508.4800000011,
    "totalOrders": 607,
    "avgRevenue": 12927.061573033721,
    "avgOrders": 6.820224719101123
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 95,
    "totalRevenue": 451805.4400000001,
    "totalOrders": 262,
    "avgRevenue": 4755.846736842106,
    "avgOrders": 2.7578947368421054
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 89,
    "totalRevenue": 616639.2500000003,
    "totalOrders": 329,
    "avgRevenue": 6928.530898876408,
    "avgOrders": 3.696629213483146
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 86,
    "totalRevenue": 875768.79,
    "totalOrders": 429,
    "avgRevenue": 10183.358023255814,
    "avgOrders": 4.988372093023256
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 86,
    "totalRevenue": 280356.5400000001,
    "totalOrders": 150,
    "avgRevenue": 3259.9597674418615,
    "avgOrders": 1.744186046511628
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 90,
    "totalRevenue": 603859.3999999998,
    "totalOrders": 325,
    "avgRevenue": 6709.548888888887,
    "avgOrders": 3.611111111111111
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 90,
    "totalRevenue": 664065.7899999998,
    "totalOrders": 381,
    "avgRevenue": 7378.508777777775,
    "avgOrders": 4.233333333333333
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 80,
    "totalRevenue": 255871.74999999994,
    "totalOrders": 167,
    "avgRevenue": 3198.3968749999995,
    "avgOrders": 2.0875
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 95,
    "totalRevenue": 660882.5400000004,
    "totalOrders": 351,
    "avgRevenue": 6956.6583157894775,
    "avgOrders": 3.694736842105263
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 89,
    "totalRevenue": 658868.4900000002,
    "totalOrders": 355,
    "avgRevenue": 7403.016741573037,
    "avgOrders": 3.9887640449438204
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 86,
    "totalRevenue": 706421.4299999996,
    "totalOrders": 352,
    "avgRevenue": 8214.2026744186,
    "avgOrders": 4.093023255813954
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 86,
    "totalRevenue": 1011846.2000000001,
    "totalOrders": 503,
    "avgRevenue": 11765.653488372094,
    "avgOrders": 5.848837209302325
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 95,
    "totalRevenue": 91102.93999999999,
    "totalOrders": 57,
    "avgRevenue": 958.9783157894735,
    "avgOrders": 0.6
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 79,
    "totalRevenue": 825665.8699999994,
    "totalOrders": 415,
    "avgRevenue": 10451.466708860751,
    "avgOrders": 5.253164556962025
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 80,
    "totalRevenue": 316892.6800000001,
    "totalOrders": 182,
    "avgRevenue": 3961.1585000000014,
    "avgOrders": 2.275
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 79,
    "totalRevenue": 718653.1900000009,
    "totalOrders": 357,
    "avgRevenue": 9096.875822784821,
    "avgOrders": 4.518987341772152
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 79,
    "totalRevenue": 398433.95999999985,
    "totalOrders": 224,
    "avgRevenue": 5043.467848101264,
    "avgOrders": 2.8354430379746836
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 90,
    "totalRevenue": 338592.45,
    "totalOrders": 203,
    "avgRevenue": 3762.1383333333333,
    "avgOrders": 2.2555555555555555
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 80,
    "totalRevenue": 30947.09,
    "totalOrders": 28,
    "avgRevenue": 386.838625,
    "avgOrders": 0.35
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 90,
    "totalRevenue": 723978.1499999996,
    "totalOrders": 373,
    "avgRevenue": 8044.201666666661,
    "avgOrders": 4.144444444444445
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 86,
    "totalRevenue": 533563.5500000002,
    "totalOrders": 329,
    "avgRevenue": 6204.227325581397,
    "avgOrders": 3.8255813953488373
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 79,
    "totalRevenue": 546136.7499999997,
    "totalOrders": 250,
    "avgRevenue": 6913.123417721515,
    "avgOrders": 3.1645569620253164
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 95,
    "totalRevenue": 966305.2499999998,
    "totalOrders": 489,
    "avgRevenue": 10171.634210526314,
    "avgOrders": 5.147368421052631
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 86,
    "totalRevenue": 394442.7500000003,
    "totalOrders": 199,
    "avgRevenue": 4586.543604651166,
    "avgOrders": 2.313953488372093
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 79,
    "totalRevenue": 826219.8500000003,
    "totalOrders": 416,
    "avgRevenue": 10458.479113924055,
    "avgOrders": 5.265822784810126
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 90,
    "totalRevenue": 1160303.3299999991,
    "totalOrders": 619,
    "avgRevenue": 12892.259222222212,
    "avgOrders": 6.877777777777778
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 86,
    "totalRevenue": 873014.59,
    "totalOrders": 506,
    "avgRevenue": 10151.332441860464,
    "avgOrders": 5.883720930232558
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 86,
    "totalRevenue": 514996.7199999999,
    "totalOrders": 289,
    "avgRevenue": 5988.333953488371,
    "avgOrders": 3.36046511627907
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 86,
    "totalRevenue": 509392.51999999984,
    "totalOrders": 282,
    "avgRevenue": 5923.1688372093,
    "avgOrders": 3.2790697674418605
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 95,
    "totalRevenue": 128414.67000000004,
    "totalOrders": 89,
    "avgRevenue": 1351.733368421053,
    "avgOrders": 0.9368421052631579
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 95,
    "totalRevenue": 494410.7500000001,
    "totalOrders": 265,
    "avgRevenue": 5204.323684210528,
    "avgOrders": 2.789473684210526
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 86,
    "totalRevenue": 581132.94,
    "totalOrders": 277,
    "avgRevenue": 6757.35976744186,
    "avgOrders": 3.2209302325581395
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 80,
    "totalRevenue": 236063.57000000004,
    "totalOrders": 148,
    "avgRevenue": 2950.7946250000005,
    "avgOrders": 1.85
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 79,
    "totalRevenue": 513077.99,
    "totalOrders": 287,
    "avgRevenue": 6494.658101265823,
    "avgOrders": 3.632911392405063
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 89,
    "totalRevenue": 98987.43999999996,
    "totalOrders": 30,
    "avgRevenue": 1112.2184269662916,
    "avgOrders": 0.33707865168539325
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 95,
    "totalRevenue": 419661.8999999997,
    "totalOrders": 215,
    "avgRevenue": 4417.493684210523,
    "avgOrders": 2.263157894736842
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 95,
    "totalRevenue": 509655.35,
    "totalOrders": 244,
    "avgRevenue": 5364.793157894736,
    "avgOrders": 2.568421052631579
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 86,
    "totalRevenue": 429550.57000000007,
    "totalOrders": 224,
    "avgRevenue": 4994.774069767443,
    "avgOrders": 2.604651162790698
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 86,
    "totalRevenue": 373235.70000000007,
    "totalOrders": 189,
    "avgRevenue": 4339.950000000001,
    "avgOrders": 2.197674418604651
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 86,
    "totalRevenue": 465457.22999999975,
    "totalOrders": 198,
    "avgRevenue": 5412.2933720930205,
    "avgOrders": 2.302325581395349
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 86,
    "totalRevenue": 305488.6600000001,
    "totalOrders": 157,
    "avgRevenue": 3552.1937209302337,
    "avgOrders": 1.8255813953488371
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 86,
    "totalRevenue": 192678.99999999988,
    "totalOrders": 106,
    "avgRevenue": 2240.4534883720917,
    "avgOrders": 1.2325581395348837
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 80,
    "totalRevenue": 127110.82000000004,
    "totalOrders": 57,
    "avgRevenue": 1588.8852500000005,
    "avgOrders": 0.7125
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 80,
    "totalRevenue": 7550.72,
    "totalOrders": 10,
    "avgRevenue": 94.384,
    "avgOrders": 0.125
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 80,
    "totalRevenue": 35784.13,
    "totalOrders": 29,
    "avgRevenue": 447.30162499999994,
    "avgOrders": 0.3625
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 80,
    "totalRevenue": 161781.44999999995,
    "totalOrders": 118,
    "avgRevenue": 2022.2681249999994,
    "avgOrders": 1.475
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 80,
    "totalRevenue": 245814.25,
    "totalOrders": 149,
    "avgRevenue": 3072.678125,
    "avgOrders": 1.8625
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 80,
    "totalRevenue": 266862.13000000006,
    "totalOrders": 160,
    "avgRevenue": 3335.776625000001,
    "avgOrders": 2
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 80,
    "totalRevenue": 384496.60000000003,
    "totalOrders": 182,
    "avgRevenue": 4806.2075,
    "avgOrders": 2.275
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 80,
    "totalRevenue": 300515.5,
    "totalOrders": 169,
    "avgRevenue": 3756.44375,
    "avgOrders": 2.1125
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 80,
    "totalRevenue": 345460.26999999996,
    "totalOrders": 183,
    "avgRevenue": 4318.253374999999,
    "avgOrders": 2.2875
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 80,
    "totalRevenue": 201510.46999999994,
    "totalOrders": 127,
    "avgRevenue": 2518.8808749999994,
    "avgOrders": 1.5875
  },
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 79,
    "totalRevenue": 104321.19999999998,
    "totalOrders": 66,
    "avgRevenue": 1320.5215189873416,
    "avgOrders": 0.8354430379746836
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 79,
    "totalRevenue": 66835.45000000001,
    "totalOrders": 35,
    "avgRevenue": 846.0183544303799,
    "avgOrders": 0.4430379746835443
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 79,
    "totalRevenue": 359438.81,
    "totalOrders": 209,
    "avgRevenue": 4549.85835443038,
    "avgOrders": 2.6455696202531644
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 79,
    "totalRevenue": 430686.7099999999,
    "totalOrders": 236,
    "avgRevenue": 5451.730506329112,
    "avgOrders": 2.9873417721518987
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 79,
    "totalRevenue": 465247.8499999999,
    "totalOrders": 249,
    "avgRevenue": 5889.213291139239,
    "avgOrders": 3.151898734177215
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 79,
    "totalRevenue": 398503.32999999984,
    "totalOrders": 274,
    "avgRevenue": 5044.345949367086,
    "avgOrders": 3.4683544303797467
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 90,
    "totalRevenue": 212646.90999999995,
    "totalOrders": 102,
    "avgRevenue": 2362.743444444444,
    "avgOrders": 1.1333333333333333
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 90,
    "totalRevenue": 155527.57,
    "totalOrders": 96,
    "avgRevenue": 1728.0841111111113,
    "avgOrders": 1.0666666666666667
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 90,
    "totalRevenue": 1066606.129999999,
    "totalOrders": 553,
    "avgRevenue": 11851.17922222221,
    "avgOrders": 6.144444444444445
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 90,
    "totalRevenue": 603013.4699999997,
    "totalOrders": 324,
    "avgRevenue": 6700.1496666666635,
    "avgOrders": 3.6
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 90,
    "totalRevenue": 412092.35000000003,
    "totalOrders": 200,
    "avgRevenue": 4578.80388888889,
    "avgOrders": 2.2222222222222223
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 89,
    "totalRevenue": 24841,
    "totalOrders": 20,
    "avgRevenue": 279.1123595505618,
    "avgOrders": 0.2247191011235955
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 89,
    "totalRevenue": 126515.73000000001,
    "totalOrders": 95,
    "avgRevenue": 1421.5250561797754,
    "avgOrders": 1.0674157303370786
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 89,
    "totalRevenue": 401284.1000000002,
    "totalOrders": 220,
    "avgRevenue": 4508.8101123595525,
    "avgOrders": 2.4719101123595504
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 89,
    "totalRevenue": 881436.6399999997,
    "totalOrders": 485,
    "avgRevenue": 9903.782471910108,
    "avgOrders": 5.449438202247191
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 89,
    "totalRevenue": 559630.7300000003,
    "totalOrders": 327,
    "avgRevenue": 6287.985730337083,
    "avgOrders": 3.6741573033707864
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 89,
    "totalRevenue": 442813.3900000001,
    "totalOrders": 189,
    "avgRevenue": 4975.431348314608,
    "avgOrders": 2.1235955056179776
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 86,
    "totalRevenue": 94193.09,
    "totalOrders": 37,
    "avgRevenue": 1095.268488372093,
    "avgOrders": 0.43023255813953487
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 86,
    "totalRevenue": 1061645.6000000003,
    "totalOrders": 554,
    "avgRevenue": 12344.716279069771,
    "avgOrders": 6.441860465116279
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 86,
    "totalRevenue": 1219648.1599999985,
    "totalOrders": 648,
    "avgRevenue": 14181.955348837191,
    "avgOrders": 7.534883720930233
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 86,
    "totalRevenue": 667038.7299999995,
    "totalOrders": 360,
    "avgRevenue": 7756.264302325576,
    "avgOrders": 4.186046511627907
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 95,
    "totalRevenue": 54620.46,
    "totalOrders": 21,
    "avgRevenue": 574.9522105263158,
    "avgOrders": 0.22105263157894736
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 95,
    "totalRevenue": 264521.76000000007,
    "totalOrders": 140,
    "avgRevenue": 2784.4395789473692,
    "avgOrders": 1.4736842105263157
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 86,
    "totalRevenue": 167218.58,
    "totalOrders": 70,
    "avgRevenue": 1944.4020930232557,
    "avgOrders": 0.813953488372093
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 86,
    "totalRevenue": 54914.729999999996,
    "totalOrders": 39,
    "avgRevenue": 638.5433720930232,
    "avgOrders": 0.45348837209302323
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 86,
    "totalRevenue": 221918.72999999998,
    "totalOrders": 135,
    "avgRevenue": 2580.4503488372093,
    "avgOrders": 1.569767441860465
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 80,
    "totalRevenue": 144516.64999999997,
    "totalOrders": 74,
    "avgRevenue": 1806.4581249999997,
    "avgOrders": 0.925
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 80,
    "totalRevenue": 311048.6300000002,
    "totalOrders": 186,
    "avgRevenue": 3888.1078750000024,
    "avgOrders": 2.325
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 79,
    "totalRevenue": 295498.65,
    "totalOrders": 167,
    "avgRevenue": 3740.489240506329,
    "avgOrders": 2.1139240506329116
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 79,
    "totalRevenue": 542427.2199999995,
    "totalOrders": 265,
    "avgRevenue": 6866.167341772146,
    "avgOrders": 3.3544303797468356
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 90,
    "totalRevenue": 105366.99999999999,
    "totalOrders": 64,
    "avgRevenue": 1170.7444444444443,
    "avgOrders": 0.7111111111111111
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 86,
    "totalRevenue": 170358.84,
    "totalOrders": 99,
    "avgRevenue": 1980.9167441860466,
    "avgOrders": 1.1511627906976745
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 86,
    "totalRevenue": 150374.26000000007,
    "totalOrders": 98,
    "avgRevenue": 1748.537906976745,
    "avgOrders": 1.1395348837209303
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 86,
    "totalRevenue": 288601.90000000014,
    "totalOrders": 200,
    "avgRevenue": 3355.8360465116293,
    "avgOrders": 2.3255813953488373
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 95,
    "totalRevenue": 121986.7,
    "totalOrders": 72,
    "avgRevenue": 1284.0705263157895,
    "avgOrders": 0.7578947368421053
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 95,
    "totalRevenue": 277148.0500000001,
    "totalOrders": 173,
    "avgRevenue": 2917.347894736843,
    "avgOrders": 1.8210526315789475
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 80,
    "totalRevenue": 21192.63,
    "totalOrders": 17,
    "avgRevenue": 264.907875,
    "avgOrders": 0.2125
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 79,
    "totalRevenue": 34515.22,
    "totalOrders": 12,
    "avgRevenue": 436.9015189873418,
    "avgOrders": 0.1518987341772152
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 90,
    "totalRevenue": 44862.350000000006,
    "totalOrders": 31,
    "avgRevenue": 498.4705555555556,
    "avgOrders": 0.34444444444444444
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 90,
    "totalRevenue": 29643.659999999996,
    "totalOrders": 20,
    "avgRevenue": 329.37399999999997,
    "avgOrders": 0.2222222222222222
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 90,
    "totalRevenue": 43465.08999999999,
    "totalOrders": 27,
    "avgRevenue": 482.9454444444443,
    "avgOrders": 0.3
  },
  {
    "dayOfWeek": 2,
    "hour": 4,
    "dayCount": 89,
    "totalRevenue": 15879.999999999998,
    "totalOrders": 13,
    "avgRevenue": 178.4269662921348,
    "avgOrders": 0.14606741573033707
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 86,
    "totalRevenue": 37669.1,
    "totalOrders": 20,
    "avgRevenue": 438.0127906976744,
    "avgOrders": 0.23255813953488372
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 86,
    "totalRevenue": 19963.66,
    "totalOrders": 15,
    "avgRevenue": 232.13558139534882,
    "avgOrders": 0.1744186046511628
  },
  {
    "dayOfWeek": 0,
    "hour": 3,
    "dayCount": 79,
    "totalRevenue": 5523.14,
    "totalOrders": 8,
    "avgRevenue": 69.91316455696203,
    "avgOrders": 0.10126582278481013
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 79,
    "totalRevenue": 33058.380000000005,
    "totalOrders": 23,
    "avgRevenue": 418.46050632911397,
    "avgOrders": 0.2911392405063291
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 79,
    "totalRevenue": 146465.77,
    "totalOrders": 70,
    "avgRevenue": 1853.9970886075948,
    "avgOrders": 0.8860759493670886
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 79,
    "totalRevenue": 244382.9500000002,
    "totalOrders": 118,
    "avgRevenue": 3093.4550632911414,
    "avgOrders": 1.4936708860759493
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 86,
    "totalRevenue": 52245.46,
    "totalOrders": 37,
    "avgRevenue": 607.5053488372093,
    "avgOrders": 0.43023255813953487
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 95,
    "totalRevenue": 24202.2,
    "totalOrders": 17,
    "avgRevenue": 254.76000000000002,
    "avgOrders": 0.17894736842105263
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 86,
    "totalRevenue": 78976.77,
    "totalOrders": 46,
    "avgRevenue": 918.334534883721,
    "avgOrders": 0.5348837209302325
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 80,
    "totalRevenue": 15709.69,
    "totalOrders": 8,
    "avgRevenue": 196.371125,
    "avgOrders": 0.1
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 89,
    "totalRevenue": 32325.17,
    "totalOrders": 14,
    "avgRevenue": 363.2041573033708,
    "avgOrders": 0.15730337078651685
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 86,
    "totalRevenue": 62082.469999999994,
    "totalOrders": 29,
    "avgRevenue": 721.8891860465116,
    "avgOrders": 0.3372093023255814
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 86,
    "totalRevenue": 16344.21,
    "totalOrders": 15,
    "avgRevenue": 190.0489534883721,
    "avgOrders": 0.1744186046511628
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 90,
    "totalRevenue": 25550.78,
    "totalOrders": 15,
    "avgRevenue": 283.8975555555555,
    "avgOrders": 0.16666666666666666
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 86,
    "totalRevenue": 7484.330000000001,
    "totalOrders": 6,
    "avgRevenue": 87.02709302325583,
    "avgOrders": 0.06976744186046512
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 79,
    "totalRevenue": 8047.929999999999,
    "totalOrders": 11,
    "avgRevenue": 101.87253164556961,
    "avgOrders": 0.13924050632911392
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 86,
    "totalRevenue": 29203.75,
    "totalOrders": 21,
    "avgRevenue": 339.57848837209303,
    "avgOrders": 0.2441860465116279
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 79,
    "totalRevenue": 20459.18,
    "totalOrders": 9,
    "avgRevenue": 258.9769620253165,
    "avgOrders": 0.11392405063291139
  }
];
