// Auto-generated by scripts/fetchShoptetData.js — last update: 2026-04-17
// NL: hourly purchase behaviour (EUR), all-time

export interface HourlyPoint {
  dayOfWeek:    number;  // 0 = Sunday … 6 = Saturday
  hour:         number;  // 0–23
  dayCount:     number;
  totalRevenue: number;
  totalOrders:  number;
  avgRevenue:   number;
  avgOrders:    number;
}

export const hourlyDataNL: HourlyPoint[] = [
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 1,
    "totalRevenue": 579.38,
    "totalOrders": 1,
    "avgRevenue": 579.38,
    "avgOrders": 1
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 1,
    "totalRevenue": 28.96,
    "totalOrders": 1,
    "avgRevenue": 28.96,
    "avgOrders": 1
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 1,
    "totalRevenue": 98.38999999999999,
    "totalOrders": 1,
    "avgRevenue": 98.38999999999999,
    "avgOrders": 1
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 1,
    "totalRevenue": 49.2,
    "totalOrders": 1,
    "avgRevenue": 49.2,
    "avgOrders": 1
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 1,
    "totalRevenue": 68.31,
    "totalOrders": 1,
    "avgRevenue": 68.31,
    "avgOrders": 1
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 1,
    "totalRevenue": 26.02,
    "totalOrders": 1,
    "avgRevenue": 26.02,
    "avgOrders": 1
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 1,
    "totalRevenue": 28.38,
    "totalOrders": 1,
    "avgRevenue": 28.38,
    "avgOrders": 1
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 1,
    "totalRevenue": 17.11,
    "totalOrders": 1,
    "avgRevenue": 17.11,
    "avgOrders": 1
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 1,
    "totalRevenue": 0,
    "totalOrders": 1,
    "avgRevenue": 0,
    "avgOrders": 1
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 1,
    "totalRevenue": 42.95,
    "totalOrders": 1,
    "avgRevenue": 42.95,
    "avgOrders": 1
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 1,
    "totalRevenue": 54.949999999999996,
    "totalOrders": 1,
    "avgRevenue": 54.949999999999996,
    "avgOrders": 1
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 1,
    "totalRevenue": 11,
    "totalOrders": 1,
    "avgRevenue": 11,
    "avgOrders": 1
  }
];
