// Auto-generated by scripts/fetchShoptetData.js — last update: 2026-04-16
// AT: hourly purchase behaviour (EUR), all-time

export interface HourlyPoint {
  dayOfWeek:    number;  // 0 = Sunday … 6 = Saturday
  hour:         number;  // 0–23
  dayCount:     number;
  totalRevenue: number;
  totalOrders:  number;
  avgRevenue:   number;
  avgOrders:    number;
}

export const hourlyDataAT: HourlyPoint[] = [
  {
    "dayOfWeek": 2,
    "hour": 21,
    "dayCount": 121,
    "totalRevenue": 4369.4,
    "totalOrders": 44,
    "avgRevenue": 36.11074380165289,
    "avgOrders": 0.36363636363636365
  },
  {
    "dayOfWeek": 2,
    "hour": 19,
    "dayCount": 121,
    "totalRevenue": 2786.51,
    "totalOrders": 28,
    "avgRevenue": 23.02900826446281,
    "avgOrders": 0.23140495867768596
  },
  {
    "dayOfWeek": 3,
    "hour": 3,
    "dayCount": 118,
    "totalRevenue": 566.6600000000001,
    "totalOrders": 7,
    "avgRevenue": 4.802203389830509,
    "avgOrders": 0.059322033898305086
  },
  {
    "dayOfWeek": 4,
    "hour": 16,
    "dayCount": 114,
    "totalRevenue": 2750.01,
    "totalOrders": 28,
    "avgRevenue": 24.122894736842106,
    "avgOrders": 0.24561403508771928
  },
  {
    "dayOfWeek": 6,
    "hour": 11,
    "dayCount": 113,
    "totalRevenue": 3555.5999999999995,
    "totalOrders": 26,
    "avgRevenue": 31.465486725663713,
    "avgOrders": 0.23008849557522124
  },
  {
    "dayOfWeek": 1,
    "hour": 7,
    "dayCount": 117,
    "totalRevenue": 1846.3700000000001,
    "totalOrders": 21,
    "avgRevenue": 15.780940170940172,
    "avgOrders": 0.1794871794871795
  },
  {
    "dayOfWeek": 1,
    "hour": 21,
    "dayCount": 117,
    "totalRevenue": 3061.0900000000015,
    "totalOrders": 39,
    "avgRevenue": 26.163162393162406,
    "avgOrders": 0.3333333333333333
  },
  {
    "dayOfWeek": 2,
    "hour": 14,
    "dayCount": 121,
    "totalRevenue": 3433.340000000001,
    "totalOrders": 34,
    "avgRevenue": 28.37471074380166,
    "avgOrders": 0.2809917355371901
  },
  {
    "dayOfWeek": 2,
    "hour": 20,
    "dayCount": 121,
    "totalRevenue": 4234.3200000000015,
    "totalOrders": 39,
    "avgRevenue": 34.99438016528927,
    "avgOrders": 0.32231404958677684
  },
  {
    "dayOfWeek": 3,
    "hour": 13,
    "dayCount": 118,
    "totalRevenue": 3790.03,
    "totalOrders": 39,
    "avgRevenue": 32.11889830508475,
    "avgOrders": 0.3305084745762712
  },
  {
    "dayOfWeek": 3,
    "hour": 15,
    "dayCount": 118,
    "totalRevenue": 1900.7500000000002,
    "totalOrders": 29,
    "avgRevenue": 16.10805084745763,
    "avgOrders": 0.2457627118644068
  },
  {
    "dayOfWeek": 3,
    "hour": 20,
    "dayCount": 118,
    "totalRevenue": 2860.0300000000007,
    "totalOrders": 34,
    "avgRevenue": 24.23754237288136,
    "avgOrders": 0.288135593220339
  },
  {
    "dayOfWeek": 3,
    "hour": 21,
    "dayCount": 118,
    "totalRevenue": 2532.17,
    "totalOrders": 32,
    "avgRevenue": 21.45906779661017,
    "avgOrders": 0.2711864406779661
  },
  {
    "dayOfWeek": 6,
    "hour": 14,
    "dayCount": 113,
    "totalRevenue": 3073.2,
    "totalOrders": 27,
    "avgRevenue": 27.19646017699115,
    "avgOrders": 0.23893805309734514
  },
  {
    "dayOfWeek": 6,
    "hour": 15,
    "dayCount": 113,
    "totalRevenue": 2090.7999999999997,
    "totalOrders": 20,
    "avgRevenue": 18.502654867256634,
    "avgOrders": 0.17699115044247787
  },
  {
    "dayOfWeek": 6,
    "hour": 23,
    "dayCount": 113,
    "totalRevenue": 434.74000000000007,
    "totalOrders": 13,
    "avgRevenue": 3.847256637168142,
    "avgOrders": 0.11504424778761062
  },
  {
    "dayOfWeek": 0,
    "hour": 17,
    "dayCount": 113,
    "totalRevenue": 3779.559999999999,
    "totalOrders": 35,
    "avgRevenue": 33.44743362831858,
    "avgOrders": 0.30973451327433627
  },
  {
    "dayOfWeek": 0,
    "hour": 18,
    "dayCount": 113,
    "totalRevenue": 2972.25,
    "totalOrders": 31,
    "avgRevenue": 26.303097345132745,
    "avgOrders": 0.2743362831858407
  },
  {
    "dayOfWeek": 2,
    "hour": 11,
    "dayCount": 121,
    "totalRevenue": 4466.85,
    "totalOrders": 33,
    "avgRevenue": 36.916115702479345,
    "avgOrders": 0.2727272727272727
  },
  {
    "dayOfWeek": 3,
    "hour": 9,
    "dayCount": 118,
    "totalRevenue": 4035.9300000000003,
    "totalOrders": 29,
    "avgRevenue": 34.20279661016949,
    "avgOrders": 0.2457627118644068
  },
  {
    "dayOfWeek": 3,
    "hour": 12,
    "dayCount": 118,
    "totalRevenue": 2662.3800000000006,
    "totalOrders": 32,
    "avgRevenue": 22.56254237288136,
    "avgOrders": 0.2711864406779661
  },
  {
    "dayOfWeek": 4,
    "hour": 14,
    "dayCount": 114,
    "totalRevenue": 4079.0300000000016,
    "totalOrders": 36,
    "avgRevenue": 35.780964912280716,
    "avgOrders": 0.3157894736842105
  },
  {
    "dayOfWeek": 0,
    "hour": 2,
    "dayCount": 113,
    "totalRevenue": 1444.3899999999999,
    "totalOrders": 7,
    "avgRevenue": 12.782212389380529,
    "avgOrders": 0.061946902654867256
  },
  {
    "dayOfWeek": 0,
    "hour": 13,
    "dayCount": 113,
    "totalRevenue": 2004.2700000000002,
    "totalOrders": 28,
    "avgRevenue": 17.736902654867258,
    "avgOrders": 0.24778761061946902
  },
  {
    "dayOfWeek": 1,
    "hour": 9,
    "dayCount": 117,
    "totalRevenue": 3636.0600000000004,
    "totalOrders": 23,
    "avgRevenue": 31.0774358974359,
    "avgOrders": 0.19658119658119658
  },
  {
    "dayOfWeek": 1,
    "hour": 20,
    "dayCount": 117,
    "totalRevenue": 4039.61,
    "totalOrders": 30,
    "avgRevenue": 34.5265811965812,
    "avgOrders": 0.2564102564102564
  },
  {
    "dayOfWeek": 2,
    "hour": 22,
    "dayCount": 121,
    "totalRevenue": 2563.8499999999995,
    "totalOrders": 31,
    "avgRevenue": 21.188842975206608,
    "avgOrders": 0.256198347107438
  },
  {
    "dayOfWeek": 3,
    "hour": 16,
    "dayCount": 118,
    "totalRevenue": 3486.409999999999,
    "totalOrders": 32,
    "avgRevenue": 29.545847457627108,
    "avgOrders": 0.2711864406779661
  },
  {
    "dayOfWeek": 4,
    "hour": 1,
    "dayCount": 114,
    "totalRevenue": 304.23999999999995,
    "totalOrders": 6,
    "avgRevenue": 2.668771929824561,
    "avgOrders": 0.05263157894736842
  },
  {
    "dayOfWeek": 4,
    "hour": 7,
    "dayCount": 114,
    "totalRevenue": 782.53,
    "totalOrders": 18,
    "avgRevenue": 6.864298245614035,
    "avgOrders": 0.15789473684210525
  },
  {
    "dayOfWeek": 4,
    "hour": 23,
    "dayCount": 114,
    "totalRevenue": 2028.9099999999999,
    "totalOrders": 26,
    "avgRevenue": 17.797456140350874,
    "avgOrders": 0.22807017543859648
  },
  {
    "dayOfWeek": 5,
    "hour": 21,
    "dayCount": 114,
    "totalRevenue": 2002.2400000000002,
    "totalOrders": 24,
    "avgRevenue": 17.563508771929826,
    "avgOrders": 0.21052631578947367
  },
  {
    "dayOfWeek": 6,
    "hour": 12,
    "dayCount": 113,
    "totalRevenue": 1392.8600000000001,
    "totalOrders": 20,
    "avgRevenue": 12.326194690265488,
    "avgOrders": 0.17699115044247787
  },
  {
    "dayOfWeek": 0,
    "hour": 16,
    "dayCount": 113,
    "totalRevenue": 2132.5099999999998,
    "totalOrders": 29,
    "avgRevenue": 18.871769911504423,
    "avgOrders": 0.25663716814159293
  },
  {
    "dayOfWeek": 2,
    "hour": 17,
    "dayCount": 121,
    "totalRevenue": 3674.979999999999,
    "totalOrders": 29,
    "avgRevenue": 30.371735537190077,
    "avgOrders": 0.2396694214876033
  },
  {
    "dayOfWeek": 3,
    "hour": 8,
    "dayCount": 118,
    "totalRevenue": 2517.8900000000003,
    "totalOrders": 26,
    "avgRevenue": 21.33805084745763,
    "avgOrders": 0.22033898305084745
  },
  {
    "dayOfWeek": 3,
    "hour": 17,
    "dayCount": 118,
    "totalRevenue": 3089.86,
    "totalOrders": 24,
    "avgRevenue": 26.185254237288138,
    "avgOrders": 0.2033898305084746
  },
  {
    "dayOfWeek": 3,
    "hour": 18,
    "dayCount": 118,
    "totalRevenue": 3254.609999999999,
    "totalOrders": 36,
    "avgRevenue": 27.581440677966096,
    "avgOrders": 0.3050847457627119
  },
  {
    "dayOfWeek": 5,
    "hour": 5,
    "dayCount": 114,
    "totalRevenue": 451.17,
    "totalOrders": 5,
    "avgRevenue": 3.9576315789473684,
    "avgOrders": 0.043859649122807015
  },
  {
    "dayOfWeek": 5,
    "hour": 8,
    "dayCount": 114,
    "totalRevenue": 2624.1000000000004,
    "totalOrders": 29,
    "avgRevenue": 23.01842105263158,
    "avgOrders": 0.2543859649122807
  },
  {
    "dayOfWeek": 5,
    "hour": 10,
    "dayCount": 114,
    "totalRevenue": 4871.8099999999995,
    "totalOrders": 36,
    "avgRevenue": 42.735175438596485,
    "avgOrders": 0.3157894736842105
  },
  {
    "dayOfWeek": 5,
    "hour": 17,
    "dayCount": 114,
    "totalRevenue": 4345.9,
    "totalOrders": 27,
    "avgRevenue": 38.1219298245614,
    "avgOrders": 0.23684210526315788
  },
  {
    "dayOfWeek": 6,
    "hour": 0,
    "dayCount": 113,
    "totalRevenue": 3052.6499999999996,
    "totalOrders": 12,
    "avgRevenue": 27.0146017699115,
    "avgOrders": 0.10619469026548672
  },
  {
    "dayOfWeek": 6,
    "hour": 20,
    "dayCount": 113,
    "totalRevenue": 2591.28,
    "totalOrders": 26,
    "avgRevenue": 22.931681415929205,
    "avgOrders": 0.23008849557522124
  },
  {
    "dayOfWeek": 0,
    "hour": 19,
    "dayCount": 113,
    "totalRevenue": 3429.859999999999,
    "totalOrders": 36,
    "avgRevenue": 30.352743362831852,
    "avgOrders": 0.3185840707964602
  },
  {
    "dayOfWeek": 1,
    "hour": 13,
    "dayCount": 117,
    "totalRevenue": 3243.5400000000004,
    "totalOrders": 38,
    "avgRevenue": 27.722564102564107,
    "avgOrders": 0.3247863247863248
  },
  {
    "dayOfWeek": 2,
    "hour": 9,
    "dayCount": 121,
    "totalRevenue": 3025.3199999999997,
    "totalOrders": 25,
    "avgRevenue": 25.002644628099173,
    "avgOrders": 0.2066115702479339
  },
  {
    "dayOfWeek": 3,
    "hour": 19,
    "dayCount": 118,
    "totalRevenue": 1875.8599999999997,
    "totalOrders": 28,
    "avgRevenue": 15.897118644067794,
    "avgOrders": 0.23728813559322035
  },
  {
    "dayOfWeek": 4,
    "hour": 18,
    "dayCount": 114,
    "totalRevenue": 2402.0800000000004,
    "totalOrders": 21,
    "avgRevenue": 21.070877192982458,
    "avgOrders": 0.18421052631578946
  },
  {
    "dayOfWeek": 6,
    "hour": 19,
    "dayCount": 113,
    "totalRevenue": 2571.3099999999995,
    "totalOrders": 18,
    "avgRevenue": 22.754955752212386,
    "avgOrders": 0.1592920353982301
  },
  {
    "dayOfWeek": 0,
    "hour": 22,
    "dayCount": 113,
    "totalRevenue": 3145.1499999999987,
    "totalOrders": 29,
    "avgRevenue": 27.833185840707955,
    "avgOrders": 0.25663716814159293
  },
  {
    "dayOfWeek": 1,
    "hour": 8,
    "dayCount": 117,
    "totalRevenue": 3329.9299999999994,
    "totalOrders": 28,
    "avgRevenue": 28.460940170940166,
    "avgOrders": 0.23931623931623933
  },
  {
    "dayOfWeek": 1,
    "hour": 10,
    "dayCount": 117,
    "totalRevenue": 3028.7799999999993,
    "totalOrders": 38,
    "avgRevenue": 25.88700854700854,
    "avgOrders": 0.3247863247863248
  },
  {
    "dayOfWeek": 1,
    "hour": 15,
    "dayCount": 117,
    "totalRevenue": 2600.1700000000005,
    "totalOrders": 34,
    "avgRevenue": 22.223675213675218,
    "avgOrders": 0.2905982905982906
  },
  {
    "dayOfWeek": 1,
    "hour": 18,
    "dayCount": 117,
    "totalRevenue": 2644.9500000000003,
    "totalOrders": 38,
    "avgRevenue": 22.60641025641026,
    "avgOrders": 0.3247863247863248
  },
  {
    "dayOfWeek": 2,
    "hour": 10,
    "dayCount": 121,
    "totalRevenue": 2863.2,
    "totalOrders": 22,
    "avgRevenue": 23.66280991735537,
    "avgOrders": 0.18181818181818182
  },
  {
    "dayOfWeek": 4,
    "hour": 8,
    "dayCount": 114,
    "totalRevenue": 2508.9100000000003,
    "totalOrders": 22,
    "avgRevenue": 22.007982456140354,
    "avgOrders": 0.19298245614035087
  },
  {
    "dayOfWeek": 5,
    "hour": 15,
    "dayCount": 114,
    "totalRevenue": 2004.1399999999996,
    "totalOrders": 28,
    "avgRevenue": 17.580175438596488,
    "avgOrders": 0.24561403508771928
  },
  {
    "dayOfWeek": 5,
    "hour": 23,
    "dayCount": 114,
    "totalRevenue": 1700.1900000000003,
    "totalOrders": 24,
    "avgRevenue": 14.913947368421056,
    "avgOrders": 0.21052631578947367
  },
  {
    "dayOfWeek": 1,
    "hour": 11,
    "dayCount": 117,
    "totalRevenue": 3138.3900000000003,
    "totalOrders": 37,
    "avgRevenue": 26.823846153846155,
    "avgOrders": 0.3162393162393162
  },
  {
    "dayOfWeek": 1,
    "hour": 22,
    "dayCount": 117,
    "totalRevenue": 3206.75,
    "totalOrders": 31,
    "avgRevenue": 27.40811965811966,
    "avgOrders": 0.26495726495726496
  },
  {
    "dayOfWeek": 2,
    "hour": 6,
    "dayCount": 121,
    "totalRevenue": 314.99,
    "totalOrders": 5,
    "avgRevenue": 2.6032231404958677,
    "avgOrders": 0.04132231404958678
  },
  {
    "dayOfWeek": 2,
    "hour": 13,
    "dayCount": 121,
    "totalRevenue": 4196.02,
    "totalOrders": 25,
    "avgRevenue": 34.67785123966942,
    "avgOrders": 0.2066115702479339
  },
  {
    "dayOfWeek": 2,
    "hour": 16,
    "dayCount": 121,
    "totalRevenue": 1821.3899999999999,
    "totalOrders": 21,
    "avgRevenue": 15.05280991735537,
    "avgOrders": 0.17355371900826447
  },
  {
    "dayOfWeek": 3,
    "hour": 6,
    "dayCount": 118,
    "totalRevenue": 595.02,
    "totalOrders": 9,
    "avgRevenue": 5.042542372881356,
    "avgOrders": 0.07627118644067797
  },
  {
    "dayOfWeek": 4,
    "hour": 15,
    "dayCount": 114,
    "totalRevenue": 1926.5299999999997,
    "totalOrders": 28,
    "avgRevenue": 16.899385964912277,
    "avgOrders": 0.24561403508771928
  },
  {
    "dayOfWeek": 5,
    "hour": 11,
    "dayCount": 114,
    "totalRevenue": 4398.549999999999,
    "totalOrders": 26,
    "avgRevenue": 38.58377192982456,
    "avgOrders": 0.22807017543859648
  },
  {
    "dayOfWeek": 5,
    "hour": 12,
    "dayCount": 114,
    "totalRevenue": 3946.0199999999995,
    "totalOrders": 29,
    "avgRevenue": 34.61421052631579,
    "avgOrders": 0.2543859649122807
  },
  {
    "dayOfWeek": 5,
    "hour": 22,
    "dayCount": 114,
    "totalRevenue": 2548.119999999999,
    "totalOrders": 27,
    "avgRevenue": 22.351929824561395,
    "avgOrders": 0.23684210526315788
  },
  {
    "dayOfWeek": 6,
    "hour": 7,
    "dayCount": 113,
    "totalRevenue": 655.01,
    "totalOrders": 7,
    "avgRevenue": 5.796548672566372,
    "avgOrders": 0.061946902654867256
  },
  {
    "dayOfWeek": 0,
    "hour": 8,
    "dayCount": 113,
    "totalRevenue": 584.52,
    "totalOrders": 8,
    "avgRevenue": 5.172743362831858,
    "avgOrders": 0.07079646017699115
  },
  {
    "dayOfWeek": 1,
    "hour": 0,
    "dayCount": 117,
    "totalRevenue": 2632.48,
    "totalOrders": 17,
    "avgRevenue": 22.49982905982906,
    "avgOrders": 0.1452991452991453
  },
  {
    "dayOfWeek": 1,
    "hour": 17,
    "dayCount": 117,
    "totalRevenue": 3617.5099999999998,
    "totalOrders": 33,
    "avgRevenue": 30.918888888888887,
    "avgOrders": 0.28205128205128205
  },
  {
    "dayOfWeek": 1,
    "hour": 19,
    "dayCount": 117,
    "totalRevenue": 1773.8799999999999,
    "totalOrders": 26,
    "avgRevenue": 15.16136752136752,
    "avgOrders": 0.2222222222222222
  },
  {
    "dayOfWeek": 2,
    "hour": 18,
    "dayCount": 121,
    "totalRevenue": 1880.91,
    "totalOrders": 21,
    "avgRevenue": 15.544710743801653,
    "avgOrders": 0.17355371900826447
  },
  {
    "dayOfWeek": 3,
    "hour": 11,
    "dayCount": 118,
    "totalRevenue": 4103.320000000001,
    "totalOrders": 33,
    "avgRevenue": 34.77389830508475,
    "avgOrders": 0.2796610169491525
  },
  {
    "dayOfWeek": 4,
    "hour": 6,
    "dayCount": 114,
    "totalRevenue": 267.96000000000004,
    "totalOrders": 6,
    "avgRevenue": 2.350526315789474,
    "avgOrders": 0.05263157894736842
  },
  {
    "dayOfWeek": 4,
    "hour": 17,
    "dayCount": 114,
    "totalRevenue": 2578.52,
    "totalOrders": 25,
    "avgRevenue": 22.61859649122807,
    "avgOrders": 0.21929824561403508
  },
  {
    "dayOfWeek": 6,
    "hour": 8,
    "dayCount": 113,
    "totalRevenue": 4684,
    "totalOrders": 28,
    "avgRevenue": 41.45132743362832,
    "avgOrders": 0.24778761061946902
  },
  {
    "dayOfWeek": 6,
    "hour": 22,
    "dayCount": 113,
    "totalRevenue": 1981.69,
    "totalOrders": 26,
    "avgRevenue": 17.5370796460177,
    "avgOrders": 0.23008849557522124
  },
  {
    "dayOfWeek": 1,
    "hour": 16,
    "dayCount": 117,
    "totalRevenue": 3783.4400000000005,
    "totalOrders": 33,
    "avgRevenue": 32.337094017094024,
    "avgOrders": 0.28205128205128205
  },
  {
    "dayOfWeek": 2,
    "hour": 12,
    "dayCount": 121,
    "totalRevenue": 5422.88,
    "totalOrders": 31,
    "avgRevenue": 44.81719008264463,
    "avgOrders": 0.256198347107438
  },
  {
    "dayOfWeek": 3,
    "hour": 14,
    "dayCount": 118,
    "totalRevenue": 4016.759999999999,
    "totalOrders": 49,
    "avgRevenue": 34.04033898305084,
    "avgOrders": 0.4152542372881356
  },
  {
    "dayOfWeek": 5,
    "hour": 6,
    "dayCount": 114,
    "totalRevenue": 685.8799999999999,
    "totalOrders": 9,
    "avgRevenue": 6.016491228070175,
    "avgOrders": 0.07894736842105263
  },
  {
    "dayOfWeek": 5,
    "hour": 19,
    "dayCount": 114,
    "totalRevenue": 2952.3999999999996,
    "totalOrders": 30,
    "avgRevenue": 25.898245614035083,
    "avgOrders": 0.2631578947368421
  },
  {
    "dayOfWeek": 5,
    "hour": 20,
    "dayCount": 114,
    "totalRevenue": 2255.44,
    "totalOrders": 29,
    "avgRevenue": 19.78456140350877,
    "avgOrders": 0.2543859649122807
  },
  {
    "dayOfWeek": 6,
    "hour": 18,
    "dayCount": 113,
    "totalRevenue": 1760.8200000000002,
    "totalOrders": 13,
    "avgRevenue": 15.582477876106196,
    "avgOrders": 0.11504424778761062
  },
  {
    "dayOfWeek": 0,
    "hour": 6,
    "dayCount": 113,
    "totalRevenue": 123.18,
    "totalOrders": 2,
    "avgRevenue": 1.0900884955752213,
    "avgOrders": 0.017699115044247787
  },
  {
    "dayOfWeek": 0,
    "hour": 12,
    "dayCount": 113,
    "totalRevenue": 1150.15,
    "totalOrders": 20,
    "avgRevenue": 10.178318584070798,
    "avgOrders": 0.17699115044247787
  },
  {
    "dayOfWeek": 0,
    "hour": 23,
    "dayCount": 113,
    "totalRevenue": 3877.4099999999994,
    "totalOrders": 21,
    "avgRevenue": 34.3133628318584,
    "avgOrders": 0.18584070796460178
  },
  {
    "dayOfWeek": 1,
    "hour": 14,
    "dayCount": 117,
    "totalRevenue": 2814.09,
    "totalOrders": 31,
    "avgRevenue": 24.052051282051284,
    "avgOrders": 0.26495726495726496
  },
  {
    "dayOfWeek": 4,
    "hour": 19,
    "dayCount": 114,
    "totalRevenue": 2217.98,
    "totalOrders": 24,
    "avgRevenue": 19.455964912280702,
    "avgOrders": 0.21052631578947367
  },
  {
    "dayOfWeek": 6,
    "hour": 16,
    "dayCount": 113,
    "totalRevenue": 1963.1099999999997,
    "totalOrders": 24,
    "avgRevenue": 17.372654867256635,
    "avgOrders": 0.21238938053097345
  },
  {
    "dayOfWeek": 6,
    "hour": 17,
    "dayCount": 113,
    "totalRevenue": 2472.98,
    "totalOrders": 22,
    "avgRevenue": 21.88477876106195,
    "avgOrders": 0.19469026548672566
  },
  {
    "dayOfWeek": 6,
    "hour": 21,
    "dayCount": 113,
    "totalRevenue": 2147.8,
    "totalOrders": 26,
    "avgRevenue": 19.0070796460177,
    "avgOrders": 0.23008849557522124
  },
  {
    "dayOfWeek": 0,
    "hour": 10,
    "dayCount": 113,
    "totalRevenue": 1201.71,
    "totalOrders": 17,
    "avgRevenue": 10.634601769911505,
    "avgOrders": 0.1504424778761062
  },
  {
    "dayOfWeek": 0,
    "hour": 21,
    "dayCount": 113,
    "totalRevenue": 6075.499999999998,
    "totalOrders": 39,
    "avgRevenue": 53.7654867256637,
    "avgOrders": 0.34513274336283184
  },
  {
    "dayOfWeek": 2,
    "hour": 23,
    "dayCount": 121,
    "totalRevenue": 1690.13,
    "totalOrders": 18,
    "avgRevenue": 13.96801652892562,
    "avgOrders": 0.1487603305785124
  },
  {
    "dayOfWeek": 4,
    "hour": 10,
    "dayCount": 114,
    "totalRevenue": 3499.8300000000004,
    "totalOrders": 26,
    "avgRevenue": 30.70026315789474,
    "avgOrders": 0.22807017543859648
  },
  {
    "dayOfWeek": 4,
    "hour": 11,
    "dayCount": 114,
    "totalRevenue": 2672.47,
    "totalOrders": 23,
    "avgRevenue": 23.442719298245613,
    "avgOrders": 0.20175438596491227
  },
  {
    "dayOfWeek": 4,
    "hour": 21,
    "dayCount": 114,
    "totalRevenue": 3244.96,
    "totalOrders": 23,
    "avgRevenue": 28.46456140350877,
    "avgOrders": 0.20175438596491227
  },
  {
    "dayOfWeek": 0,
    "hour": 0,
    "dayCount": 113,
    "totalRevenue": 1208.9999999999998,
    "totalOrders": 14,
    "avgRevenue": 10.699115044247785,
    "avgOrders": 0.12389380530973451
  },
  {
    "dayOfWeek": 1,
    "hour": 5,
    "dayCount": 117,
    "totalRevenue": 47.779999999999994,
    "totalOrders": 2,
    "avgRevenue": 0.4083760683760683,
    "avgOrders": 0.017094017094017096
  },
  {
    "dayOfWeek": 1,
    "hour": 12,
    "dayCount": 117,
    "totalRevenue": 5666.25,
    "totalOrders": 34,
    "avgRevenue": 48.42948717948718,
    "avgOrders": 0.2905982905982906
  },
  {
    "dayOfWeek": 3,
    "hour": 1,
    "dayCount": 118,
    "totalRevenue": 1730.7400000000002,
    "totalOrders": 9,
    "avgRevenue": 14.667288135593223,
    "avgOrders": 0.07627118644067797
  },
  {
    "dayOfWeek": 4,
    "hour": 9,
    "dayCount": 114,
    "totalRevenue": 3533.709999999999,
    "totalOrders": 31,
    "avgRevenue": 30.99745614035087,
    "avgOrders": 0.2719298245614035
  },
  {
    "dayOfWeek": 4,
    "hour": 22,
    "dayCount": 114,
    "totalRevenue": 1878.74,
    "totalOrders": 36,
    "avgRevenue": 16.48017543859649,
    "avgOrders": 0.3157894736842105
  },
  {
    "dayOfWeek": 5,
    "hour": 14,
    "dayCount": 114,
    "totalRevenue": 3829.77,
    "totalOrders": 34,
    "avgRevenue": 33.59447368421053,
    "avgOrders": 0.2982456140350877
  },
  {
    "dayOfWeek": 5,
    "hour": 16,
    "dayCount": 114,
    "totalRevenue": 2031.4699999999996,
    "totalOrders": 24,
    "avgRevenue": 17.81991228070175,
    "avgOrders": 0.21052631578947367
  },
  {
    "dayOfWeek": 5,
    "hour": 18,
    "dayCount": 114,
    "totalRevenue": 3369.179999999999,
    "totalOrders": 27,
    "avgRevenue": 29.55421052631578,
    "avgOrders": 0.23684210526315788
  },
  {
    "dayOfWeek": 6,
    "hour": 13,
    "dayCount": 113,
    "totalRevenue": 1421.84,
    "totalOrders": 20,
    "avgRevenue": 12.582654867256636,
    "avgOrders": 0.17699115044247787
  },
  {
    "dayOfWeek": 0,
    "hour": 14,
    "dayCount": 113,
    "totalRevenue": 1665.8,
    "totalOrders": 24,
    "avgRevenue": 14.741592920353982,
    "avgOrders": 0.21238938053097345
  },
  {
    "dayOfWeek": 0,
    "hour": 15,
    "dayCount": 113,
    "totalRevenue": 2279.7799999999997,
    "totalOrders": 24,
    "avgRevenue": 20.175044247787607,
    "avgOrders": 0.21238938053097345
  },
  {
    "dayOfWeek": 2,
    "hour": 0,
    "dayCount": 121,
    "totalRevenue": 416.05,
    "totalOrders": 8,
    "avgRevenue": 3.438429752066116,
    "avgOrders": 0.06611570247933884
  },
  {
    "dayOfWeek": 3,
    "hour": 10,
    "dayCount": 118,
    "totalRevenue": 4059.84,
    "totalOrders": 40,
    "avgRevenue": 34.40542372881356,
    "avgOrders": 0.3389830508474576
  },
  {
    "dayOfWeek": 3,
    "hour": 22,
    "dayCount": 118,
    "totalRevenue": 2357.5699999999997,
    "totalOrders": 30,
    "avgRevenue": 19.979406779661016,
    "avgOrders": 0.2542372881355932
  },
  {
    "dayOfWeek": 4,
    "hour": 13,
    "dayCount": 114,
    "totalRevenue": 2429.4900000000007,
    "totalOrders": 34,
    "avgRevenue": 21.31131578947369,
    "avgOrders": 0.2982456140350877
  },
  {
    "dayOfWeek": 5,
    "hour": 1,
    "dayCount": 114,
    "totalRevenue": 632.51,
    "totalOrders": 6,
    "avgRevenue": 5.548333333333333,
    "avgOrders": 0.05263157894736842
  },
  {
    "dayOfWeek": 5,
    "hour": 13,
    "dayCount": 114,
    "totalRevenue": 3597.349999999999,
    "totalOrders": 29,
    "avgRevenue": 31.555701754385957,
    "avgOrders": 0.2543859649122807
  },
  {
    "dayOfWeek": 1,
    "hour": 1,
    "dayCount": 117,
    "totalRevenue": 575.1999999999999,
    "totalOrders": 8,
    "avgRevenue": 4.916239316239316,
    "avgOrders": 0.06837606837606838
  },
  {
    "dayOfWeek": 1,
    "hour": 23,
    "dayCount": 117,
    "totalRevenue": 1907.63,
    "totalOrders": 19,
    "avgRevenue": 16.304529914529915,
    "avgOrders": 0.1623931623931624
  },
  {
    "dayOfWeek": 2,
    "hour": 8,
    "dayCount": 121,
    "totalRevenue": 3861.06,
    "totalOrders": 20,
    "avgRevenue": 31.909586776859502,
    "avgOrders": 0.1652892561983471
  },
  {
    "dayOfWeek": 4,
    "hour": 0,
    "dayCount": 114,
    "totalRevenue": 458.21000000000004,
    "totalOrders": 8,
    "avgRevenue": 4.019385964912281,
    "avgOrders": 0.07017543859649122
  },
  {
    "dayOfWeek": 2,
    "hour": 15,
    "dayCount": 121,
    "totalRevenue": 3992.8000000000006,
    "totalOrders": 26,
    "avgRevenue": 32.99834710743802,
    "avgOrders": 0.21487603305785125
  },
  {
    "dayOfWeek": 0,
    "hour": 9,
    "dayCount": 113,
    "totalRevenue": 2200.21,
    "totalOrders": 20,
    "avgRevenue": 19.47088495575221,
    "avgOrders": 0.17699115044247787
  },
  {
    "dayOfWeek": 3,
    "hour": 23,
    "dayCount": 118,
    "totalRevenue": 2542.8800000000006,
    "totalOrders": 22,
    "avgRevenue": 21.54983050847458,
    "avgOrders": 0.1864406779661017
  },
  {
    "dayOfWeek": 0,
    "hour": 11,
    "dayCount": 113,
    "totalRevenue": 847.6500000000001,
    "totalOrders": 13,
    "avgRevenue": 7.50132743362832,
    "avgOrders": 0.11504424778761062
  },
  {
    "dayOfWeek": 3,
    "hour": 7,
    "dayCount": 118,
    "totalRevenue": 1967.2200000000003,
    "totalOrders": 14,
    "avgRevenue": 16.671355932203394,
    "avgOrders": 0.11864406779661017
  },
  {
    "dayOfWeek": 1,
    "hour": 6,
    "dayCount": 117,
    "totalRevenue": 723.26,
    "totalOrders": 9,
    "avgRevenue": 6.181709401709401,
    "avgOrders": 0.07692307692307693
  },
  {
    "dayOfWeek": 3,
    "hour": 2,
    "dayCount": 118,
    "totalRevenue": 188.68,
    "totalOrders": 2,
    "avgRevenue": 1.5989830508474576,
    "avgOrders": 0.01694915254237288
  },
  {
    "dayOfWeek": 5,
    "hour": 9,
    "dayCount": 114,
    "totalRevenue": 2543.14,
    "totalOrders": 25,
    "avgRevenue": 22.308245614035087,
    "avgOrders": 0.21929824561403508
  },
  {
    "dayOfWeek": 0,
    "hour": 1,
    "dayCount": 113,
    "totalRevenue": 172.76000000000002,
    "totalOrders": 6,
    "avgRevenue": 1.5288495575221241,
    "avgOrders": 0.05309734513274336
  },
  {
    "dayOfWeek": 4,
    "hour": 20,
    "dayCount": 114,
    "totalRevenue": 629.97,
    "totalOrders": 17,
    "avgRevenue": 5.526052631578947,
    "avgOrders": 0.14912280701754385
  },
  {
    "dayOfWeek": 0,
    "hour": 20,
    "dayCount": 113,
    "totalRevenue": 3481.2499999999995,
    "totalOrders": 39,
    "avgRevenue": 30.8075221238938,
    "avgOrders": 0.34513274336283184
  },
  {
    "dayOfWeek": 6,
    "hour": 10,
    "dayCount": 113,
    "totalRevenue": 1299.6699999999998,
    "totalOrders": 16,
    "avgRevenue": 11.50150442477876,
    "avgOrders": 0.1415929203539823
  },
  {
    "dayOfWeek": 5,
    "hour": 2,
    "dayCount": 114,
    "totalRevenue": 352.14,
    "totalOrders": 3,
    "avgRevenue": 3.0889473684210524,
    "avgOrders": 0.02631578947368421
  },
  {
    "dayOfWeek": 2,
    "hour": 7,
    "dayCount": 121,
    "totalRevenue": 1226.26,
    "totalOrders": 11,
    "avgRevenue": 10.134380165289256,
    "avgOrders": 0.09090909090909091
  },
  {
    "dayOfWeek": 5,
    "hour": 7,
    "dayCount": 114,
    "totalRevenue": 699.0899999999999,
    "totalOrders": 10,
    "avgRevenue": 6.132368421052631,
    "avgOrders": 0.08771929824561403
  },
  {
    "dayOfWeek": 0,
    "hour": 4,
    "dayCount": 113,
    "totalRevenue": 166.08999999999997,
    "totalOrders": 2,
    "avgRevenue": 1.4698230088495574,
    "avgOrders": 0.017699115044247787
  },
  {
    "dayOfWeek": 4,
    "hour": 2,
    "dayCount": 114,
    "totalRevenue": 85.69,
    "totalOrders": 2,
    "avgRevenue": 0.7516666666666666,
    "avgOrders": 0.017543859649122806
  },
  {
    "dayOfWeek": 6,
    "hour": 9,
    "dayCount": 113,
    "totalRevenue": 673.2500000000001,
    "totalOrders": 13,
    "avgRevenue": 5.957964601769913,
    "avgOrders": 0.11504424778761062
  },
  {
    "dayOfWeek": 6,
    "hour": 5,
    "dayCount": 113,
    "totalRevenue": 564.3,
    "totalOrders": 4,
    "avgRevenue": 4.993805309734513,
    "avgOrders": 0.035398230088495575
  },
  {
    "dayOfWeek": 3,
    "hour": 0,
    "dayCount": 118,
    "totalRevenue": 1547.0500000000004,
    "totalOrders": 11,
    "avgRevenue": 13.110593220338986,
    "avgOrders": 0.09322033898305085
  },
  {
    "dayOfWeek": 2,
    "hour": 1,
    "dayCount": 121,
    "totalRevenue": 410.63,
    "totalOrders": 6,
    "avgRevenue": 3.3936363636363636,
    "avgOrders": 0.049586776859504134
  },
  {
    "dayOfWeek": 0,
    "hour": 7,
    "dayCount": 113,
    "totalRevenue": 603.01,
    "totalOrders": 8,
    "avgRevenue": 5.336371681415929,
    "avgOrders": 0.07079646017699115
  },
  {
    "dayOfWeek": 4,
    "hour": 12,
    "dayCount": 114,
    "totalRevenue": 1462.2600000000002,
    "totalOrders": 23,
    "avgRevenue": 12.82684210526316,
    "avgOrders": 0.20175438596491227
  },
  {
    "dayOfWeek": 1,
    "hour": 2,
    "dayCount": 117,
    "totalRevenue": 139.24,
    "totalOrders": 3,
    "avgRevenue": 1.1900854700854702,
    "avgOrders": 0.02564102564102564
  },
  {
    "dayOfWeek": 2,
    "hour": 5,
    "dayCount": 121,
    "totalRevenue": 182.77999999999997,
    "totalOrders": 1,
    "avgRevenue": 1.510578512396694,
    "avgOrders": 0.008264462809917356
  },
  {
    "dayOfWeek": 0,
    "hour": 5,
    "dayCount": 113,
    "totalRevenue": 32.19,
    "totalOrders": 2,
    "avgRevenue": 0.2848672566371681,
    "avgOrders": 0.017699115044247787
  },
  {
    "dayOfWeek": 1,
    "hour": 4,
    "dayCount": 117,
    "totalRevenue": 69.03999999999999,
    "totalOrders": 3,
    "avgRevenue": 0.59008547008547,
    "avgOrders": 0.02564102564102564
  },
  {
    "dayOfWeek": 6,
    "hour": 1,
    "dayCount": 113,
    "totalRevenue": 275.58,
    "totalOrders": 6,
    "avgRevenue": 2.4387610619469027,
    "avgOrders": 0.05309734513274336
  },
  {
    "dayOfWeek": 5,
    "hour": 4,
    "dayCount": 114,
    "totalRevenue": 204.67000000000002,
    "totalOrders": 3,
    "avgRevenue": 1.7953508771929827,
    "avgOrders": 0.02631578947368421
  },
  {
    "dayOfWeek": 6,
    "hour": 3,
    "dayCount": 113,
    "totalRevenue": 475.5699999999999,
    "totalOrders": 2,
    "avgRevenue": 4.2085840707964595,
    "avgOrders": 0.017699115044247787
  },
  {
    "dayOfWeek": 5,
    "hour": 0,
    "dayCount": 114,
    "totalRevenue": 2151.1800000000003,
    "totalOrders": 11,
    "avgRevenue": 18.87,
    "avgOrders": 0.09649122807017543
  },
  {
    "dayOfWeek": 5,
    "hour": 3,
    "dayCount": 114,
    "totalRevenue": 185.45,
    "totalOrders": 2,
    "avgRevenue": 1.6267543859649123,
    "avgOrders": 0.017543859649122806
  },
  {
    "dayOfWeek": 2,
    "hour": 2,
    "dayCount": 121,
    "totalRevenue": 73.26,
    "totalOrders": 2,
    "avgRevenue": 0.6054545454545455,
    "avgOrders": 0.01652892561983471
  },
  {
    "dayOfWeek": 2,
    "hour": 3,
    "dayCount": 121,
    "totalRevenue": 527.54,
    "totalOrders": 2,
    "avgRevenue": 4.359834710743801,
    "avgOrders": 0.01652892561983471
  },
  {
    "dayOfWeek": 4,
    "hour": 4,
    "dayCount": 114,
    "totalRevenue": 141.64000000000001,
    "totalOrders": 5,
    "avgRevenue": 1.2424561403508774,
    "avgOrders": 0.043859649122807015
  },
  {
    "dayOfWeek": 1,
    "hour": 3,
    "dayCount": 117,
    "totalRevenue": 92.99,
    "totalOrders": 3,
    "avgRevenue": 0.7947863247863247,
    "avgOrders": 0.02564102564102564
  },
  {
    "dayOfWeek": 3,
    "hour": 5,
    "dayCount": 118,
    "totalRevenue": 71,
    "totalOrders": 2,
    "avgRevenue": 0.6016949152542372,
    "avgOrders": 0.01694915254237288
  },
  {
    "dayOfWeek": 6,
    "hour": 2,
    "dayCount": 113,
    "totalRevenue": 401.73,
    "totalOrders": 3,
    "avgRevenue": 3.555132743362832,
    "avgOrders": 0.02654867256637168
  },
  {
    "dayOfWeek": 4,
    "hour": 5,
    "dayCount": 114,
    "totalRevenue": 125.79,
    "totalOrders": 3,
    "avgRevenue": 1.103421052631579,
    "avgOrders": 0.02631578947368421
  },
  {
    "dayOfWeek": 6,
    "hour": 4,
    "dayCount": 113,
    "totalRevenue": 8.5,
    "totalOrders": 1,
    "avgRevenue": 0.0752212389380531,
    "avgOrders": 0.008849557522123894
  },
  {
    "dayOfWeek": 4,
    "hour": 3,
    "dayCount": 114,
    "totalRevenue": 103.82,
    "totalOrders": 2,
    "avgRevenue": 0.9107017543859649,
    "avgOrders": 0.017543859649122806
  },
  {
    "dayOfWeek": 6,
    "hour": 6,
    "dayCount": 113,
    "totalRevenue": 937.52,
    "totalOrders": 2,
    "avgRevenue": 8.296637168141594,
    "avgOrders": 0.017699115044247787
  }
];
