// Auto-generated by scripts/fetchShoptetData.js — last update: 2026-04-17
// NL: per-order product basket value bez DPH (EUR), cancelled excluded

export interface OrderValueRecord {
  date: string;
  value: number;
}

export const orderValueDataNL: OrderValueRecord[] = [
  {
    "date": "2026-04-09",
    "value": 579.38
  },
  {
    "date": "2026-04-09",
    "value": 28.96
  },
  {
    "date": "2026-04-09",
    "value": 98.38999999999999
  },
  {
    "date": "2026-04-09",
    "value": 49.2
  },
  {
    "date": "2026-04-09",
    "value": 68.31
  },
  {
    "date": "2026-04-10",
    "value": 26.02
  },
  {
    "date": "2026-04-10",
    "value": 28.38
  },
  {
    "date": "2026-04-11",
    "value": 17.11
  },
  {
    "date": "2026-04-11",
    "value": 0
  },
  {
    "date": "2026-04-13",
    "value": 42.95
  },
  {
    "date": "2026-04-14",
    "value": 54.949999999999996
  },
  {
    "date": "2026-04-14",
    "value": 11
  }
];
